### ISSUE TITLE
Make workaround for Thunderbird not saving current printer 

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#1]
Thunderbird does not seem to save  the last used printer.
See:
https://github.com/cleidigh/printing-tools-ng/commit/5b3468d73212f75329a0edce13f09c70f555235b#commitcomment-39730769
fyi @GeepsJay

**Comment by cleidigh** [comment]
@GeepsJay
okay I think this works
let me know you think
https://github.com/cleidigh/printing-tools-ng/blob/default-printer-test/xpi/printing-tools-ng-0.1.3-dpt-tb.xpi

**Comment by GeepsJay** [comment]
Hi

After the initial setup where i saw a new Microsoft printing info box, it seems to work great. I've printed outside of Thunderbird to various printers, but Thunderbird still prints to Fineprint. I'll have a more thorough test tomorrow where I'll archive lots of emails and let you know how I get on. 

Thank you

Graham

**Comment by cleidigh** [comment]
FYI
posted  cleanup.
I label the option "Default Printer" I think that is just sufficient to do the job.
If one wants to print to another printer you can temporarily do so in the normal print dialog
but subsequent prints will go to the printer set in Printing tools
I will wait for a bit before doing another Release to see if any more issues come in.

@tidebre67 FYI this is the default printer issue I referred to, see comment thread
https://github.com/cleidigh/printing-tools-ng/blob/default-printer-test/xpi/printing-tools-ng-0.1.3-dpt2-tb.xpi
(or higher number)

**Comment by cleidigh** [comment]
@GeepsJay 
@tidebre67
dp3 is fully localized
what to you guys think about releasing? should I wait?
@cleidigh

**Comment by tidebre67** [comment]
as i personally see no issue/s , no need to wait.
    
    tks/brds
    
      
        
        Von:
          Christopher Leidigh <notifications@github.com>
        An:
          cleidigh/printing-tools-ng
          <printing-tools-ng@noreply.github.com>
        Cc: tidebre67
          <Th.Tiedemann@gmx.de> , Mention
          <mention@noreply.github.com>
        Datum:
          Mittwoch, 10. Juni 2020, 05:12
        Betreff:
          [cleidigh/printing-tools-ng] Make workaround for Thunderbird
          notsaving current printer (#1)
        
      
    
    
      
      @GeepsJay
        @tidebre67
        dp3 is fully localized
        what to you guys think about releasing? should I wait?
        @cleidigh
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
        {
        "@context": "http://schema.org",
        "@type": "EmailMessage",
        "potentialAction": {
        "@type": "ViewAction",
        "target":
"https://github.com/cleidigh/printing-tools-ng/issues/1#issuecomment-641693705","url":
"https://github.com/cleidigh/printing-tools-ng/issues/1#issuecomment-641693705",
        "name": "View Issue"
        },
        "description": "View this Issue on GitHub",
        "publisher": {
        "@type": "Organization",
        "name": "GitHub",
        "url": "https://github.com"
        }
        }
        ]

**Comment by cleidigh** [comment]
@tidebre67 
@GeepsJay 
v0.1.3-b2 is final and I will submit
besides the default printer includes many new locales (and some corrections)
https://github.com/cleidigh/printing-tools-ng/blob/v0.1.3-update/xpi/printing-tools-ng-0.1.3-b2-tb.xpi
@cleidigh

**Comment by cleidigh** [comment]
Completed
v0.1.3
