### ISSUE TITLE
How to suppress the Attachments line?

### ISSUE THREAD

**Issue by LindsayGraham41** [cleidigh/printing-tools-ng#10]
I include the attachment name and icon in the headers, but still there is an Attachments line appearing after the email.  This did not appear in Paolo's PrintingTools, and I cannot see how to suppress it in Printing Tools NG.  Am I missing something?

**Comment by cleidigh** [comment]
@LindsayGraham41 
There is no such option now or before. I did not use this function before so I have no historical experience.
If that was the default behavior before, there must be a porting issue.  I will mark it as a unverified bug
and do a little investigation. won't be right away as I'm in the middle of a couple critical items for Thunderbird my other extensions. (Keep this in mind on your enhancements as well)!
Thanks
@cleidigh

**Comment by LindsayGraham41** [comment]
Again, thanks for the prompt reply, Chris.  This is a pretty minor issue, so does not need high priority.  Thanks for all that you do -- I'm truly grateful.

**Comment by cleidigh** [comment]
@LindsayGraham41 
Thanks for the support!  Still, the minor issues which are changes in behavior from original should be corrected.
just have to add it to my huge list ;-)
Christopher

**Comment by cleidigh** [comment]
@LindsayGraham41 
fixed with b5 see #18 
happy new year!
