### ISSUE TITLE
Header sort order inconsistent using zh-CN locale 

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#101]
@KC-T
Can you add some detail and an example, thanks.
@cleidigh

**Comment by KC-T** [comment]
Defined order in English:
Sent
From
To
Cc
Bcc
Subject
Attachment

**Chinese (China):**
Names and order defined by Print-NG:
![Screen Shot 03-21-22 at 04 58 AM](https://user-images.githubusercontent.com/81372892/159185874-f1c8cefb-763e-4b47-aa19-2fc26fc3d77e.PNG)
where "from" should be "来自“。
Actually printed names and order:
![Screen Shot 03-21-22 at 05 50 AM](https://user-images.githubusercontent.com/81372892/159187459-b5192ed3-a97c-42c4-9171-b75af6f1f1e6.PNG)
Cc should use "抄送”
The last one is Bcc and should be moved to follow Cc.


**Chinese (Taiwan):**
Names and order defined by Print-NG:
![Screen Shot 03-21-22 at 04 59 AM](https://user-images.githubusercontent.com/81372892/159185873-33dd7bfe-86c9-45cf-afaa-0bee043c13bf.PNG)
Actually printed names and order:
![Screen Shot 03-21-22 at 05 48 AM](https://user-images.githubusercontent.com/81372892/159187447-24e74014-fed7-4ae6-983e-517f2fe39f90.PNG)
The names are correct but not the order.

**Comment by cleidigh** [comment]
@KC-T 
Excellent, I will work on this, also I will add the tiawanese locale for 2.1.1
The english from in the list may be a clue.  Odd because this has localization within tb.
@cleidigh

**Comment by cleidigh** [comment]
@KC-T 
I found the culprit 
bcc = 密件抄送 printingtoolsng-pengine.js:657:13

this was in the mime header file, perhaps an old form?
@cleidigh

**Comment by KC-T** [comment]
"密送" is a  short form for "密件抄送" for Bcc。

**Comment by cleidigh** [comment]
@KC-T 
That makes sense as the first and last characters are the same, I will learn them eventually!
ok i have the Chinese locale fixed 

<img width="328" alt="Screenshot 2022-03-21 124718" src="https://user-images.githubusercontent.com/25272315/159378353-c4ebfb72-b94d-4d37-98bf-4a8813ff9b9a.png">

I  also added the tiawanese locale, may have issues,
The tb standard uses the latin suffixes for cc and bcc, shall we remove those?
I have to fix the margin  on them.



[printing-tools-ng-2.1.0-dbg6-tb.zip](https://github.com/cleidigh/printing-tools-ng/files/8319729/printing-tools-ng-2.1.0-dbg6-tb.zip)

**Comment by KC-T** [comment]
The above two results are good. Use of Cc or Bcc in place of the characters can be adopted. On the other hand, the characters are good on their own.

Just for your information. Both locales can actually use the same terms but different forms, one traditional and the other simplified. However, different people adopt different terms of the same meanings, ending up with different characters as shown above.

**Comment by KC-T** [comment]
I confirm that both Chinese locale and Taiwanese locale are in order.

**Comment by cleidigh** [comment]
@KC-T 
Just got online, very glad the locales work.
Since we have the option to use cc and bcc in any locale  I think I will try to use the pure Tiawanese characters for printing. This would match how tb displays them.
Do you agree?
@cleidigh

**Comment by cleidigh** [comment]
@KC-T 
Can I close this with b1+ completing this?
@cleidigh

**Comment by KC-T** [comment]
Yes. Thanks!
