### ISSUE TITLE
Print Preview and past problems

### ISSUE THREAD

**Issue by Foxfan100** [cleidigh/printing-tools-ng#108]
W10 Pro 21H2 64-bit, Tbird 91.7.0 (64-bit)

I observe that Tbird will not update from a 32-bit to 64-bit version on its own. I was running the legacy 32-bit version (as 64-bit wasn't originally available), and PTNG would not work at all to an Epson inkjet printer.

I have updated Tbird to the 64-bit version, and it now prints to that printer. However, when selecting the PTNG print preview, either from a highlighted in-folder email, or the email in a full separate tab, I do not see a preview, and the email is immediately spooled to the printer and printed.

If I export or save the email as an eml file, and then File>Open in TB, it does the same i.e. no preview and the file printed. 

Screenshots of settings attached:-
![PTNG-1](https://user-images.githubusercontent.com/22635836/160236320-e75e6b17-6260-4303-84f5-53fd212a0923.jpg)
![ptng-2](https://user-images.githubusercontent.com/22635836/160236321-1342274b-a084-4451-a9ea-f0e1515558e8.jpg)
![ptng-3](https://user-images.githubusercontent.com/22635836/160236323-68d20082-f682-4bcc-80b5-726d51de7dad.jpg)

**Comment by cleidigh** [comment]
@Foxfan100 
Thanks for posting all the options, that always helps.
So first question is what do you observe with other printers, like the MS PDF?
We have seen some drivers mess with formatting, but never preview so I will see if I can reproduce.
@cleidigh

**Comment by Foxfan100** [comment]
I have tried the Preview with the Default printer set as follows:-
1) MS PDF - no preview, goes straight to folder/filename request, but prints a PDF as per settings
2) Cute PDF - no preview, no queue, no request for filename i.e. nothing happens
3) Epson LQ dot matrix - no preview, file sent to queue immediately
4) Epson inkjet - as per 3)

Before I reinstalled TB with the 64-bit version, PTNG would queue and print to the dot matrix, but not to the inkjet. In the case of the latter, the print progress screen appeared and then disappeared, but no file was enqueued.

**Comment by cleidigh** [comment]
@Foxfan100 
I  was developing on x32 so I also installed x64 91.70
I set options per your screen shots.
I get the preview with MS PDF and my HP printer
Not going to preview, but printing is a path but not sure why we are going there.
Let me add some debug in my next beta for v2.1.1 b4
You can track in #106 
@cleidigh

**Comment by cleidigh** [comment]
@Foxfan100 
You can try b4 which has debug output as well as fixes listed in the release status.
Print a short email and capture the console output and post here.
- #106 
@cleidigh

**Comment by cleidigh** [comment]
@Foxfan100 
I think this is all set?
@cleidigh

**Comment by Foxfan100** [comment]
> @Foxfan100 I think this is all set? @cleidigh

I think so.
