### ISSUE TITLE
Spacing between paragraphs

### ISSUE THREAD

**Issue by LindsayGraham41** [cleidigh/printing-tools-ng#11]
This issue existed also with PrintingTools, but I don't think I ever raised it with Paolo.

With most emails, Printing Tools NG faithfully reproduces the layout, including the spacing between paragraphs.  But with some emails, the spaces between paragraphs are ignored so that the paragraphs are all jammed together.  It appears that this happens with emails sent using Outlook (maybe other clients too, but Outlook is the one that I've noticed).

Is a fix possible for this glitch?

**Comment by cleidigh** [comment]
@LindsayGraham41 
Honestly, no idea, another investigation. Outlook has a reputation for quirks, some sort of proprietary formatting could be a possibility.
@cleidigh

**Comment by LindsayGraham41** [comment]
Thanks for the prompt reply, Chris -- it's no big deal, just a bit annoying.  If you need me to send samples, please let me know.

**Comment by cleidigh** [comment]
@LindsayGraham41 
Actually it would be great if you posted an example e-mail (export to EML) here so I can reproduce when I try to address this.
@cleidigh

**Comment by cleidigh** [comment]
@LindsayGraham41 
FYI 78 beta:
https://github.com/cleidigh/printing-tools-ng/issues/18

if you have an example e-mail that would be great, just strange thing is to people have commented on extra  spaces between paragraphs.  problem is somewhat opaque
Christopher
