### ISSUE TITLE
German Translation Header Background Color  

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#112]
with tb new printer engine hint needs new content

GERMAN
Hinweis: "Drucken" >> "Mehr Einstellungen" >> Einstellungen: "Hintergrund drucken" muss aktiviert sein

![printing-tools-ng-2 1 1-b3-tb_Hintergrund](https://user-images.githubusercontent.com/77779094/160276960-e09935ef-bcc9-445a-b304-fa48b210b0b0.PNG)

![printing-tools-ng-2 1 1-b3-tb_Hintergrund_Option](https://user-images.githubusercontent.com/77779094/160276965-1de6f92b-a419-4213-8ebd-58bad70d0896.PNG)

**Comment by cleidigh** [comment]
@RRoenn 
I appreciate your attention to detail! (and your continued help) 
Especially given my 20 or so German vocabulary, most used word on my trips to Germany... Weißbier ;-)

How does this look?

![image](https://user-images.githubusercontent.com/25272315/160298154-784d9260-db50-4760-8036-342442e10d5e.png)

@cleidigh

**Comment by RRoenn** [comment]
You don't need food if you have something to drink 👍

**Comment by cleidigh** [comment]
@RRoenn 
Words I live by 💯
