### ISSUE TITLE
Data format: long and localized problem

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#116]
PrintingTools NG 2.1.0, 2.1.1-b10 & 2.1.1-b11
Thunderbird 91.8.1 ja version 64bit
Windows 10 Pro 21H2 64bit

In 2.1.1-b11, the date format no longer reflects the local format.
It seems that Thunderbird does not reflect the local language date format.

- Version 2.1.0 & 2.1.1-b10
送信日時：　2022年3月9日（水） 22:22

- Version 2.1.1-b11
送信日時：　Wed, 9 Mar 2022 22:22:22 +0900

![送信日時の表記違い](https://user-images.githubusercontent.com/80428201/164463461-4958f0ca-2d69-488f-bf04-36d54046befd.png)

![b-10とb-11の全般設定](https://user-images.githubusercontent.com/80428201/164463496-9c0f8942-4f65-4714-a6c8-5c868c3151a8.png)

![言語と外観 en-US   ja](https://user-images.githubusercontent.com/80428201/164463507-6f3d5a83-48b5-4284-bdad-6c4b5f1551f8.png)

**Comment by cleidigh** [comment]
@kiki-ja 
I found this. It was actually not a problem with the date format, but rather another side issue with header fixup. Tb uses English even in the ja locale.
Ironically b10 worked because I errored and had the fixup off.
I think I am burned out with these tiny edge cases that wreak havoc on the rest of the code!
Anyway b12 should do it, tested in en, ja and zh
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>Tb uses English even in the ja locale.

Yes, that is correct.

I am disappointed that what used to be local time notation in PrintingTools NG 2.1.0 is now English time notation in 2.1.1.
The reason is that version 2.1.0 extended the functionality of Thunderbird itself.

I would be happy if you could make it the same as version 2.1.0 if possible.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Absolutely the localization should be as before, I was explaining what happened.
Did you try b12? I am confident that should fix it.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>Absolutely the localization should be as before, I was explaining what happened.

Understood.

>Did you try b12?

Resolved in b-12.
Thank you very much.

![ローカル日時表記 2 1 1b-12](https://user-images.githubusercontent.com/80428201/164884706-aa07e99c-216e-4043-86eb-870acd806901.png)

If it does not reproduce after the 2.1.1 release, this issue will be closed.

@kiki-ja

**Comment by cleidigh** [comment]
Good that is what we want!
Closing.
@cleidigh
