### ISSUE TITLE
Feature Request/Question:: Set pages to custom

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#118]
Hello @all,
does anyone know how to set the pages to custom by default so that you don't have to switch them from print all pages everytime?
I didn't  find some key in the about:config

@cleidigh 
have you access with the addon to these settings? I usually print only the first or first and second page.
Or can you tell me how to do that?

Thanks in advance.
Greetings from Germany

![grafik](https://user-images.githubusercontent.com/77779094/164887410-dac8544a-2bb7-455c-be99-4b0cacbff308.png)

**Comment by cleidigh** [comment]
@RRoenn 
I am not sure I can pass this to the print process, have to check.
It does bring up the question of duplicating print options within PTNG.
Usually I would be against that, however, there are options that you have to go to the native print dialog and that is not necessarily ideal.
So maybe we should consider these, thoughts?
Cheers back from Providence, good to hear from you!
@cleidigh

**Comment by cleidigh** [comment]
@RRoenn 
I finally have my first test version for this. It is test level not even beta, but I want community feedback before I really clean the ui etc.
Get, track and comments in:
- #152 
- @cleidigh
