### ISSUE TITLE
White space under receipt

### ISSUE THREAD

**Issue by ChadOfDoom2** [cleidigh/printing-tools-ng#12]
I'm using Thunderbird, filtquila, and Printingtools NG to auto print email receipts. When I I go to print preview it shows a ton of white space under the email that also shows when I print a receipt to my printer.

**Comment by cleidigh** [comment]
@ChadOfDoom2 
thanks for the post.
can you post a screenshot  example so I can clearly see the issue. Also identify OS /Version
@cleidigh

**Comment by ChadOfDoom2** [comment]
Thanks, @cleidgh. Here is a stream of what I’m seeing
https://streamable.com/lg2406

On the left you see the receipt it is printing and on the right you see the
print preview that is super long. When I print it the receipt has many feet
of white space under it.

**Comment by ChadOfDoom2** [comment]
Is that enough info for you? Do you have any ideas on this?

**Comment by cleidigh** [comment]
@ChadOfDoom2 
no idea  currently
Couple of things for us to try:
- disable all extensions except printing tools and try to see if there's any difference
- try printing without printing tools
- can you possibly create an example e-mail that displays the problem that you can send or post so I can try and reproduce?
@cleidigh

**Comment by ChadOfDoom2** [comment]
Here is the exact email I'm trying to print.

[image: Front Porch Coffee]
Thank you for your order

Hi chad,

Just to let you know — we've received your order #5528, and it is now being
processed:
[Order #5528] (July 8, 2020)
Product Quantity Price
Buena Vista Guatemala 1 $17.00
Chill Vibes Warm Hearts Graphic Sweatshirt - L 3 $107.85
Subtotal: $124.85
Shipping: $8.00 via Flat rate
Tax: $10.96
Payment method: Credit Card (Stripe)
Total: $143.81
Billing address ************* Shipping address **************

Thanks for using www.frontporchcoffee.com!

Sent by Front Porch Coffee <https://frontporchcoffee.com>

**Comment by ChadOfDoom2** [comment]
For sure. Do you have an email address I can forward the receipt to? I'm
not sure how I could post it otherwise.

**Comment by cleidigh** [comment]
@ChadOfDoom2 
you can send it to:
test1@kokkini.net

**Comment by ChadOfDoom2** [comment]
Sent, Thanks so much!

**Comment by cleidigh** [comment]
@ChadOfDoom2 
Printing with the Microsoft PDF printer driver + PT produces the following  - looks okay to me
[CoffeePrint.pdf](https://github.com/cleidigh/printing-tools-ng/files/5106852/CoffeePrint.pdf)
can you try printing to PDF with and without the extension
We need to eliminate either the printer driver or the extension
Christopher

**Comment by cleidigh** [comment]
@ChadOfDoom2 
any update?

**Comment by ChadOfDoom2** [comment]
I tried today. I disabled all the add-ons and printed directly through TB
and it's still super long. So I'm guessing it's something to do with the
print format in TB?

**Comment by zalmanlew** [comment]
@ChadOfDoom2 we had a similar issue - if you're printing to a receipt printer you should be able to handle the whitespace through the printer settings on Windows Printer Preferences. It'll still display it in the preview but ours get cut after 1/3" or so of the bottom.

If it still contains text at the _end_ of the page - you need to remove the footers - which if still there than your best option would be to create a custom email template for the WooCommerce emails - this can be optimized for a receipt paper layout (whereas the current email is made for web viewing).
