### ISSUE TITLE
[Feature Request] Body and Header change of Font family, Size, Color

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#120]
@cleidigh

I want to change the font, size and color in both the body and the headers.
Fonts, sizes, color can only be specified for the body or header.
I would like to be able to specify and change both of those.

My desired image is as follows.
![Sample Style Tab 03](https://user-images.githubusercontent.com/80428201/168431352-426b12d1-a96a-4048-8ade-9a3559b398e7.png)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
I think if we only follow what we do now with the body this should be possible.
How did you do the example dialog? It looks very good!
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>I think if we only follow what we do now with the body this should be possible.

Thanks.
Does that mean that my hope is likely to be realized?

>How did you do the example dialog? 

I have captured, copied, pasted and otherwise processed images.

k@iki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
I think this should be doable in 2.1.2 .
I assume that just modifying <p> elements as we do now is ok?
I do want to make sure we are ready for 102 before I attack this.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>I think this should be doable in 2.1.2.

Thanks.

>I assume that just modifying elements as we do now is ok?

Yes, I would be happy if it looks like the image I created.
However, HTML messages may cause new problems.

>I do want to make sure we are ready for 102 before I attack this.

I am in no hurry.
I will leave the priorities to you.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Some things to consider for this which will charge some aspects of your mockup...
- The "use black as the base color for text" was deactivated some time ago before me
 also I have no idea what it was doing, needs to be removed from ui
- The citations only relevant for body of message 
- the font changes for html seem to work ok on quick try 
- have to look at css issues separating hdr and body rules

What do you think about adding color option for headers, maybe body?
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>    The "use black as the base color for text" was deactivated some time ago before me.
>    also I have no idea what it was doing, needs to be removed from ui.

I agree.

>    the font changes for html seem to work ok on quick try.

understood.

>    have to look at css issues separating hdr and body rules.

I guess its a laborious task but would be happy to sort it out.

>What do you think about adding color option for headers, maybe body?

If I were to add one, it would be the body text color option.
As per my original request, I would like to be able to customize fonts, size and color for both the body and headers.

![Sample Style Tab 04](https://user-images.githubusercontent.com/80428201/171624114-5b0ae00c-4b6b-4e0a-8d68-347854042885.png)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
no luck with css yet, I'm going to see if any devs of tb have ideas
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
Ok, after sleeping on it I figured out how to get the css different for the body  versus the headers.  I am not done, but I wanted you to see and test.
Right now you can change either the body or the headers, no ui changes yet and i have to add the restoration  methods to restore the original fonts,
Check it out to see if it works on all messages.  My testing was successful.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>Right now you can change either the body or the headers, no ui changes yet and i have to add the restoration methods to restore the original fonts, Check it out to see if it works on all messages.

I agree.

１．Test report
　PTNG 2.1.2-b2
　Thunderbird 91.10.0 64bit
　Windows 10 Pro 21H2 64bit

- Font size
Headers = HTML messages and plain text messages -> OK
Body text = HTML messages -> OK, plain text message -> NG

- Font type
Headers = HTML messages and plain text message -> NG
Body text = HTML messages and plain text message -> NG

２．Update my mockup image

![Sample Style Tab 06-0](https://user-images.githubusercontent.com/80428201/172046716-011a3b5c-1b91-41df-b9d3-8840c11279e7.png)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Alot of work...
Here is a shot of the ui changes, still doing backend stuff, but I have worked out the main issues.  By rearranging items the dialog is both smaller and better organized.
<img width="960" alt="2022-06-06-22-39-49 " src="https://user-images.githubusercontent.com/25272315/172284844-2996db4d-6353-4c63-97b4-cf88247018f8.png">

@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
ok b2 has everything working and the dialog is much better.
I think I will wrap this up so I can get LocalFolders out also.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

The dialogs are better.
Thank you.
I am not sure about LocalFolders, but I hope that your original request can be fulfilled.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
everything is done in b2, have you tested?
I think I can release.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
I  think the only other translation change is:
"Note: Enable Print backgrounds in the print dialog"
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh 

>What is the difference between OK and NG in your test results?

The difference between OK and NG in the test results is as follows
-OK means the change of font size, type is enabled.
-NG means the change of font size, type is not disabled.

I investigated why the font type change was not taking effect and found the cause.
It was because I had not turned on 'Allow messages to use other fonts' in the Thunderbird options Font Control.
After turning it on, it is now enabled.

![Font Control](https://user-images.githubusercontent.com/80428201/173059270-628625d4-5eec-4425-a65a-18d4f967340a.png)

>Yes I always do translations last.

I agree.

>I think the only other translation change is:
>"Note: Enable Print backgrounds in the print dialog"

I will try to translate according to the changes in the en-US version.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
ok good, that makes sense.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
b3 has the updated en strings.
We already had "Headers" (assuming the ja is correct)
The two new strings are:
"Message Body"
 "Note: Enable Print backgrounds in the Print dialog"
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh 

>b3 has the updated en strings.

I have added one translation and changed one.
The printingtoolsng.dtd file is attached.

[ja-printingtoolsng.dtd.zip](https://github.com/cleidigh/printing-tools-ng/files/8885607/ja-printingtoolsng.dtd.zip)

I have found a problem with the font size pull down values in the message body.
The maximum value is 1000, but I feel it should be standardized to 50.
Please see screenshots.

![Style - Font size pulldown-1](https://user-images.githubusercontent.com/80428201/173228146-e8f5d2dc-18d5-4fe4-b83e-8480bf909dd3.png)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Updated all translations, thanks. See b4
I left the body fonts because this was actually requested for some 
users.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

> Updated all translations, thanks. See b4

I have checked b4. Good.

> I left the body fonts because this was actually requested for some
> users.

I understand.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Fixed alignments, ja file
I think we can release.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
I am cleaning up. 
If you think it looks good I will put it in the Q.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

I confirmed b5.
This issue has been resolved and the hope has been realized.
I consider the release to be fine.

I will send you a separate email regarding the optional UI customization.

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

> Updated all translations, thanks. See b4

I have checked b4. Good.

> I left the body fonts because this was actually requested for some
> users.

I understand.

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

>I think this should be doable in 2.1.2.

Thanks.

>I assume that just modifying elements as we do now is ok?

Yes, I would be happy if it looks like the image I created.
However, HTML messages may cause new problems.

>I do want to make sure we are ready for 102 before I attack this.

I am in no hurry.
I will leave the priorities to you.

@kiki-ja
