### ISSUE TITLE
Blog and News (RSS & Atom Feed) print email not RSS (dup #119)

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#121]
@cleidigh 

PrintingTools NG 2.1.1
Thunderbird 91.9.0 64bit
Windows 10 Pro 21H2 64bit

This is a print issue of Blog and News

[Problem]
-Print... (NG), Ctrl+P (Windows OS) will not work.
-The PTNG icon button on the toolbar prints only the title.
Please see sample screenshots.

[Workaround]
-Use the print button on the standard Thunderbird toolbar.
Please see sample screenshots.

![比較レビュー02](https://user-images.githubusercontent.com/80428201/168568090-46d3e45e-985f-4ad7-abf0-68f62fb443c7.png)

Sample feed URL:
https://github.com/cleidigh/printing-tools-ng/commits/v2.0.7.atom

Sample feed page:
"Merge branch 'master' into v2.0.7"
https://github.com/cleidigh/printing-tools-ng/commit/b4ea742354c25a5f44e31e62c8ff6c28f5173202

[Suggestion]
The main issue is the separation or integration of shortcut keys, menus, and icon buttons.
I think should organize how to deal with feed page as it is not a message.
The same applies to preview printing of PDF attachments.(#119)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Discussed this today on the developer call, will post more tomorrow, cant type well today.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
I think I have determined the methods to detect emails from other types and fallback to tb print.
Have to integrate into a beta
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

I think fallback is a good way.
It would be nice if we could solve this problem in a simple way.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
The fix is straightforward and implemented in b1.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

Great!
Confirmed with PTNG 2.1.2-b1.
Also confirmed with #119 as well.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
good. I just found another 102 issue  with eml files
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

I was thinking of asking for a new 'Feature Request' for #102.
For now, I will close this #119.

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

I think fallback is a good way.
It would be nice if we could solve this problem in a simple way.

@kiki-ja
