### ISSUE TITLE
[Feature Request] Improve width of text input space and fonts selection area

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#124]
@cleidigh

The width of the optional input space is narrow and we are requesting that it be widened a bit.
At the same time, we would like the fonts selection area to be wider so that all can be displayed as well.

![Option- Misce mod](https://user-images.githubusercontent.com/80428201/171870477-88bf2237-e3d9-4881-bf13-d8dcfec0aeb2.png)

![Option - Style mod](https://user-images.githubusercontent.com/80428201/171870503-b8895905-17a9-403e-abcb-2912767f5a2f.png)

A modified version of the above, 'ptng-options.xhtml', has been created below. Please refer to it.
[ptng-options.xhtml.zip](https://github.com/cleidigh/printing-tools-ng/files/8832888/ptng-options.xhtml.zip)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
I agree that these fields should change.
Comments : 
I made the header title shorter to not run up to the right edge.
I changed the font and border sizes per your changes, however, the font dropdown is very large. For my font set it's much larger than necessary.
I know you have some Japanese fonts that I do not, do they need such a large width?

see b2 for changes 
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

I have previously reported this issue in #80.
I need wider widths for non-Japanese fonts.

Issue - 2.0.7 Beta Test Reports
https://github.com/cleidigh/printing-tools-ng/issues/80#issuecomment-904647577

I confirmed b2.
The width is now sufficient for my needs.
Thank you very much.

See screenshot of b2.

![Option - Style - Font pull-down](https://user-images.githubusercontent.com/80428201/171995538-7349ccc9-f7f6-4adb-ac3f-9ca371d98d77.png)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
great, i need to do the ui changes in a bit. I'm now also getting localfolders ready for 102 so I'm getting busy!
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

Additional request.
Can the width of the Options Dialog window be made a little smaller?

Please see mockup image.
![Option - Miscellaneous - Mockup 04](https://user-images.githubusercontent.com/80428201/172056859-735d9163-7388-4e5c-ac64-52fa6a3845ed.png)

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

The dialogs are better.(from 120)
Once the improved dialogs are implemented, I will close this issue.

<img width="455" alt="Option - Style 20200606" src="https://user-images.githubusercontent.com/80428201/172611624-20e59999-e1a8-4f76-a13a-337f26ee0a12.png">

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Last alignments done  in b6
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

I confirmed b6.
This issue has been resolved and the hope has been realized.
I consider the release to be fine.

I will send you a separate email regarding the option UI customization.

@kiki-ja
