### ISSUE TITLE
Version 2.1.2 not working

### ISSUE THREAD

**Issue by Thefaroah** [cleidigh/printing-tools-ng#127]
The PrintingTools NG icon is in both main toolbar and message toolbar.
Select Print or Print Preview. Nothing happens.
Disabled other add-ons one at a time to see if there was any conflict. Nothing found.
I'm using TB 91.10.0 (64-bit).

**Comment by cleidigh** [comment]
@Thefaroah 
Thanks for the quick report, this just landed.
Two questions, what OS and do you see anything in the console?
Oh, and how about seeing the options dialog?
Definitely don't want a broken release!
@cleidigh

**Comment by Thefaroah** [comment]
OS is Win 10 with latest updates.
Options dialog works fine from the dropdown menu.
Console:
![image](https://user-images.githubusercontent.com/46969365/174646791-74ea62ab-5284-481b-b15c-45a28777db16.png)

**Comment by cleidigh** [comment]
@Thefaroah 
ok that's a pref error, can you expand the twistie on the exception?
That will give me the call stack.
Also did you upgrade manualy, auto or a fresh install?
I have several new prefs and I am guessing that may be related.
@cleidigh

**Comment by Thefaroah** [comment]
Normally I manually check for updates for add-ons and for TB, sometimes manually, sometimes it lets me know an update is available for manual update.
Here's the additional info:
![image](https://user-images.githubusercontent.com/46969365/174650461-c45b506d-4c21-4756-9845-1f8d2c6b0ced.png)

**Comment by cleidigh** [comment]
@Thefaroah 
ok, it's an uninitialized pref. Try this:
Go to options /style
Enable headers font to anything and save options 
Then retry printing 
@cleidigh

**Comment by Thefaroah** [comment]
You solved it. Works like charm.
Thanks for quick response.

**Comment by cleidigh** [comment]
@Thefaroah 
Closed with v2.1.3
@cleidigh
