### ISSUE TITLE
Thunderbird 78

### ISSUE THREAD

**Issue by ahub108** [cleidigh/printing-tools-ng#13]
When will there be a version for the new Thunderbird ?
Thanks for the good coding !

ahub

**Comment by cleidigh** [comment]
@ahub108 
I cannot say for sure as I really need to work on several other extensions having just finished PrintingTools recently.
I will say that unless there is some major issue, I will be upgrading the extension.
as soon as I start I will update the homepage to let people know they can get beta
Christopher

**Comment by librelegal** [comment]
Would be great to publish a beta even (with ImportExportTools NG, another plugin you support the beta helped a lot). Thank you

**Comment by cleidigh** [comment]
@librelegal 
thanks!
unfortunately because of the very different nature of 78 getting a functional beta  is pretty much most of the work.
the good units is that I should be much faster than my first try.
I am also looking at getting some help
Christopher

**Comment by cleidigh** [comment]
@librelegal 
@ahub108 
first beta is posted!
track below:
https://github.com/cleidigh/printing-tools-ng/issues/18
