### ISSUE TITLE
Please add support for version 103

### ISSUE THREAD

**Issue by MHolkamp** [cleidigh/printing-tools-ng#130]
I know it is still beta but iḿ using version 103 and this extension.
So please add support version 103 and i will test the plugin here.

**Comment by cleidigh** [comment]
@MHolkamp 
I will start a beta and enable for 103 shortly.
@cleidigh

**Comment by cleidigh** [comment]
@MHolkamp 
v2.1.4 is in the review Q with support for TB 103.0.
Let me know if you see any issues.
@cleidigh

**Comment by MHolkamp** [comment]
Hi,

Stupid question : Where do i find the review Q.
Btw: Keep up the good work!

**Comment by cleidigh** [comment]
@MHolkamp 
No not a stupid question, stupid assumption on my part ;-{
The review queue is where addons get reviewed before release.
So we have to wait for that. While it's not official, you can get 2.1.4 here:
https://github.com/cleidigh/printing-tools-ng/blob/v2.1.4/xpi/printing-tools-ng-2.1.4-tb.xpi
@cleidigh

**Comment by MHolkamp** [comment]
@cleidigh Great!
It was not a stupid assumption ;-)
Learning everyday ;-)
I have downloaded the xpi.
When i find issues i will open new ones here.
Thanks!

**Comment by cleidigh** [comment]
Closed with v2.1.4
