### ISSUE TITLE
PTNG not working if mail not displayed

### ISSUE THREAD

**Issue by querixg** [cleidigh/printing-tools-ng#132]
Thunderbird 91.11.0
PTNG 2.1.4
Linux Mint 20.1

@cleidigh

I just noticed that printing a mail using PTNG 2.1.3 or 2.1.4  (menu bar: File > Print... (NG)), mail toolbar: Print NG, context menu: Print... (NG), or Ctrl+P) yields normal print instead (like menu bar: File > Print), if the mail has not been opened and the message pane is not displayed. This had been fixed with PTNG 2.1.1-b1 I thought.

**Comment by cleidigh** [comment]
Hey @querixg 
You caught correctly 👍 
I reproduced on Windows, must have reverted something along the way..
I will investigate, fyi i have multiple big bugs for IETNG I am in the middle of.
@cleidigh

**Comment by cleidigh** [comment]
Closed with v2.1.5
