### ISSUE TITLE
How to print PDF attachment only?

### ISSUE THREAD

**Issue by SamirSplit** [cleidigh/printing-tools-ng#135]
Olá, tudo bem? estou usando o PTNG, junto com Filtaquila para imprimir automaticamente os e-mail, porém preciso que imprima somente os anexos (eles sempre são em PDF), é possível imprimir somente o anexo?

**Comment by SamirSplit** [comment]
Hello how are you?  I'm using PTNG, together with Filtaquila to automatically print the emails, but I need you to print only the attachments (they are always in PDF), is it possible to print only the attachment?

**Comment by cleidigh** [comment]
@SamirSplit 
Tudo azul, brigado!
So what part of Brazil are you from ? 👍 
Right now there unfortunately is no way to print attachments separately.  Because the attachment content is not originating in TB it makes this difficult. There are several requests for handling attachments and pdf may have some possibilities. I will see if i can investigate.
Saudaje
@cleidigh

**Comment by SamirSplit** [comment]
I’m from Rio de Janeiro

Thanks 

Samir Antonio

**Comment by cleidigh** [comment]
@SamirSplit 
One of my favorite cities !
Christopher

**Comment by SamirSplit** [comment]
despite having its problems like every big city, it's wonderful right here… where are you from?

Samir Antonio

**Comment by cleidigh** [comment]
Originally from NY now in Providence south of Boston. Have also lived in Buenos Aires and traveled all over SA, but not enough in Brazil.

FYI I do think there is good possibility that we have the mechanism to print pdf attachments. I am working on some major things for ImportExportTools so I can't say when I can get to this.

Can I ask the application? I am interested what you are doing with pTNG and FiltaQuila.
@cleidigh

**Comment by cleidigh** [comment]
@SamirSplit 
If i get some time I will experiment.
@cleidigh

**Comment by SamirSplit** [comment]
thank you so much….  I tested this code and it worked perfectly… I don't know if it will help in the future to create an option like this for Mozilla thunderbird… Thank you very much again

Samir Antonio

> Em 31 de ago. de 2022, à(s) 18:53, Christopher Leidigh ***@***.***> escreveu:
> 
> If i get some time I will experiment.
