### ISSUE TITLE
Print multiple selection fails

### ISSUE THREAD

**Issue by fabiozam71** [cleidigh/printing-tools-ng#136]
hi, in last update, when I print multiple selected emails, it doesn't take the custom style, but it prints the whole email entirely. are there any solutions?

**Comment by kiki-ja** [comment]
@fabiozam71
@cleidigh


>when I print multiple selected emails, it doesn't take the custom style, but it prints the whole email entirely.

I reproduce it too.
PrintingTools NG 2.1.4 
Thunderbird 102.2.2 64bit
Windows 10 Pro 21H2 64bit

>in last update,

What are the updates?
Was a custom style of print multiple messages possible in previous versions?
What is that version?

>are there any solutions?

So far, no.
If there is a solution, it is to print the messages one at a time or request improvements from the author @cleidigh.

@kiki-ja

**Comment by cleidigh** [comment]
@fabiozam71 
@kiki-ja 
I actually introduced this problem when I fixed another.
I should have a beta fix shortly
@cleidigh

**Comment by fabiozam71** [comment]
Ok thanks 

Il giorno 10 set 2022, 21:27, alle ore 21:27, Christopher Leidigh ***@***.***> ha scritto:
***@***.*** 
***@***.*** 
>I actually introduced this problem when I fixed another.
>I should have a beta fix shortly
***@***.*** 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/cleidigh/printing-tools-ng/issues/136#issuecomment-1242792646
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by fabiozam71** [comment]
> @fabiozam71 @kiki-ja In realtà ho introdotto questo problema quando ne ho risolto un altro. Dovrei avere una correzione beta a breve @cleidigh

hello, do you have any news on solving the problem? thank you

**Comment by cleidigh** [comment]
@fabiozam71 
I have gotten tangled up in ten different things!
Yes I think I refixed this.
Let me see if I can make a clean beta for this.
@cleidigh

**Comment by fabiozam71** [comment]
Perfect thanks :-)

**Comment by fabiozam71** [comment]
> @fabiozam71 I have gotten tangled up in ten different things! Yes I think I refixed this. Let me see if I can make a clean beta for this. @cleidigh

Perfect thanks :-)

**Comment by cleidigh** [comment]
@fabiozam71 
@kiki-ja 
@querixg

I  am finally back to where I can get beta out fixing multi selection print. Sorry it's been awhile...

I need a sanity check : 
All of the sudden nothing was working at all on 102.3.
Is anyone seeing problems with ptng output on 102.x?
I feel like maybe I missed a regression?

One thing I am chasing that is related is pdf issues.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

PrintingTools NG **2.1.5-b1**
Thunderbird 102.3.0 64bit
Windows 10 Pro 21H2 64bit

I report the results of my test.
procedure:
・Select two messages
・Ctrl+P or click on PTNG icon
・Printing system dialog opens (skip print preview)
・Print with the style set in PTNG

See screenshots.
![multi select message sample](https://user-images.githubusercontent.com/80428201/192714451-89c96477-e8c2-4079-b214-142973d2966c.png)

@kiki-ja

**Comment by fabiozam71** [comment]
> @fabiozam71 @kiki-ja @querixg
> 
> I am finally back to where I can get beta out fixing multi selection print. Sorry it's been awhile...
> 
> I need a sanity check : All of the sudden nothing was working at all on 102.3. Is anyone seeing problems with ptng output on 102.x? I feel like maybe I missed a regression?
> 
> One thing I am chasing that is related is pdf issues.
> 
> Update beta tested on Windows and Linux https://github.com/cleidigh/printing-tools-ng/blob/v2.1.5/xpi/printing-tools-ng-2.1.5-b1-tb.xpi
> 
> @cleidigh

hello, installed the beta, now it works.
but I haven't done the client update to 91.13.0 (32 bit) I'm at 91.130

**Comment by cleidigh** [comment]
@fabiozam71 
@kiki-ja 
Thanks, that's good.
@cleidigh

**Comment by cleidigh** [comment]
Closed with v2.1.5
