### ISSUE TITLE
Does Printing Tools work on latest T'bird version?

### ISSUE THREAD

**Issue by cloverdavid** [cleidigh/printing-tools-ng#137]
Keep getting requests to update T'Bird from 91.8.1 to 91.13.0. Will not upgrade unless I know that Printing Tools (my favorite) works on new version.

**Comment by cleidigh** [comment]
@cloverdavid 
Worry not, PTNG is compatible up to 103.  There are already over 4k users under 91.13.
I have the stats public, you can check them anytime.
https://addons.thunderbird.net/EN-us/thunderbird/addon/printingtools-ng/statistics/usage/applications/?last=90

Cheers, thanks!
@cleidigh
