### ISSUE TITLE
Add Dark mode theme support 

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#141]
Both TB 91 & 102 Dark modes are not currently supported  and require tweaks.

@kiki-ja 
@RRoenn I think you use dark mode, I will post my beta tomorrow for any comments.

@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

I have not used the dark mode, but will report the results of my testing.

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

PTNG-2.1.5 pdft6
Thunderbird 102.6.0 RC1 64bit
Windows 10 Pro 22H2 64bit

Thunderbird Theme:
Use the standard bundled Dark(A theme with a dark color scheme).

OS Theme:
No dark theme is used.

Please see screenshots.
![Datk - Manage Your Themes](https://user-images.githubusercontent.com/80428201/206857167-3d3b8ee7-7513-499d-be9e-804f46d9d880.png)

![TAB1 - Dark](https://user-images.githubusercontent.com/80428201/206857175-86985498-e22f-4afb-ac0e-930a42d46e1f.png)

![TAB2 - Dark](https://user-images.githubusercontent.com/80428201/206857181-c5c4207f-80e1-4efa-b3e3-7ae497918a79.png)

![TAB3 - Dark](https://user-images.githubusercontent.com/80428201/206857219-7bea622b-cb14-4505-9298-d008a37f1621.png)

![TAB4 - Dark](https://user-images.githubusercontent.com/80428201/206857221-73355454-e525-400a-8f9d-3154eea67447.png)

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

PTNG-2.2.0 b5
Thunderbird 102.6.1 64bit
Windows 10 Pro 22H2 64bit

#152 mentions.

Thunderbird Theme:
Use the standard bundled Dark(A theme with a dark color scheme).

OS Theme:
No dark theme is used.

Please see screenshots.
![Dark-TAB1](https://user-images.githubusercontent.com/80428201/212298752-e8eba335-04e8-4e18-9c7f-f6aa412f5b4c.png)

![Dark-TAB2](https://user-images.githubusercontent.com/80428201/212298866-ea4e4abd-6684-4d61-bd96-5be775bdc787.png)

![Dark-TAB3](https://user-images.githubusercontent.com/80428201/212298893-c5bc0fc8-ca04-4984-835c-ad38f99b9df2.png)

![Dark-TAB4](https://user-images.githubusercontent.com/80428201/212298928-427e290e-23cf-4249-8f20-7486b9c43f4f.png)

![Dark-TAB5](https://user-images.githubusercontent.com/80428201/212298955-38cadf54-3674-451c-938c-346ef05a0260.png)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
I think everything looks good and consistent.
I will close with release.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh
To All

Visibility is excellent and great under my environmental conditions.

It would be nice to have test reports from dark theme users on other operating systems (macOS, Linux).

@kiki-ja
