### ISSUE TITLE
HTML entities not shown correctly and double notification

### ISSUE THREAD

**Issue by RealRaven2000** [cleidigh/printing-tools-ng#142]
My Printing Tools NG probably just updated, and there is adouble notification. I had my French locale enabled, the notification is stacked 2 times on top and the contents look like this:

![image](https://user-images.githubusercontent.com/6314674/195849346-18a405f5-53f1-4131-97fd-36b8057c0ad3.png)

One way to fix the contents is by copying the text into element.innerHTML:

![image](https://user-images.githubusercontent.com/6314674/195849463-ff54b956-a2c5-4fea-8b5f-d1f5f4d1d8ec.png)

**Comment by cleidigh** [comment]
@RealRaven2000 
Weird, I wonder if this is an edge condition of the upgrade.
I don't think it has to do with HTML.
@cleidigh
