### ISSUE TITLE
Not working on mac?

### ISSUE THREAD

**Issue by ArieVerhagen** [cleidigh/printing-tools-ng#145]
I was happy to see the NG version of this great tool, but somehow it does not seem to be working with Thunderbird (102) on my macbook. After installation, I can access the options, and the NG button replaced the default print button, but clicking it (or pressing Cmd-P), or requesting preview, just gives me exactly the same as the built-in print command (mozilla preview screen), and the options I ticked are not implemented. Restarting Tb did not help. Disabling the mozilla preview did not either. Any suggestions?

**Comment by cleidigh** [comment]
@ArieVerhagen 
I have a macbook but it's 2013 with an older osx.
Can you capture the console output? Hopefully that will give us something to go on.
@cleidigh

**Comment by ArieVerhagen** [comment]
My macbook is 2021, just updated to OSX Ventura - but I just found out that the problem can't be in the OS. I run Thunderbird with two different profiles. The problem occurs when running with the default profile - that's where I first installed the add-on, and tested it. I just installed it in the other profile too, and there it works as it should! I have nu clue whatsoever - do you?

**Comment by cleidigh** [comment]
@ArieVerhagen 
I guess reinstall and check console when printing.
Also disable other extensions.
@cleidigh

**Comment by eRudy** [comment]
Hi,

same issue here on MacOS, the preview is not modified at all as expected.

I found out that it works after disabling the extension "Thunderbird conversation" (http://github.com/thunderbird-conversations/thunderbird-conversations/wiki).

**Comment by cleidigh** [comment]
@eRudy 
Could you possibly capture the console output when doing a print.
It might at least show if ptng is being invoked.
Does Conversations do anything with printing?
@cleidigh

**Comment by eRudy** [comment]
> @eRudy Could you possibly capture the console output when doing a print. It might at least show if ptng is being invoked. Does Conversations do anything with printing? @cleidigh

This is what I get in the console with "Thunderbird conversation" deactivated:
`18:24:32,932 cmd_printng start: silent: false [printingtoolsng-pengine.js:464:11](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
18:24:33,447 PTNG: Done [printingtoolsng-pengine.js:505:11](chrome://printingtoolsng/content/printingtoolsng-pengine.js)`

and with the plugin activated:
`18:25:56,995 cmd_printng start: silent: false`

Don't know if we can see more things, but that's all I have in the console..

**Comment by cleidigh** [comment]
@eRudy 
I have reproduced this on Windows so I can now debug and hopefully find a solution. Stay tuned...
@cleidigh

**Comment by cleidigh** [comment]
@eRudy 
Found the conflict, should have a beta shortly.
@cleidigh

**Comment by ArieVerhagen** [comment]
Looking forward... In the meantime, I also checked for possible conflict with other plugins. I didn't find any (I don't have the conversations plugin installed), but in the process stumbled upon something else. As I said before, I run Thunderbird with two different profiles, and one of them does not exhibit the problem. Now, the main account of one of the profiles is an exchange account, which I access through the (paid for) OWL-for-Exchange add-on. That one I couldn't disable without losing access to my inbox. So to test Thunderbird's settings for that profile, I temporarily added a second acoount (imap). Lo and behold: In that account's inbox, the printingtools NG add-on works fine!! Actually, the same turns out to be true for messages in local folders... I guess that narrows down the possibilities to some extent?

**Comment by cleidigh** [comment]
@ArieVerhagen 
Thanks for the sleuthing!
The issue with Conversations is slightly indirect and could occur with other addons if they alter the message view or designate a non standard message type. I am wondering if this may be your case with OWL.
I should be able to prove the theory with some debug.
In the meantime if you want to try to capture the current output, clear the log, attempt print and capture the log and post.
@cleidigh

**Comment by kiki-ja** [comment]
@ArieVerhagen

1. The profile that is causing the problem may be corrupted.
    We recommend testing with a new profile.

2. If you have add-ons installed, please list them.
    Otherwise, it is unclear if there are conflicts with other add-ons.

Please refer to the following comments
https://github.com/cleidigh/printing-tools-ng/issues/149#issuecomment-1321104420
https://github.com/cleidigh/printing-tools-ng/issues/104#issue-1175488286

------------
About plugin:
Thunderbird does not have plug-ins.
Add-ons are extensions, themes, language packs, etc.

@kiki-ja

**Comment by cleidigh** [comment]
@eRudy 
@ArieVerhagen 
I have a really rough test version that solves some of the main issues with Conversations. It's messy, but it should prove out a lot.
One of the behaviors is that when you are viewing a thread only the first message is printed. If you want the thread, you use the conversations print link.
The multiple messages printing has to be fixed.

@ArieVerhagen 
If you can capture all the console output doing a print from your OWL account, I am hoping to find why it's not printing ptng output.
I think it may be manipulating the message display which ptng expects the default format.

https://github.com/cleidigh/printing-tools-ng/blob/pdfTest/xpi/printing-tools-ng-2.1.5-pdft5-tb.xpi

@cleidigh

**Comment by cleidigh** [comment]
@ArieVerhagen 
ok, I will walk you through a couple things.
First I would at least expect some debug from the release version so lets start there.

First test  
clear the console with the trash icon top left in window
next go to your local folders and print one of your emails there , this should succeed given your statements above
next return to the console and right click , choose select all
then ctrl c to copy
next you should save that in a text file and post here 
if you cannot do that you can also just paste here 

Second test
Follow the same sequence above, but choose one of your owl account messages

Loading test xpi
I have had users report the corrupted file download before. It is some glitch with the download. They have resolved the problem by downloading one or more times or using a different browser. 

If you are able to load the test xpi repeat test two with the owl account and also post results.

The fact that you are able to print from your LF tells me the owl account alters either the headers or the message url, both would cause failure.
I have no way to test owl so we will need to get the test xpi which may give us some clue.
@cleidigh

**Comment by cleidigh** [comment]
@ArieVerhagen 
Any update?
@cleidigh
