### ISSUE TITLE
FEATURE REQUEST: Separate 'Print Preview' button for toolbar

### ISSUE THREAD

**Issue by IanEMartin** [cleidigh/printing-tools-ng#146]
As a user it would be really nice not to have to click the little down arrow on the Print button on the toolbar to select Print Preview.  I would like to have a separate button that is only for 'Print Preview'.

**Comment by cleidigh** [comment]
@IanEMartin 
With a single message selected, clicking the main part of the button will go to the preview. If you are seeing something different then we need to explore.
@cleidigh

**Comment by IanEMartin** [comment]
I am seeing something different.  It pulls up the print modal.

**Comment by cleidigh** [comment]
@IanEMartin 
When you say "print modal" are you referring to the system print dialog?
There is a system preference that forces the system dialog. Check 
print.prefer_system_dialog
it should be false
if that's not the issue check the console output after attempting a print.
@cleidigh
