### ISSUE TITLE
Install current plugin (2.1.5) on old thunderbird (91.xx)

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#149]
Hello,
today I installed the current PTNG v2.1.5 on a PC of a client. After that, no printig was possible.
I found that it was an old thunderbird v.91.xx ...

Is there a way to prevent this? (e.g. min. ... max. version)

Thank you and best regards

**Comment by cleidigh** [comment]
@RRoenn 
How are things, been a while...
PTNG 2.1.5 is compatible and tested for 91.x to 103.x
It sounds like an install or conflict issue.
Can you try capturing the console?
BTW I am working on the features to be able to set page ranges, margins, headers and footers etc.
I will include you when I am close to something testable.
@cleidigh

**Comment by kiki-ja** [comment]
@RRoenn

The following are possible reasons why you cannot print after installing PTNG 2.1.5.
1. Conflict with other add-ons. (I experienced this too.)
2. Thunderbird's profile is corrupted.
3. Thunderbird is not installed properly. 
4. Other reasons, such as incompatibility with the OS type and version, or a problem with the printer driver.

**Troubleshooting steps:**
1. disable all other add-ons and check if you can print normally with PTNG.
　　If normal: 
　　Enable other add-ons one by one and find out which add-on is conflicting with which.
　　If you cannot print with PTNG:
　　Check with 2 and 3.

2. Create a new profile in Thunderbird and check it.
　　Reference:
　　#104

3. Reinstall Thunderbird.

4. Check if the OS is supported.
　　Reference: 
　　Thunderbird — 91.13.1 System Requirements — Thunderbird
　　https://www.thunderbird.net/en-US/thunderbird/91.13.1/system-requirements/
　　Thunderbird — 102.5.0 System Requirements — Thunderbird
　　https://www.thunderbird.net/thunderbird/102.5.0/system-requirements/

Add-ons in conflict that have already been reported include.
"Thunderbird conversation"
Reference:
https://github.com/cleidigh/printing-tools-ng/issues/145#issuecomment-1312457859

**If you find an add-on that is causing a conflict, send a report to the author.**

--------------------------
Digression:
Plugin = X
Add-on = ○

Thunderbird add-ons - frequently asked questions | Thunderbird Help
https://support.mozilla.org/kb/thunderbird-add-ons-frequently-asked-questions#w_what-is-an-add-on

@kiki-ja

**Comment by RRoenn** [comment]
@cleidigh
I am fine, I hope you are also.
Lots of work ... but I am happy and would like to support you with the best, like testing and so one.

I updated the system to the latest TB version, so I can no longer check anything in the console.

@RRoenn
