### ISSUE TITLE
New Page options: Feature testing 

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#152]
Latest test version:  https://github.com/cleidigh/printing-tools-ng/blob/pdfTest/xpi/printing-tools-ng-2.1.5-pdft6-tb.xpi

Basic first test version. Ignore ui stuff, testing operation etc.

@cleidigh 
@kiki-ja 

@KC-T 
@tidebre67 
@reinerblock
@querixg
@RRoenn
@madvinegar
@ditchfinder
@3LaHoonK
@realraven
@librelegal
@Francewhoa
@JF1313
@ffsel

All

As active members of our PTNG community I am seeking input
for a significant new Page Options feature. If not interested 
please ignore / unsubscribe.  Normally I would involve people 
at the beta stage for feedback and testing. For this I need
early input before too much UI work and to make sure we have
everything we need.  My first test release is rough both
in the UI and error handling department. It is, however,
highly functional.

Overview :

Under PTNG options you can configure various settings for both 
preview and silent printing. Significantly we can set:
Copies, Page ranges, margins and headers and footers.
These are always sticky even if changed in the preview dialog.

The first big question is are we missing any config item.
Several current items are not sticky in the dialog so
they have unique value(Copies, page ranges).
Headers and footers are not configurable in the dialog.
These are a big add.
Margins are already both configurable in the dialog and
are sticky per printer. So one could argue these are fully
redundant.  Similarly I do not want to duplicate everything 
in the dialog so additions should have a good reason and
use case.

As for behaviors, I am looking to make sure how we are
doing things is sensible etc.

Thanks in advance...

**Comment by RRoenn** [comment]
Hello @cleidigh 
nice work, thank you!!!

I did some quick tests.
TB 91.13.1 (64bit)
ptng v2.1.5-pdf6, Add-On says in details v2.1.1: v100+ Update Mai 2022

**first of all, it works**

Strange behavior after first tests. TB need to be restarted as usual.

I set page ranges to: 1,2 was changed to 1, 2 ... no problem
I set page ranges to: 1 - 2 was changed to 1-2 ... no problem
I set page ranges to: 1 test- 3 (e.g. by mistake) was changed to 1-3 ... no problem
I set page ranges to: 1 -test 3 (e.g. by mistake) **was changed to 1-0 ... ?**

If I set to 1,3 or 1, 3 the print preview window page range was set to **1,1,3,3** print was okay, 1 and 3 page
If I set to 1-0 the print preview window page range was set to **1,0** <- Error
If I set to 1,5 the print preview window page range was set to **1,1,5,5** <- Error, my mail had just 4 pages ...
If I set to 1-3 the print preview window page range was set to **1,3** <- not the same as 1-3

But I will love it! Thank you

As you mentioned, the ui still needs some attention.
It would be nice to explain the abbreviations (&T, &PT etc.)

General question, does page scaling have an impact on the margins in mm?


If there are specific tests you want me to do, please let me know.

First of all, many greetings

**Comment by cleidigh** [comment]
@RRoenn 
Greetings back to you!
Your quick testing and enthusiasm is why I do all this, thanks!
I am going to add explanation and questions in the top post, I couldn't manage that yesterday, but I will comment here first.
Right now I have a hot, spaghetti mess due to all the experimentation.
I decided I needed feedback before really flushing things out.

The page ranges need improved validation as you already noted. I'll add comments above.
I want people's opinions on both the set of items configurable in PTNG as well as behavior.
I will add a table in the help for the header tokens, definitely needed.
I do not know about your question about scaling. I don't use that so maybe we need to experiment?
So think about if we are missing something that really has a use case.
@cleidigh

**Comment by Francewhoa** [comment]
Happy holiday season to both you @cleidigh and all contributors

To make it easier and faster to find and open all the **printing-tools-ng**'s configuration, including its new UI. I suggest adding an **Add-On Option** button. I created a new ticket with this suggestion at #153.

**Comment by JF1313** [comment]
Thanks for the quick turnaround!

When saving to PDF is it possible to add a default file location?

When I access the plug-in through the Filtaquilla with the default printer sent to PDF, the email is not printed.

**Comment by tidebre67** [comment]
@cleidigh , 
Christopher, for my purposes it works really fine. 
There is only one thing i found, the print preview opens rather slow in comparision to previous version.

**Comment by cleidigh** [comment]
@Francewhoa 
Great to hear you back, hope all is well for the holidays!
I am going to reopen and comment on 
- #153 
as the failed installation of the wrench icon is an issue.
@cleidigh

**Comment by cleidigh** [comment]
@RRoenn 
I am changing the page ranges input to a radio with All and Custom so I can do better validation in the input. Mixing the text and numbers is problematic.
One thing I confirmed yesterday is that even if you have a range greater than the document it will print in silent mode.
@cleidigh

**Comment by cleidigh** [comment]
@JF1313 
I don't have anything yet for the silent pdf/naming issue. I may do that in a formal beta 
@cleidigh

**Comment by cleidigh** [comment]
@RRoenn 
@kiki-ja
All
Was hoping for more feature feedback, but will move forward regardless.
I have done a lot with validation and some error flags.
@RRoenn addressing your error observations : 

set page ranges to: 1,2 was changed to 1, 2 ... no problem
	This is how TB styles the ranges 

I set page ranges to: 1 - 2 was changed to 1-2 ... no problem
	This is how TB styles the ranges 

I set page ranges to: 1 test- 3 (e.g. by mistake) was changed to 1-3 ... no problem
	Added key filtering that eliminates this scenario 

I set page ranges to: 1 -test 3 (e.g. by mistake) was changed to 1-0 ... ?
	Added key filtering that eliminates this scenario 

If I set to 1,3 or 1, 3 the print preview window page range was set to 1,1,3,3 print was okay, 1 and 3 page
	Fixed PP string formatting 

If I set to 1-0 the print preview window page range was set to 1,0 <- Error
	New validation flags this, disables OK

If I set to 1,5 the print preview window page range was set to 1,1,5,5 <- Error, my mail had just 4 pages ...
	Expected behavior, PTNG cannot know doc size at configuration 

If I set to 1-3 the print preview window page range was set to 1,3 <- not the same as 1-3
	Bug fixed

I restrict keys on number inputs 
I have dropdown errors 
Margins are checked for non empty, but no errors yet

I think if no one comments I have to hunker down and rewrite lots of code.
And the UI...
@cleidigh 

https://github.com/cleidigh/printing-tools-ng/blob/pdfTest/xpi/printing-tools-ng-2.1.5-pdft7-tb.xpi

**Comment by cleidigh** [comment]
@tidebre67 
Cheers, I was down and out yesterday, accomplished nothing...
I want to bring your issue here so we can all track.

The two things you mentioned were the translation for cancel and an issue with the correct units for margins. 

I will correct cancel. @RRoenn mentioned the translation for Body, tab 3. This is short for email body, but I think the translation is for the human body. I would hope we could use one word.

On the units...
"on my Notebook it shows mm in destination PDF24 and when i switch to destination printer
inches are shown. On my normal PC in both destination inches are displayed.
Little bit strange to me."

ok this is an important thing to resolve. It's also one that I can't debug here as I cannot reproduce the locale environment.

Couple of questions.
Independent of ptng, do you always see mm units on every pc/notebook and for every printer?

I get the units from the printsettings for the active printer so this is surprising. If i understand you, on your pc you never see mm?

Can you check your advanced preferences under the config editor. Search on print then I want to check the various printers.

For priknter there will be a set of print.printer_name. Prefs. 
For each printer look for the print_paper_size_unit
it should be 0 or 1 
This is what sets the units.
Also if you look in the log when you open the ui and look for output from line 68 of printerSettings.js

@RRoenn have you seen any units issues?
@cleidigh

**Comment by tidebre67** [comment]
@cleidigh , Christopher, i solved it due to your information. 
I changed the print.printer_........).print_paper_size_unit from 0 to 1 in the config editor  and all is fine now.
No idea why what happened before.

**Comment by cleidigh** [comment]
@tidebre67 
That is interesting. Did you have one printer wrong? Have you seen inches before? I never manipulate this setting, it should be what the original driver sets it to.
@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
on the notebook only 1 (local printer), on the normal pc  only pdf24 and the local printer,
Regret, no idea when i saw inches first time, presume last weekend.
