### ISSUE TITLE
Would you add a feature to set the margins?

### ISSUE THREAD

**Issue by Poikilos** [cleidigh/printing-tools-ng#156]
There is no way to set the margins and the header and footer gets cut off no matter how I set it. This is a widespread issue with Thunderbird itself. The only place I could find a list of settings is on a [2011 mozillazine post](http://forums.mozillazine.org/viewtopic.php?f=39&t=2286083): 
```
user_pref("print.print_edge_left", 50);
user_pref("print.print_edge_right", 50);
user_pref("print.print_unwriteable_margin_bottom", 25);
user_pref("print.print_unwriteable_margin_left", 0);
user_pref("print.print_unwriteable_margin_right", 0);
user_pref("print.print_unwriteable_margin_top", 20);
user_pref("print.printer_CUPS/HP1006.print_edge_bottom", 0);
user_pref("print.printer_CUPS/HP1006.print_edge_left", 50);
user_pref("print.printer_CUPS/HP1006.print_edge_right", 50);
user_pref("print.printer_CUPS/HP1006.print_edge_top", 0);
user_pref("print.printer_CUPS/HP1006.print_margin_bottom", ".2");
user_pref("print.printer_CUPS/HP1006.print_margin_left", "0");
user_pref("print.printer_CUPS/HP1006.print_margin_right", "0");
user_pref("print.printer_CUPS/HP1006.print_margin_top", "0.2");
user_pref("print.printer_Print_to_File.print_edge_bottom", 0);
user_pref("print.printer_Print_to_File.print_edge_left", 50);
user_pref("print.printer_Print_to_File.print_edge_right", 50);
user_pref("print.printer_Print_to_File.print_edge_top", 0);
user_pref("print.printer_Print_to_File.print_margin_bottom", "0.2");
user_pref("print.printer_Print_to_File.print_margin_left", "0");
user_pref("print.printer_Print_to_File.print_margin_right", "0");
user_pref("print.printer_Print_to_File.print_margin_top", "0.2");
user_pref("print.printer_Print_to_File.print_unwriteable_margin_bottom", 20);
user_pref("print.printer_Print_to_File.print_unwriteable_margin_left", 20);
user_pref("print.printer_Print_to_File.print_unwriteable_margin_right", 20);
user_pref("print.printer_Print_to_File.print_unwriteable_margin_top", 20);
user_pref("printer_HP1006.print_edge_bottom", 0);
user_pref("printer_HP1006.print_edge_left", 0);
user_pref("printer_HP1006.print_edge_right", 0);
user_pref("printer_HP1006.print_edge_top", 0);
user_pref("printer_HP1006.print_margin_bottom", "0.200000004842877");
user_pref("printer_HP1006.print_margin_left", "0");
user_pref("printer_HP1006.print_margin_right", "0");
user_pref("printer_HP1006.print_margin_top", "0.200000004842877");
user_pref("printer_HP1006.print_unwriteable_margin_bottom", 20);
user_pref("printer_HP1006.print_unwriteable_margin_left", 20);
user_pref("printer_HP1006.print_unwriteable_margin_right", 20);
user_pref("printer_HP1006.print_unwriteable_margin_top", 20);
``` 
- I'm not sure if the per-printer settings are necessary to deal with, but maybe. In that case, the settings would need to be iterated to discover the name patterns above.

**Comment by cleidigh** [comment]
@Poikilos 
Right now I am in the final stages of beta for the next version which has two significant new features, page options and pdf naming /auto save.
The first allows you to set copies, page ranges, margins and headers and footers.
These may be useful to you, however, I think you may have a different need.
Can you further describe your issue?
First id os, tb and ptng versions.
Next what margins are you not able to change? I have no awareness about headers and footers not being printed, can you be more specific?
What printer and page size are you using.
Have you tried the Save as pdf driver?

Here is the beta
 https://github.com/cleidigh/printing-tools-ng/blob/v2.2.0/xpi/printing-tools-ng-2.2.0-b6-tb.xpi
@cleidigh

**Comment by Poikilos** [comment]
> @Poikilos Right now I am in the final stages of beta for the next version which has two significant new features, page options and pdf naming /auto save. The first allows you to set copies, page ranges, margins and headers and footers. These may be useful to you, however, I think you may have a different need. Can you further describe your issue? First id os, tb and ptng versions.

- OS: Linux Mint 21 (based on Ubuntu Jammy)
- Thunderbird 102.4.2
- Printing Tools NG 2.1.5

It happens when I print using Thunderbird's File, Print option in the menu or using the Printing Tools NG button.

> Next what margins are you not able to change? I have no awareness about headers and footers not being printed, can you be more specific?

I cannot change any margins, but the header placement is the biggest issue. 

> What printer and page size are you using. Have you tried the Save as pdf driver?

The page size is U.S. Letter (8.5x11).

They are hard-coded to print outside of the range of *any* printer for some reason, and Thunderbird has not only neglected to add settings but made the defaults poor. If I push print on an e-mail, you can see the issue here:

![image](https://user-images.githubusercontent.com/7557867/212774905-1b475147-a784-4cd0-ab9b-919eab898232.png)

- Even if I click "Print using system dialog" and check "Ignore scaling and Shrink to Fit the Page Width" that doesn't help--height is still too tall regardless of that.
- If I click Print, then choose "Save to PDF" as the printer, there is no change. The headers and footers are there like they are in the preview, but they are outside the print range of any (consumer) printer. However, it introduces a workaround because for some reason if I print the PDF using Xreader the "...Shrink to Fit the Page Width" checkbox is no longer available under Options and in its place is a "Page Scaling" drop-down where I can choose "Shrink to Printable Area". Of course, this is so convoluted that I will probably forget the workaround. I only got there from your suggestion to print a PDF and the workaround can't even be done inside Thunderbird.

> 
> Here is the beta https://github.com/cleidigh/printing-tools-ng/blob/v2.2.0/xpi/printing-tools-ng-2.2.0-b6-tb.xpi @cleidigh

If I install the beta, it says installed then Thunderbird and my taskbar and menu all become unresponsive. I had a terminal already open so I had to Alt+Tab to it and run `killall thunderbird`. If I re-open Thunderbird, I can't click anything. Eventually I get:

![image](https://user-images.githubusercontent.com/7557867/212776559-28900505-c8b8-49ca-863b-a1f75a479594.png)

I have to run `thunderbird --safe-mode` and disable all addons, then I'm able to remove the beta add-on.

**Comment by cleidigh** [comment]
@Poikilos 
I am not on my dev computer so I may not be able to accurately describe certain things...
For the beta refer to #154, it was probably a download issue.
I have to assume Firefox /thunderbird get there unwriteable margins from the driver itself. Doing a Google search indicates this does come up with various printers and applications. 
The two  sets of advanced preference sets are edge or unwriteable for each side.
If you go to The config editor and search print you should find your printer and see the various margins.
For reference maybe you can post those.
We should be able to experiment with the edge and unwriteable sets to shift the headers and footers.
I think both use twips for units 1/1440 inches.
See what you find tweaking those.
PTNG only deals with the main margins.
@cleidigh

**Comment by Poikilos** [comment]
I tried "To access the Config Editor, go to Fx57Menu and select Settings. Search for config and click on the Config Editor button when it is displayed." from https://support.mozilla.org/en-US/kb/config-editor but cannot even get into it.

**Comment by Poikilos** [comment]
Yes, my printer driver is apparently at fault:
![image](https://user-images.githubusercontent.com/7557867/212820629-7d0f6db0-88e1-4d50-8776-f608a6a9c376.png)
- It would be nice if there was a way to fix this. It is going to be a problem for anyone with my printer model, and potentially any Brother user. Maybe even any network user since it is networked depending on how the CUPS device is added (some appear automatically, others are added manually when that fails--I am not sure which is which) and one 17 and one is 0. They both seem wrong if it is twips, which it seems to be, since the one above it that just says "printer" is 25 (which is still too low--that's only ~0.017 in).

**Comment by cleidigh** [comment]
@Poikilos 
It was not clear to me, were you able to make adjustments to get the headers and footers to appear?
@cleidigh

**Comment by cleidigh** [comment]
@Poikilos 
I found this slightly old support thread. Thunderbird uses the core Firefox print code so this is relevant. I would try testing both the edge and unwritable settings. Note edges are 1/100 in.
I have not found why these two types have what appears to be inconsistent behavior.  I can see the effect on the Save as PDF with the edge prefs only. Maybe they treat pdf drivers differently than others.

https://support.mozilla.org/gl/questions/1061569
@cleidigh

**Comment by Poikilos** [comment]
Sorry, I'm not sure how much I can help. For some reason:
1. When I search for "margin" now all I get is one copy of the printer
2. Changing the settings (even to a high number such as 50--assuming hundredths, that should be 1/2 inch; I even tried 400 but there is no change) does not affect the issue.

After restarting Thunderbird, both problems remain. I'm not sure why the config values have gone away.

**Comment by Poikilos** [comment]
Ok, the disappearing values must be some kind of networking delay. One of the network printers (2 copies of it) suddenly appeared *under* the "Add" (:heavy_plus_sign:) value box since the printer must have been detected while I had the search open.

**Comment by Poikilos** [comment]
The values are in the hundreds so it doesn't seem like 100ths to me. Twips make more sense:
- 170/1440 = ~.1
- 363/1440 = ~.252
- 357/1440 = ~0.248

The values seem to be gotten from the system, and when changed, they are ignored even if I restart Thunderbird and my values are still there.

**Comment by kiki-ja** [comment]
@Poikilos 
@cleidigh 

This is different approach than @cleidigh.
@Poikilos, let me ask you a question, and let me check.

１．Is the printer you are using correct as follows?

　Brother MFCL2740DW | Compact Monochrome Wireless Laser All-in-One Printer
　https://www.brother-usa.com/products/mfcl2740dw

２．Do you have a printer driver for Linux installed?

　Downloads | MFC-L2740DW | United States | Brother
　https://support.brother.com/g/b/downloadtop.aspx?c=us&lang=en&prod=mfcl2740dw_us_eu_as

３． Are you aware that margins can be set by default in Thunderbird without PrintingTools NG installed?

４． Are you setting your margins in 'More settings' of the print preview?
　![Print preview more settings](https://user-images.githubusercontent.com/80428201/213189533-e2f64edf-a2e4-4268-8931-0bdaa532ed60.png)

5. Is it possible to set the margin in the 'More settings' but it is not reflected?

@kiki-ja

**Comment by cleidigh** [comment]
@Poikilos 
I think you want to change the edge preferences, this worked for me.
print.[your printer].print_edge_top
(other edges...)
The edge units are 1/100in
These should move the headers and footers.
@cleidigh

**Comment by cleidigh** [comment]
@Poikilos 
Any luck with the print_edge preferences?
@cleidigh

**Comment by Poikilos** [comment]
- Earlier you asked about whether I've tried the custom margins in the Mozilla print UI. It says "Custom (mm)". The default (pre-filled) values are 12.7 mm (1/2 ") which doesn't fix it.
- If I change the edge values, it doesn't fix it. Each printer has its own margins in the print preview, and the 3 networked printers avoid unprintable areas and the manually-installed MFCL2740DW prints past the printable area, and the edge setting has no effect on any of them.

![image](https://user-images.githubusercontent.com/7557867/213934526-899564a8-b8e6-413c-bbfd-f34b15c46e6a.png)
- 20 assumes 1/100ths of an inch (.2 is the approximage unprintable area of my laser printer and most laser printers)
- I also tried 720, 720, 720, 720 (1/2 inch assuming twips). The issue is not fixed.
- On restarting Thunderbird, my custom values are still there, but the issue is not fixed.

In all cases, the footer still doesn't print, though it is visible on the print preview, and printing with the networked ones with a slightly higher margin visible on the preview still is too small and misses the whole footer.

**Comment by cleidigh** [comment]
@Poikilos 
That is a stubborn printer driver!
Since your other printers work as do thousands of others, I think we have to blame the driver.
I did have an idea to try:
- set the top and bottom edge preferences in the Mozilla save to pdf printer. You will see the effect in the preview. Then save and print. That should work as a workaround.
- @cleidigh

**Comment by cleidigh** [comment]
@Poikilos 
Were you able to try the PDF idea?
D you want to keep this open?
@cleidigh

**Comment by Poikilos** [comment]
I was already able to do it with PDF printer as a workaround. I'm not sure why you would want to close the issue if we haven't figured out the cause yet.

**Comment by cleidigh** [comment]
@Poikilos 
Absolutely we can keep this open. I thought that we both determined that it must be the driver as it seems to ignore the edge and unwritable margins.
These are not controlled by ptng so I am not sure where to go next.
@cleidigh
