### ISSUE TITLE
DOM Exception - is it a bug?

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#160]
If I close the print preview, I get

> Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable

printingtoolsng-pengine.js line 217
`printingtools.doc.styleSheets[0].deleteRule(printingtools.msgRestoration.ruleIndex);`

![grafik](https://user-images.githubusercontent.com/77779094/217366416-847f8b66-d60a-47ab-8e28-1accf4f4ce37.png)

and a warning.

**Comment by cleidigh** [comment]
@RRoenn 
Looks possible.
So far I cannot reproduce, but maybe with more tries.
@cleidigh

**Comment by RRoenn** [comment]
1. open thunderbird
2. open console - clear log
3. select mail - open print preview
4. close print preview - no error log
5. open print preview again
6. close print preview - DOMException in error log
7. now every time - DOMException in error log

**Comment by RRoenn** [comment]
I think this is not fixed-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 15.03.23, 01:28 schrieb Christopher Leidigh ***@***.***>:

   
  Closed #160 as completed.

**Comment by cleidigh** [comment]
@RRoenn 
Sorry I didn't note that I fixed this in my pre4 I am wrapping up today and releasing if the rest of my tests are good.
@cleidigh
