### ISSUE TITLE
copies are switched back to 1

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#161]
I have set 2 copies - open print preview - for a short moment I see the 2 copies - but the setting is automatically switched back to 1 - every printer

https://user-images.githubusercontent.com/77779094/217651124-ecbfffe9-2488-4491-996e-060316b38377.mp4

_Originally posted by @RRoenn in https://github.com/cleidigh/printing-tools-ng/issues/159#issuecomment-1423227109_

**Comment by kiki-ja** [comment]
@RRoenn

Is this the same issue as the following past report?

See also:
https://github.com/cleidigh/printing-tools-ng/issues/139#issuecomment-1344992264

https://github.com/cleidigh/printing-tools-ng/issues/139#issuecomment-1381695785

https://github.com/cleidigh/printing-tools-ng/issues/139#issuecomment-1382443876

@kiki-ja

**Comment by RRoenn** [comment]
@kiki-ja 
you are right, maybe

but this is not related to pdf-printers as in the comments mentioned.
Maybe we can track this last single bug here?

**Comment by cleidigh** [comment]
@RRoenn 
@kiki-ja @tidebre67
Reproduced this.
It turns out the ui sets the copies to the default 1, but after about 500ms
my fix is not elegant.
I set the value three times about 200ms apart that way it's hard to ever see the 1
@cleidigh

**Comment by cleidigh** [comment]
@RRoenn 
@tidebre67
@kiki-ja 
This is a totally separate issue from the margins.
If someone can verify the fix in b19 I can close.
@cleidigh

**Comment by RRoenn** [comment]
PTNG b19
Win11

copies are fixed, but now I have other observations.

- If I set pages 2-3, but the mail has just 1 page, before the fix b19 I got a red border around the wrong values. 
- a mail with 3 pages is printed totally, not just page 2 and 3
