### ISSUE TITLE
[time zero bugs] - before any printer is configured

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#163]
tb 02.7.2 (64-Bit)
PTNG: v2.2.0 - beta21

* install ptng (in this case v2.2.0-b21)
* restart tb
* disable ptng
* enable ptng

tab 2
Header order is missing
![grafik](https://user-images.githubusercontent.com/77779094/218220602-2c2c8ce5-b21d-452b-81be-6136081369d4.png)

tab 5
- no printer selected - can't select printers
- custom pages are red cornered
![grafik](https://user-images.githubusercontent.com/77779094/218220368-8d2d25f0-5b47-4ed3-bbc3-2adabf840275.png)

had to restart tb after enabling ptng
then all is okay

**Comment by cleidigh** [comment]
@RRoenn 
Do margins work ok then?
In 5 I have to be shipped off to bed. Will be back online at about 7:30 est if anyone still up
@cleidigh

**Comment by cleidigh** [comment]
@RRoenn 
I have done multiple tests with new profiles since I made it use the system default.
I am closing.
@cleidigh
