### ISSUE TITLE
Testing v2.2.0 - beta22

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#164]
@cleidigh 
@kiki-ja 
@tidebre67

my tests with ptng b22
1. delete all in about:config(): extensions.printingtoolsng.printer.*
2. all print_paper_size_unit are 1
3. download and install -b22
4. restart tb
5. **ptng settings:**
6. set copies: 3 - (not possible for my 2 pdf printer - okay)
7. set pages 2-3 and 2,4 (if I click edit field, is it possible to enable/switch "All" to "Custom"?)
8. set all margin to 15,5 mm - 15.5 - 15, - 15.  (, and . are working) (15. has red border; 15, has no red border) see picture 
   I can accept the settings, despite the red border
9. recheck ptng settings ... **margins stay with old values** - set margins to 1 mm - save - recheck - is working (margins set to 1.0)
10. set margins to 12 mm - save - recheck - **margins have value 0.5**
11. tried with different printer ... set margins to 12 mm - save - recheck - **margins have value 0,5**
   one has point - one has comma as decimal separator

@cleidigh 
**please save inch in print.PRINTER.print_margin_ not mm values** and use point as decimal separator for inch
(This also corresponds to my observations when I change the margins in the print preview without ptng)
![grafik](https://user-images.githubusercontent.com/77779094/218975354-422828c5-77a8-4a3f-b861-b5a8289ea596.png)

**picture to nr. 8**
![grafik](https://user-images.githubusercontent.com/77779094/218972770-636c3966-0ced-407a-b740-b71928fd4c40.png)

**Comment by tidebre67** [comment]
@cleidigh 
@RRoenn 
@kiki-ja 

As i can see b22 is a great step forward.
Did as Christopher requested and deleted ptng printer preferences.

Margins in mm.
Range margings accepted in print preview and ptng seeting and vica versa
and stay stable.
Except SAVE TO PDF, here still inches in margins and range margins.

Copies and select pages working fine.

Have noted that in the config editor there is no '...paper_size_unit' anymore,
except print.printer_Mozilla_Save_to_PDF.print_paper_size_unit

**Comment by cleidigh** [comment]
@RRoenn 
I will go point by point.

6. I assume you mean you could not set the 3 as copies is disabled for pdf printers
7. The custom field is only enabled if the custom radio circle is enabled. This is how the tb control work.
8. I do have to make the validation rules slightly different.  When the locale uses comma I should disable period. I found X. Results in a zero margin entry, this is a validation bug - easy fix 
9. All ok
10. Here I need better understanding, previous tests with 15mm and 1mm worked fine. Now if we change 15mm to 12mm, you say margins are 0,5  is this what you see in ptng or the preferences?  12mm does not even equal 0,5 in, but 0,5 would be a default for a margin in inches if somehow a value got reset to defaults. If I understand this, it is a strange bug I cannot reproduce.

11. see above

Your last comments : 
I save the margins into preferences according to the paperSizeUnit for the chosen paperId, I currently always check on save which units to use. I am not clear why you propose this?
I think your suggestion is to only allow the locale specific decimal comma for mm and period for inches. This makes sense.

So the exact issue with the 12mm appears to be the thing to focus on.

One other question, you said all printers had units == 1
I thought the prior reports were that everything but the Save to PDF was mm, is that not correct?
@tidebre67 @kiki-ja what do you guys see?

@cleidigh

**Comment by cleidigh** [comment]
@tidebre67 
I understand two issues 
1. The Save to PDF printer is in inches. Do you mean the paper_size_unit  in preferences or that ptng reports as in in the ui?
2. You are saying none of the other printers have a paperSizeUnit preference?

Disable ptng and use preview /print to change paper types and see that the preferences show the right paper id and units. Remember you have to print to save any setting change.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
Any test results?
@cleidigh

**Comment by RRoenn** [comment]
@cleidigh 
6. correct and works as expected
7. activation via the edit field would only be a convenience function. I know that from PDF/HTML forms and if that doesn't work in tb, that's okay too

> One other question, you said all printers had units == 1
> I thought the prior reports were that everything but the Save to PDF was mm, is that not correct?

Due to the many tests and trials, I no longer know my default setting. With other PCs, all are set to 1 and so I would continue with print_paper_size_unit == 1 in the future
That's my config:
![grafik](https://user-images.githubusercontent.com/77779094/219152254-1de48d81-84ed-452a-b2ff-1a494a6a7e1e.png)

> Here I need better understanding, previous tests with 15mm and 1mm worked fine. Now if we change 15mm to 12mm, you say margins are 0,5 is this what you see in ptng or the preferences? 12mm does not even equal 0,5 in, but 0,5 would be a default for a margin in inches if somehow a value got reset to defaults. If I understand this, it is a strange bug I cannot reproduce.

clarification to 10. 11. and more ...
Here I speak only about ptng settings. In previous tests, you store the settings in your own key (extensions.printingtoolsng.printer.*). so they worked fine. Now you take the tb settings.
And my guess is, tb stores the margin always in inch, regardless of the print_paper_size_unit. The unit is just for the representation of the presentation.
These were my results when I only changed the settings via the print preview.
And so tb will take the saved 15, assuming it's inch; convert them to mm. Realizing that the value is way too big and discarding it and reverting to the default values of 0.5, which are then displayed in ptng settings.


**Now in print preview** (print_paper_size_unit == 1)
Mozilla_Save_to_PDF margins are in mm
![grafik](https://user-images.githubusercontent.com/77779094/219158750-7b94e592-1b9b-46ae-a884-0cbcdb285c97.png)

tb about:config()
![grafik](https://user-images.githubusercontent.com/77779094/219159089-5eb89e80-d71d-46f5-8c18-e081654af3b6.png)

The margins for all my printer are stored in inch.
I hope you get my point now?

in contrast to this, the paper height and width are again stored in mm. I have no idea what they were thinking.

**Comment by tidebre67** [comment]
> @tidebre67 I understand two issues
> 
> 1. The Save to PDF printer is in inches. Do you mean the paper_size_unit  in preferences or that ptng reports as in in the ui?
> 2. You are saying none of the other printers have a paperSizeUnit preference?
> 
> Disable ptng and use preview /print to change paper types and see that the preferences show the right paper id and units. Remember you have to print to save any setting change. @cleidigh

@cleidigh
I am out, reading from mobile. Back tomorrow around noon, reverting with further test results, if anything to report .
1. Not quite clear to me. The paper_size_unit is in the config Editor and in respect of item 2. all other printers are not in config editor anymore.

Reverting to your last sentence asap.

**Comment by cleidigh** [comment]
@RRoenn 
Now I am off the charts confused.
I have to be aware of the paper units and how can they all be in inches?
Does @tidebre67 and @kiki-ja see there printers the same way?
How would it work at all if we use the wrong units?
We have to do methodical testing with preview and see what we can learn I guess?
@cleidigh

**Comment by RRoenn** [comment]
@cleidigh 
I did, please read https://github.com/cleidigh/printing-tools-ng/issues/162#issuecomment-1426528167 and below

**Comment by kiki-ja** [comment]
@cleidigh 

Sorry, I skipped the testing of PTNG 2.2.0-b22.
I have presented below the test results of PTNG 2.2.0-**b23**.
https://github.com/cleidigh/printing-tools-ng/issues/139#issuecomment-1432973738

@kiki-ja

**Comment by RRoenn** [comment]
I am closing this issie as it is considered in b23

thanks
