### ISSUE TITLE
to much new line

### ISSUE THREAD

**Issue by Mannshoch** [cleidigh/printing-tools-ng#17]
Add an Option to remove double new-lines in Mails.
I don't know why but some Mails contain too much space between passages

**Comment by cleidigh** [comment]
@Mannshoch 
this is actually the second time this issue has come up
so far I have not been able to figure out the problem
are the e-mails from Outlook?
they seem to have some weird stuff ;-)
Christopher

**Comment by Mannshoch** [comment]
I'm not sure. I could not remember which mail it was. But may the problem is kind of the different between <br> and <p> 
Could not say how Outlook work with that.
