### ISSUE TITLE
Printing with external FiltaQuila fails after single print

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#179]
PTNG v2.2.0
OS:
TB:
Console capture of failed print:

@ryanhobrock
Two reports of the following: 

After a single print subsequent printing fails.

I believe I found this issue, it affects non PDF printing.
Here is a beta fix:
https://github.com/cleidigh/printing-tools-ng/blob/v2.2.1/xpi/printing-tools-ng-2.2.1-b1-tb.xpi

Please report results.

**Comment by ryanhobrock** [comment]
The beta fix resolves the issue. Thank you @cleidigh!

**Comment by cleidigh** [comment]
@ryanhobrock 
Excellent.
Sorry for the problem, I feel badly as I know many people use it for food orders. Hopefully neither you nor others were too badly affected.
I will get an official release out asap.
Thanks for both your alert and quick testing!
Christopher

**Comment by cleidigh** [comment]
@YvesMattle 
Since I know you are using FiltaQuila + PTNG, I wanted to let you know v2.2.0 just released has a dumb bug for this. There is already a beta fix (see above)
I have the release in the review Q.
Hopefully you were not affected.
Cheers 
@cleidigh

**Comment by cleidigh** [comment]
All v2.2.1 has been released addressing this.
@cleidigh

**Comment by cleidigh** [comment]
@ryanhobrock 
That's good, I am glad there were no major issues.
@cleidigh
