### ISSUE TITLE
68/78 v2.0.0 Release/Status

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#18]
Latest: https://github.com/cleidigh/printing-tools-ng/blob/v2.0.0/xpi/printing-tools-ng-2.0.0-tb.xpi

v2.0.0 Released !

Thanks for everyone's help 💯 

Please remember to update from ATN

See screenshots @ end

**Comment by librelegal** [comment]
Hi Christopher, you made my christmas come true. You unfortunately pointed to an old file, the right file works: https://github.com/cleidigh/printing-tools-ng/blob/v2.0.0/xpi/printing-tools-ng-2.0.0-b1-tb.xpi

**Comment by cleidigh** [comment]
@librelegal 
that's what happens when Santa rushes things out ;-)
I will fix the link thanks!
Merry Christmas all !
Christopher

**Comment by Mobeeuz** [comment]
All good here on Win10 now. No one would have blamed you for taking Xmas off you know 🥇

**Comment by cleidigh** [comment]
@Mobeeuz 
Thanks, But Santa has to keep the programmers busy!
b3 fixes the optionboxes and icons

**Comment by archfiddler** [comment]
Hi Christopher
Have just downloaded and mostly working, brilliant! Will you be adding a 'Print' custom action to filter rules?

**Comment by cleidigh** [comment]
new icons

![image](https://user-images.githubusercontent.com/25272315/103329979-672e3f80-4a2d-11eb-8beb-ff30276d0983.png)

**Comment by cleidigh** [comment]
@archfiddler 
Thanks!
can you give me a bit more detail I'm not sure exactly what you're asking for.
Christopher

**Comment by archfiddler** [comment]
Hi Christopher, Your message made me question myself! I forgot that the process I had been using for so long was FiltaQuilla adding the 'print' custom action and then Printing Tools formatted everything nicely! Just checked and FiltaQuilla has been upgraded to v78 compatibility so everything working together again at my end. 
I dont know if this is a PT issue or something else I had set up and now forgotten... The attachments are listed in the header (I would prefer a new line for each attachment?) but they also used to appear at the end of the printed email. Now I just get a line with word 'Attachments:' in it but no list?

**Comment by cleidigh** [comment]
@archfiddler 
all
check out the new icons, hidden headers, # attachments per line

![image](https://user-images.githubusercontent.com/25272315/103468647-59c4ce00-4d29-11eb-9f57-6629b95e27a8.png)


![image](https://user-images.githubusercontent.com/25272315/103468657-752fd900-4d29-11eb-97d9-52c3104aa10e.png)
