### ISSUE TITLE
Greek Translations

### ISSUE THREAD

**Issue by ichnilatis-gr** [cleidigh/printing-tools-ng#180]
Hi, 
I would just like to ask: How could anyone contribute to the translation of the plugin? There are some mistranslations in Greek.
Thank you!

**Comment by cleidigh** [comment]
@ichnilatis-gr 
Great, I got your PR. I am actually going to change to merge with the next beta branch (which I have to create) because I never develop on master.
Once I do that I will post v2.2.2-b1 so you can double check and use until I do the release. I want to wait for other potential issues to come in.
 
That will be in a bit as I am still doing post release stuff.
In the meantime I can use your transactions to improve my Greek  :-)
Can I ask how you use PTNG?
Also we have a grand total of 62 el locale users. How can we get those numbers up?
Are you on the main land or one of the many wonderful islands?

Efhxaristo poli !
X

**Comment by cleidigh** [comment]
@ichnilatis-gr 
Did you get a chance to check out the beta?
@cleidigh

**Comment by ichnilatis-gr** [comment]
It looks good! Thank you!
I would just like to change some letters to capital letters for consistency.
In which file could I make the change?

**Comment by cleidigh** [comment]
@ichnilatis-gr 
I merged these into b3, thanks.
@cleidigh

**Comment by ichnilatis-gr** [comment]
It was my pleasure!

Regarding your questions, I am from the mainland and I use PTNG mainly in order to hide headers, set their order and cut the long ones. But other settings are sometimes useful too.

**Comment by cleidigh** [comment]
@ichnilatis-gr 
Would you be able to translate a help paragraph update?

<p>
	These options allow you to set the default printer as well as 
	per printer page options. If the persistent mode is set for the 
	default printer, then a printer change in preview will be reset 
	to the PrintingTools NG printer for each subsequent print.
	It is also possible to set the silent mode where the preview dialog is
	not shown and printing is done immediately.
</p>

Appreciated 
@cleidigh

**Comment by ichnilatis-gr** [comment]
> If the persistent mode is set for the default printer, then a printer change in preview will be reset to the PrintingTools NG printer for each subsequent print.

Could you please explain the above case to me? Thank you.

**Comment by cleidigh** [comment]
@ichnilatis-gr 
The persistent flag sets the printer to the PTNG printer before each print even if the user changes the printer in the preview. Normally if the user changes the printer in preview that would be the new default printer.
@cleidigh

**Comment by ichnilatis-gr** [comment]
I am giving you my translation of the text that you have asked me to translate: 

Αυτές οι επιλογές σας επιτρέπουν να ορίσετε τον προεπιλεγμένο εκτυπωτή καθώς και τις επιλογές σελίδας ανά εκτυπωτή. Εάν έχει οριστεί η μόνιμη λειτουργία για τον προεπιλεγμένο εκτυπωτή, τότε μια αλλαγή εκτυπωτή στην προεπισκόπηση δεν θα επηρεάζει την μόνιμη ρύθμιση και για κάθε επόμενη εκτύπωση θα ορίζεται ο εκτυπωτής PrintingTools NG. Είναι επίσης δυνατό να ορίσετε την αθόρυβη λειτουργία, κατά την οποία το παράθυρο διαλόγου προεπισκόπησης δεν εμφανίζεται και η εκτύπωση γίνεται αμέσως. 

I hope it is correct.

**Comment by cleidigh** [comment]
@ichnilatis-gr 
Thank you much.
Should hopefully be releasing in a couple of days.
@cleidigh
