### ISSUE TITLE
"Use header background color" doesn't work

### ISSUE THREAD

**Issue by Thefaroah** [cleidigh/printing-tools-ng#182]
"Use header background color" doesn't work. Other than that, great add-on.

**Comment by cleidigh** [comment]
@Thefaroah 
You have to set Print Backgrounds in the preview and that will enable colored backgrounds. I realized I have to add this to the help.
Let me know...
@cleidigh

**Comment by Thefaroah** [comment]
It worked. However I had hoped just the header background color would show.
Might I suggest 2 options to replace "Print backgrounds":
1. Show header background
2. Show letter body background

**Comment by cleidigh** [comment]
@Thefaroah 
Those labels are part of Thunderbird so I can't really change them.
What I may be able to do is set this if the background color is set in PrintingTools.
@cleidigh

**Comment by Thefaroah** [comment]
Having this option set in 2 different places just confused me. (NG options and Print options).
Good luck. And keep me posted.

**Comment by Thefaroah** [comment]
Just realized that PTNG and Print preview are two separate entities. So I appreciate your efforts there. Good luck again.
The Print and Page options appear to work as expected.
The PDF options?  Setting the options make a lot of sense. Created a couple PDFs with no issues.
However, there 's an issue with different printers. Used Microsoft print PDF and was asked the PTNG question. That was OK.
Changed printer to non-PDF (after "cancel" of PTNG question), and the PTNG question won't appear until I fool with printer destination.
Must the destination printer be a "PDF" creator?

BTW... temporary fix for the body background: In settings, set the color to white in Language and appearance.

**Comment by cleidigh** [comment]
@Thefaroah 
Thanks for the feedback!
I think I understand your question, but follow up if I  miss.
The PDF output options in PrintingTools are basically accomplishing the following 
- Allow for silent printing by using a defined directory and naming system 
- Allow for multiple message printing 
- Token based naming with multiple elements 

If silent printing is off and you print to a non pdf printer it goes straight to preview. For PDF printers you get to choose auto save or preview. If silent printing were on it just auto saves

There is also external printing with FiltaQuila.

As I said the addon has to do a number of tricks to partially take over native print functionality, but not everything.
@cleidigh

**Comment by Thefaroah** [comment]
All is clear now. And you're correct, the printer must be a PDF type for all of this work properly.
Within PTNG I set the default printer to Microsoft Print to PDF. Now I get the the choice.
Still one glitch. Select Cancel at the choice, select a non-PDF printer for the printer and then print. The glitch: this new printer becomes the default printer in Preview and PTNG. The choice is no longer available until I reverse engineer the default printer.
Could PTNG "remember" the default printer that I selected in PTNG options?

**Comment by Thefaroah** [comment]
Another glitch (may be Tbird): Printing to PDF eliminates the header background color.

**Comment by cleidigh** [comment]
@Thefaroah 
Hmm you are finding the weaknesses of the "man in the middle" :-)

- I think the preview's Print Backgrounds is persistent per printer so you should ony have to set it once. Are you seeing something different?
- We had some late discussion on making the PTNG printer persistent 

I think I will make two issues for these. If i can set the Print Backgrounds according to the PTNG header background being set this will avoid the type of confusion you had.
Secondly having a toggle for default printer persistence would be good 

@cleidigh

**Comment by Thefaroah** [comment]
100% agree.
I played around with PDF function and really like it. Having PTNG "remember" the selected printer would make things so much easier. Even went a bit further. Installed EditEmailSubject MX addon to modify the subject. Now the PDF shows what I want it to show. For now, I simply edit PTNG options to set the printer to PDF if it's set to something other than PDF.

**Comment by Thefaroah** [comment]
BTW... the print background is much less important than the PDF.

**Comment by cleidigh** [comment]
@Thefaroah 
Just curious, did you see in help all the tokens besides subject you can use? That system I first created for ImportExportTools. The new filters for latinize and emojis were inspired by another user. I have had some pretty positive feedback on being able to select multiple messages and have them all auto named for PDF 
@cleidigh

**Comment by Thefaroah** [comment]
Yes, I have. And they're all set to my liking.
Don't see anywhere for emojis. Just the five tokens listed in the options.

**Comment by cleidigh** [comment]
They are part of the filter options for the naming. The idea is that many systems want pure ASCII filenames for maximum portability.
Just another point of flexibility.
C

**Comment by Thefaroah** [comment]
Doubt I'd use emojis. The important thing for me was the printing of emails.
Now That I know how to navigate PTNG, I'm good to go.
Let me know when you want me to help with PTNG... from a user's point of view, of course.

**Comment by cleidigh** [comment]
@Thefaroah 
Got this in to b3.
You can grab from release status
- #189 
- @cleidigh

**Comment by Thefaroah** [comment]
Updated v2.2.2. Still the 2 issues:
1. Background colors still not behaving.
2. The default PTNG printer is still not persistent. Change the printer in the Tbird preview and it changes it in the PTNG options.

**Comment by cleidigh** [comment]
@Thefaroah 
I have done the persistent printer yet.
What is not working with the backgrounds?
It might be necessary to check the ptng printer options.
I am wondering if it got updated with the new header bk color flag.
@cleidigh

**Comment by Thefaroah** [comment]
I think the issue is beyond your control.
In Tbird's Print/Preview options, it's an all or nothing for header and body background printing.
I can live with that, knowing now how it works. A simple occasional color tweak (change to white) and all is how I want it to print: Color header, white background.
And  it's the header background color set in PTNG that makes the big difference.

Bottom line:
Background color printing... minor issue, easy work around.
Persistent PTNG printer... would be really nice, but easy work around also.

**Comment by cleidigh** [comment]
@Thefaroah 
I am not sure I understand. What b3 does is toggle the Print Background Colors if one has set a background color in PTNG which is what we discussed.
The printer issue is on deck #188 
@cleidigh

**Comment by Thefaroah** [comment]
In Tbird:
![image](https://user-images.githubusercontent.com/46969365/229248207-47ff72bb-90ba-42e9-9bd0-d1b44e5e05d2.png)
In PTNG:
![image](https://user-images.githubusercontent.com/46969365/229248326-c38b1e8e-8cb2-49e5-ae53-3912ac717597.png)
In Tbird Print/Preview options:
![image](https://user-images.githubusercontent.com/46969365/229248538-e42d29cf-d1d6-4fba-acbc-c3a79fcb74c2.png)
This last option shuts both header and body background off (or on). All this while I thought (incorrectly) that body was only affected by this option. Assumed that because PTNG set the header color, it would have remained intact. Not so.

**Comment by cleidigh** [comment]
@Thefaroah 
What or where is the thunderbird background option?
I want to see what it controls.
You are correct, the print background colors will enable elements or divs with a background color to render with color header, body, etc.
@cleidigh

**Comment by Thefaroah** [comment]
In Tbird Print/Preview options:
![image](https://user-images.githubusercontent.com/46969365/229251170-5b27ce41-ed91-40e0-872c-7a314a63be15.png)
After it expands scroll dow to bottom:
![image](https://user-images.githubusercontent.com/46969365/229251211-89dc294d-f396-43ee-a9dd-b5b4fd28a895.png)

**Comment by cleidigh** [comment]
@Thefaroah 
Not the preview option, but the Tbird background at the top of your first list with the color beige 
What is that?
@cleidigh

**Comment by Thefaroah** [comment]
In Tbird setting > General:
![image](https://user-images.githubusercontent.com/46969365/229289703-e2b134ff-4365-4966-b4aa-58e730be0401.png)
Click Colors:
![image](https://user-images.githubusercontent.com/46969365/229289726-c2905b22-d423-4b95-b193-440b2373ec71.png)

**Comment by cleidigh** [comment]
@Thefaroah 
Check out b4, got the persistent printer in. Testing would be helpful ;-)
- #189

**Comment by Thefaroah** [comment]
The link shows b3. Will be glad to help with b4.

**Comment by cleidigh** [comment]
@Thefaroah 
I am in the middle of all the paperwork now.
Link is updated now.
@cleidigh

**Comment by Thefaroah** [comment]
Chris,
With your permission, may I share the b4 download link?

**Comment by cleidigh** [comment]
@Thefaroah 
Yes, absolutely, everything we do is open.
The more eyes the  better!
BTW you should not have had to reboot so I have to figure that out.
@cleidigh
