### ISSUE TITLE
Make Preview "Print Backgrounds" toggle with "Use Header Bg Color"

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#187]
See 
- #182 
for discussion with @Thefaroah regarding need to set Print Backgrounds.

If we toggle printSettings.printBGColors or showBackgroundColors when user has set Use Header Background Color, the use won't have to.
@cleidigh

**Comment by Thefaroah** [comment]
Awaiting v2.2.2. Best of luck.
