### ISSUE TITLE
Header "To" always in last position with locale "fr"

### ISSUE THREAD

**Issue by DenB10** [cleidigh/printing-tools-ng#190]
Hello,

I am a French user so it's normal that I use the French version of Thunderbird ;)

I discovered a bug in PTNG that occurs if Thunderbird is in French but not in English (US)!

My configuration:
- Windows 7 64-bit (or Windows 10 64-bit via VirtualBox)
- Thunderbird (or Betterbird) 102.9.0 64-bit
- PrintingTools NG v2.2.1 (or 2.2.0 or 2.1.5 or 2.1.4 or 2.1.3))

To reproduce the issue:
- Install the French language pack for Thunderbird
- Choose the French language in the Thunderbird settings and restart Thunderbird
- Do a print preview and notice that the "Pour" header is in the last position, regardless of the header order setting (which does not happen with the other headers)
-  Install the English (US) language pack for Thunderbird
- You can see that the "To" header is in the right position (As set in the options)

The error console doesn't seem to indicate anything wrong!
Strange, isn't it?
Note finally that I did the test on a new fresh Thunderbirdprofile with only PTNG installed as extension and the conclusion remains the same. So another extension isn't incriminated.

If you could debug or find an explanation for this phenomenon, I would be grateful.

P.S. : Are you interested in an improved translation in French, or not ?

**Comment by cleidigh** [comment]
@DenB10 
Merci !
Your description and steps were very complete and precise. I reproduced it already.
It was another case of an odd termination in Thunderbird's mime headers fr locale file "outwitting" my logic.
I should have a beta fix out tomorrow.

I would much appreciate any translation help  ! I would love to increase our French user count, it's only around 700. 
If you are going to do a pull request do it against v2.2.2 branch.

Cheers
@cleidigh

**Comment by cleidigh** [comment]
@DenB10 
You can grab b2 beta from the top of the release status issue for v2.2.2
- #189 

I did a bunch of hdr moves and looks good.
@cleidigh

**Comment by DenB10** [comment]
Works well, thank you for your responsiveness.

I'm now working on the French translation, it will be ready probably tomorrow.
Just a remark though: would it be possible to add the possibility to localize the accesskeys in the context menu of the button? "Aide (H)", it's not very nice!

Thanks again and good night (it's late here)!

**Comment by DenB10** [comment]
Arrangements completed, I hope it will be ok this time?

**Comment by DenB10** [comment]
@cleidigh 

I see that you had to manually edit the printingtoolsng.dtd file. I'm sorry for the work involved.

The help file has not been merged yet, are there still problems?

**Comment by cleidigh** [comment]
@DenB10 
Afternoon...
I did manually merge the dtd to restore ordering and removed entries.
Just a suggestion  (IMHO): 
When doing PRs on files like these even though ordering may not have a functional difference, maintaining it keeps comparison better. Also removing things if you don't know their purpose creates potential issues.
No big deal for now.
The important thing is the fr ui looks Tres bien now (even my high school French can tell that %-) thanks)

I have to play with the help today among other support issues. Have to merge some other stuff into it also.
@cleidigh

**Comment by DenB10** [comment]
> I did manually merge the dtd to restore ordering and removed entries.

I am sorry to have caused you this extra work instead of helping you!

> The important thing is the fr ui looks Tres bien now (even my high school French can tell that %-) thanks)

It is I who thank you for your efforts in keeping this great extension alive.

P.S.: I just pulled request a new version of the help file that will allow a better comparison. Have I learned my lesson well?

**Comment by cleidigh** [comment]
@DenB10 
Phew...b3 has a bunch of stuff, just posted.
The fr ui and help look great.
I did have to make one change to help... Adding you to the credits 🥇  %-)

Have to add to the other locales when I tweak them with the other diffs.
Very much appreciated.

See release status 👍 - #189 
@cleidigh

**Comment by DenB10** [comment]
> Adding you to the credits %-)

It's too much of an honor :-)

A final question: you wrote above:
> I would love to increase our French user count, it's only around 700.

How do you know that?

**Comment by cleidigh** [comment]
@DenB10 
TB on the addon site provides statistics. I have actually made these public so you should be able to see them. Try this link, otherwise I can find one.
https://addons.thunderbird.net/EN-us/thunderbird/addon/printingtools-ng/statistics/usage/languages/?last=90

BTW reviews are always welcome  :-)

@cleidigh

**Comment by DenB10** [comment]
Ok, thanks for the info :+1: 
I didn't know that, but I often go on ATN!
