### ISSUE TITLE
Page Ranges won't work when printing multiple email at the same time

### ISSUE THREAD

**Issue by YakumoHamaji** [cleidigh/printing-tools-ng#195]
Hello
When I highlighted two or more emails at thunderbird, after I click print (NG), It will print every pages on those emails even I did set 1 at page ranges
This function work perfectly fine when I do only print one single email
Any suggestion?

====
off topic:
I'm a programing noob, would like to ask if I do only want the header border + add "attachment:" in header section, what exact code should I add in userchrome.css? (while add-on is disable)

Thanks for help

**Comment by YakumoHamaji** [comment]
> @YakumoHamaji Thank you for your post on our new feature! This requires a lot of tricky methods since we are injecting ourselves into the print process. I will investigate.
> 
> On your question (btw "noob" is great %-)
> 
> userChrome.css does not have anything to do with PTNG, maybe I misunderstood your question on that. If I understand what you want it is a header with a border and ONLY the Attachment field?
> 
> This is easy.
> 
>     * Set the border CSS on the Headers tab
> 
>     * Inthe headers order list, hide all fields except Attachments
> 
> 
> Is that what you are looking for? @cleidigh
Thanks, this will be a great help.
I discover that while printing multiple emails with NG, no printing prompt popup appear, that's why I can't change my printer (which should be useful for alot of users), and maybe that is also the reason the page ranges not working.

=============
(off-topic continue)
![unnamed](https://user-images.githubusercontent.com/129287503/228723205-b03047ab-6398-4493-8a4a-b6b6b06bdf06.png)

Like this, not hide all fileds but make attachments under the header (and if cc and bcc available, put it under attachment), with a border around it, like what NG can do.
Back in the old days when printing tools outdated and NG isn't appear yet, I search via google and saw somebody suggested that we can modify userchrome.css (or other css?) for reaching the same result, is that true?
NG appear saved me, but in case one day something bad happens, it's always good if I have the knowledge for reaching my goal with other ways

Regards :)

**Comment by cleidigh** [comment]
@YakumoHamaji 
I was able to fix this in beta 3.
Thank you for finding this important issue.
You can get b3 here : 
- #189 
@cleidigh

**Comment by cleidigh** [comment]
@YakumoHamaji 
If maybe you could make some sort of picture that might help.
@cleidigh

**Comment by RRoenn** [comment]
@off topic
I can imagine what @YakumoHamaji wants, but this won't be possible with just CCS and userChrome. There's way too much magic in PTNG. Unfortunately, I've also found that it's not that easy to use userChrome anymore. I gave it up.

@RRoenn

**Comment by cleidigh** [comment]
@RRoenn 
As you can see I am doing some patching, but nothing big...
I do get the feeling that the idea is outside of the normal pattern of PTNG. As you said there is a lot going on most are not aware of.
I am still trying to start the process of updating for the big changes in v115.
I have three with the critical ImportExportTools  NG so I will probably dissappear for a while.
Cheers 
@cleidigh

**Comment by YakumoHamaji** [comment]
> @YakumoHamaji I was able to fix this in beta 3. Thank you for finding this important issue. You can get b3 here :
> 
>     * [v2.2.2 Release Status #189](https://github.com/cleidigh/printing-tools-ng/issues/189)
>       @cleidigh

@cleidigh 
Sorry for the late reply
The function work in multi emails printing now, thanks :)
But can I also request the function to change the printer easily while I print multiply emails? (because I need to switch between printers and PDF Creator twice each time I print those email)

Having the popup like thunderbird itself will be great:
![Untitled](https://user-images.githubusercontent.com/129287503/229408489-0b478ee3-6ef0-422b-bcaa-5fd17043694e.png)

or any other ways that can switching between printers

**Comment by cleidigh** [comment]
@YakumoHamaji 
So you are asking for a printer prompt for each message to change the printer with multiple messages?
This is the opposite of what most users do which is to print silently without having dialogs.

just so I am clear can you describe the sequence you would expect for printing an example three messages A, B, C

@cleidigh

**Comment by YakumoHamaji** [comment]
> 

@cleidigh Usually I print multi-emails 5-10 times/Day (depends on how much emails I receive), each time need to switch between real printers and PDF creator (Virtual printer) for saving soft copy + hard copy

>This is the opposite of what most users do which is to print silently without having dialogs.
Seems "print without the dialog windows" set to default "ON" for multi-emails printings? 
is it some kind of technical difficulty?

One quick idea: if bring up the dialogs is difficult, maybe we can "create different shortcut" for different print?
For example, it's Print...(NG) now while right click, bring a new function which we can choose to create shortcuts in the add-on setting page, as a result, while we right clicking those highlighted emails, it will like: 
Print NG (Printer A)
Print NG (Printer B) ?
(which is what i choose to create those printer's shortcut in the add-on setting page)

Many thanks :)

**Comment by cleidigh** [comment]
@YakumoHamaji 
I didn't forget you!
Just off on other things.
I think I have a working solution for the printers.
I am doing this as "experimental" for now.
To enable it you put "msprompt" (no quotes) in the debug options. This will prompt before each print. For pdf printers you do not need to select Print to file, ptng will take care of that.
Let me know what you think.

Grab b4 from : 
- #189 
- @cleidigh

**Comment by YakumoHamaji** [comment]
> @YakumoHamaji I didn't forget you! Just off on other things. I think I have a working solution for the printers. I am doing this as "experimental" for now. To enable it you put "msprompt" (no quotes) in the debug options. This will prompt before each print. For pdf printers you do not need to select Print to file, ptng will take care of that. Let me know what you think.
> 
> Grab b4 from :
> 
>     * [v2.2.2 Release Status #189](https://github.com/cleidigh/printing-tools-ng/issues/189)
> 
>     * @cleidigh

Hello!

Thanks very much for the update
The msprompt works fine, but got one bug:
msprompt popup as many time as the sum of the emails I highlighted

For example, when I hightlight 5 emails and print, the first msprompt popup, then the second appear after I click "ok(print)" at the first prompt  (p.s: 5 mails can be successfully print after I confirm the first prompt, doesn't need to click the second prompt for second email)
The normal performance should be 1 prompt only for all emails

Regards
@cleidigh

**Comment by YakumoHamaji** [comment]
> @YakumoHamaji This is not what I understood before. I don't want to go on the wrong path again so let me give an example of what you are thinking :
> 
>     * we select two messages or more A, B,...
> 
>     * we click the PTNG button
> 
>     * *** we display the system print dialog, current PTNG printer is selected
> 
>     * user can change printer (to printer X) and click print
> 
>     * message A is printed to printer X
> 
>     * messages B and any others selected are printed to printer X with no dialogs
> 
> 
> Please let me know as soon as possible because I need to finish. @cleidigh

Yes, that's exactly what I was thinking (messages B and any others selected are printed to printer X with no dialogs)
Because I used to print like 20-40 mails together each time, having 20-40x dialogs will not be a good idea :D

Thanks for the quick respond
Regards
@cleidigh

**Comment by cleidigh** [comment]
@YakumoHamaji 
Arigato!
Your English is excellent , I wish I knew more than my ten or so words in Japanese, but I used them well on my two trips to Tokyo %-)

I will change the logic for the next beta.
@cleidigh

**Comment by cleidigh** [comment]
@YakumoHamaji 
ok get b7 from the release status 
This does the single prompt before doing a multiple selection print.
Note the system dialog does not see the Mozilla save to pdf pseudo driver so you can't print to it this way.
@cleidigh

**Comment by YakumoHamaji** [comment]
> @YakumoHamaji ok get b7 from the release status This does the single prompt before doing a multiple selection print. Note the system dialog does not see the Mozilla save to pdf pseudo driver so you can't print to it this way. @cleidigh

Thanks, it's working nicely now!
Although for some reason PDF Creator doesn't work together with this add-on , but Microsoft print to PDF works so that's fine
===
But elsewhere seems broken: Page Range for **Single** email printing won't work, it used to select "Custom" and fill in the number automatically which I entered in the add-on setting page, now it just "All" when I print single email  (Multi emails work fine)

@cleidigh

**Comment by cleidigh** [comment]
@YakumoHamaji 
Ok two steps forward and one back.
Sorry, yes I broke the page ranges with a mistake, already fixed in b8.
Should be out tonight.
@cleidigh

**Comment by cleidigh** [comment]
@YakumoHamaji 
I got b8 posted in the release status.
Fixed what I broke and we should be able to release.
@cleidigh
