### ISSUE TITLE
Question: Reset PrintingTools NG Settings back to default

### ISSUE THREAD

**Issue by ebnerjoh** [cleidigh/printing-tools-ng#206]
Hi,

I was playing around with the options and now I am not able to revert back to defaults. Even a uninstall/install of the Plugin is not resetting my options back to default.

Br,
Johannes Ebner

**Comment by ebnerjoh** [comment]
Thunderbird on Raspbian.

**Comment by RRoenn** [comment]
@ebnerjoh 

Hello,

can go to about:config ?

- uninstall plugin 
- delete all entries with "extensions.printingtools*"
- do a fresh installation of the plugin

@RRoenn

**Comment by ebnerjoh** [comment]
Thanks!
