### ISSUE TITLE
Date Format (minor glitch)

### ISSUE THREAD

**Issue by Thefaroah** [cleidigh/printing-tools-ng#21]
**Long and localized** and **Long UTC** are reversed. **Short (native)** works as expected.

![image](https://user-images.githubusercontent.com/46969365/104137313-be0b1180-5369-11eb-81db-7cd7b2de5cdc.png)

**Comment by cleidigh** [comment]
@Thefaroah 
thanks for the find, happy New Year's!
I did a quick check and verified that 'long and localized'  === UTC
however, there is no difference I see between the other two options
can you post an example of what you see for each situation?
Christopher

**Comment by Thefaroah** [comment]
Here's the three examples"
![image](https://user-images.githubusercontent.com/46969365/104187144-690ce100-53e5-11eb-815b-3a2d7b321294.png)
![image](https://user-images.githubusercontent.com/46969365/104187166-7033ef00-53e5-11eb-819d-39773fdadab0.png)
![image](https://user-images.githubusercontent.com/46969365/104187188-75913980-53e5-11eb-880e-f2e153b7ea7b.png)
And a SAFE and happy new year to you.
Mike

**Comment by cleidigh** [comment]
@Thefaroah 
as I expected it was a basic logic issue,presumably been there while
I still have to figure out handling the received date, I have to re-create
short format successfully for all locales, that's next
you can check the first fix with b1  below
Christopher

https://github.com/cleidigh/printing-tools-ng/blob/v2.0.1/xpi/printing-tools-ng-2.0.1-b1-tb.xpi

**Comment by Thefaroah** [comment]
Getting close Christopher. Here's the three result:

![image](https://user-images.githubusercontent.com/46969365/104320583-8490ee00-54b0-11eb-8868-ca2f8e3dd22c.png)
![image](https://user-images.githubusercontent.com/46969365/104320602-89ee3880-54b0-11eb-84c1-f682bb3e6d3e.png)
![image](https://user-images.githubusercontent.com/46969365/104320618-8e1a5600-54b0-11eb-904d-5e65ca45a388.png)

Long and localized just needs tweaked.

Thanks, Mike

**Comment by cleidigh** [comment]
@Thefaroah 
unfortunately I am not sure the definitions for the formats are universal.
for instance is not clear to me what is wrong with the "long and localized"
I thought it was just the inclusion of seconds ?
this is part of my problem fixing the other  the issue with received date
Christopher

**Comment by Thefaroah** [comment]
You're correct about the "long and localized". I just included all three options and their results. Sorry for the confusion.
Please don't lose any sleep over this.

My interpretation is for US, perhaps European might be different:
Short = 01/13/2021, HH:MM
Long = Wed, 13 Jan 2021, HH:MM
Personally, I don't care about the seconds showing nor the UTC time.
Thanks again, Mike

**Comment by cleidigh** [comment]
@Thefaroah 
believe me I'm not losing sleep!  just want to get it correct/sensible
I think YOUR example for "long" makes sense, however, correct or not
it does not match the original extension behavior as I inherited it.
the real fix is for me to introduce a fully custom date format library/option
as I have done with two other extensions.  that will take some work.
I have to see what is available concerning [legitimate] localized date formats
Christopher

**Comment by cleidigh** [comment]
@Thefaroah 
okay this should be much better
I like to your long-term format
check out
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.1/xpi/printing-tools-ng-2.0.1-b2-tb.xpi
Christopher

**Comment by Thefaroah** [comment]
Perfect Christopher...
Thanks for your efforts.
Stay safe during these trying times.
Mike

**Comment by cleidigh** [comment]
you stay safe also !
Christopher
