### ISSUE TITLE
File Not Found Error for Help Pages 

### ISSUE THREAD

**Issue by Jayonas** [cleidigh/printing-tools-ng#212]
Whenever Thunderbird tries to display a help page for this plugin it shows the "File not found" error page instead.  Here are a couple example URLs showing this error for me:

* moz-extension://d6cb72cf-22e7-443c-a1ec-412ec5f38778/chrome/content/help/locale/en-CA/printingtoolsng-help.html#customdate_format_help
* moz-extension://d6cb72cf-22e7-443c-a1ec-412ec5f38778/chrome/content/help/locale/en-CA/printingtoolsng-help.html#pdf_output_help

Additionally, whenever the plugin automatically updates and tries to show the "just installed/updated" page, that also shows the same error.

This started probably 1-2 months ago and I've been ignoring it because I wasn't super interested in the contents of the "just updated" page, plus I figured such a fundamental thing would probably be quickly reported and fixed.  But it hasn't been fixed yet (just updated again the other day) and I don't even see a report of it, so maybe I'm actually some strange corner case (en-CA locale, maybe?).  And now I'm interested in a few of the new settings but can't access their help.

Hopefully the URLs and error message are enough to give you somewhere to start.  I'm not sure what other information might be helpful.

**Comment by cleidigh** [comment]
@Jayonas 
I think my fallback logic that is supposed to use the en locale where the en-XX locale must not have moved when I updated things. Will check and report.
@cleidigh

**Comment by cleidigh** [comment]
@Jayonas 
Here is a beta fix for the help issue 
https://github.com/cleidigh/printing-tools-ng/blob/v2.2.3/xpi/Beta/printing-tools-ng-2.2.3-b1-tb.xpi
@cleidigh

**Comment by Jayonas** [comment]
I can confirm that your beta version resolves the problem, thanks for the quick fix!

**Comment by cleidigh** [comment]
@Jayonas 
Excellent, now I don't want to call your case an "edge condition", I think that would be disrespectful of canada %-)
It was my first issue with a locale that was en, but not en-US. The code was supposed to throw and default to en-US, but I had logic that didn't throw.
Anyway I am scrambling to get ImportExportTools NG updated for 115, a major task. Are you an IETNG user? If so would you be interested in helping out with user feedback and or testing? The first thing I would like is educated opinions on a revamp of the menu structures, they are old and awkward.
If you are not interested, no problem. ( I am inferring from your posts you are a developer)
cheers 
@cleidigh

**Comment by Jayonas** [comment]
@cleidigh

Haha, thanks. 😊 🇨🇦

You're correct that I'm a developer, though I haven't worked on Thunderbird and am also not an IETNG user so I'm afraid that I won't be much help there.  It looks like an impressive plugin though, and one that I'm glad to know about for potential use in the future.  Good luck with the major update!

**Comment by cleidigh** [comment]
@Jayonas 
No problem, if you are not using IETNG, no reason to drag you into that.
Glad you like the PDF auto save!
@cleidigh

**Comment by Jayonas** [comment]
I'm sorry to report that this issue resurfaced for me when I was updated to Supernova.  I'm getting a "file not found" page again -- at URL `moz-extension://d6cb72cf-22e7-443c-a1ec-412ec5f38778/chrome/content/help/locale/en-CA/printingtoolsng-help.html` -- when there's an update (which I now realize happens so often because of #233).  At the moment this is more of an inconvenience than a real problem, but I figured I should let you know.

Maybe or maybe not related, the Autosave to PDF feature also stopped working for me when I was updated to Supernova.  When I click the "Print NG" button I get the normal "OK to autosave or Cancel to preview" dialog, but when I click OK nothing happens, as best as I can tell; I no longer get a PDF file generated in the location specified in my settings (or anywhere else that I can find).  The workaround is just to go through the preview dialog like I used to before the Autosave feature existed (which I can do either by clicking Cancel or by turning off Autosave), so this is also effectively just an inconvenience.  If you think this is an unrelated problem then I can certainly make a new issue for it, but I thought I would mention it here first on the off chance that it's actually related to the locale thing (since they both started at the same time).

**Comment by cleidigh** [comment]
@Jayonas 
Good to hear from you.
I think I must have crossed the patch for en other locales when I started v115 support.
I verified the help failure, apologies that didn't get into v3.0.0

When I double checked the Auto save OK, that worked fine . I tested with en-US, en-CA and de locales.
So I am surprised as this has been out for a while and I am sure I would have heard about it.
You have a valid pdf output directory?
Can you do a test and check and capture the error console?
@cleidigh

**Comment by Jayonas** [comment]
@cleidigh 

Ah, glad to hear the locale thing is easy, just crossed branches.

I double-checked my PDF output directory, and it's the same valid place that it has always been, which is "H:".  To reduce complexity (since that's a network drive and what-not) I also tried changing it to "C:\Users\USERNAME\Documents".  In both cases I got these two messages in the console:

```
XPCWrappedNative_NoHelper { flags: Getter & Setter, folder: Getter, mime2DecodedSubject: Getter, subject: Getter & Setter, getStringProperty: getStringProperty(), isFlagged: Getter, messageKey: Getter & Setter, getUint32Property: getUint32Property(), messageSize: Getter & Setter, accountKey: Getter & Setter, … }
printingtoolsng-pengine.js:97:13
Uncaught (in promise) ReferenceError: messenger is not defined
    PrintSelectedMessages chrome://printingtoolsng/content/printingtoolsng-pengine.js:424
    cmd_printng chrome://printingtoolsng/content/printingtoolsng-pengine.js:652
    oncommand about:message:1
printingtoolsng-pengine.js:424:17
    cmd_printng chrome://printingtoolsng/content/printingtoolsng-pengine.js:661
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    oncommand about:message:1
```

Looks like a null reference error, basically?  Something about the Supernova upgrade caused `messenger` to be null for me but not for most anyone else, I guess.

Let me know if there's other info that would be helpful for me to provide and I'll see what I can do.  I'm unfortunately pretty far out of date on web-related stuff so I don't really know my way around these debugging facilities.  I don't see an easy way to export my PrintNG settings (which I haven't changed from before the upgrade when things worked), and I'm not sure what else might be helpful.

Also let me know if/when it's time to move this to its own issue and I can do that.

**Comment by cleidigh** [comment]
@Jayonas 
Have not forgotten about you!
Just took a break from IETNG and got things in order for ptng beta.
Besides the English sublocales, there are a couple generic help items I want to bring over from IETNG.
- only display help on ptng updates, not tb
- add pref to never show help 

Probably a couple days work.

Can you describe the exact steps to get the messenger error? Where were you, anything that can help me reproduce.
@cleidigh

**Comment by cleidigh** [comment]
@Jayonas 
FYI
I believe I found the messenger scope issue. It was reproduced if one was printing from a message window. Is that where you had the autosave issue?
I presume printing from the message list was not a problem?
Also have the help fixed.
@cleidigh

**Comment by Jayonas** [comment]
Okay I fiddled a little more and have some more info.  First, here are my settings, because I can't remember what all I changed from the defaults:

![Settings-Miscellaneous](https://github.com/cleidigh/printing-tools-ng/assets/37936740/28630a99-1cb0-4ec3-a2f5-d1914038e2af)
![Settings-Headers](https://github.com/cleidigh/printing-tools-ng/assets/37936740/20ab501a-01e4-4872-a941-4c0178a4137b)
![Settings-Body](https://github.com/cleidigh/printing-tools-ng/assets/37936740/7111cff0-c89b-46dc-b77c-20b633fec226)
![Settings-PDFOutput](https://github.com/cleidigh/printing-tools-ng/assets/37936740/284f367a-8d66-4ae3-b205-af716c6ecc3a)
![Settings-PrintAndPageOptions](https://github.com/cleidigh/printing-tools-ng/assets/37936740/54063835-f77f-4781-b01c-d67929e9df96)

Yes, you're correct that I'm printing while a message tab is active.  I have a Print NG button in both the main app toolbar for that view and the smaller toolbar to the right of the email headers.  They both effectively behave the same way for me, i.e. OK (on the AutoPDF dialog) doesn't do anything and Cancel goes through the preview process like normal.  However, the two buttons show different errors in the debug console when I click OK.  I also see an error in the debug console when I first open a message.  Lastly, I actually get the same bug/behavior if I print while viewing the message list.  Here are all of the messages/errors:

When I open a message (my test message for all of these was the notification email that GitHub sent about your reply to this thread, which is nothing complicated):
```
Missing resource in locale en-CA: messenger/openpgp/openpgp.ftl
XrayWrapper denied access to property "length" (reason: object is not safely Xrayable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. index.js:4426:16
TypeError: displayedMessage is null background.js:657:19
```
When I click Print NG from the message window header tool bar ...
```
XPCWrappedNative_NoHelper { flags: Getter & Setter, folder: Getter, mime2DecodedSubject: Getter, subject: Getter & Setter, getStringProperty: getStringProperty(), isFlagged: Getter, recipients: Getter & Setter, ccList: Getter & Setter, messageSize: Getter & Setter, messageKey: Getter & Setter, … }
printingtoolsng-pengine.js:97:13
```
... and then click OK in the AutoPDF dialog:
```
Uncaught (in promise) ReferenceError: messenger is not defined
    PrintSelectedMessages chrome://printingtoolsng/content/printingtoolsng-pengine.js:424
    cmd_printng chrome://printingtoolsng/content/printingtoolsng-pengine.js:652
    oncommand about:message:1
printingtoolsng-pengine.js:424:17
```
When I click Print NG from the main app tool bar while viewing an individual message ...
```
Uncaught TypeError: event.target.attributes.is is undefined
    init chrome://confirmbeforedelete/content/confirmbeforedelete/CBD-common.js:81
CBD-common.js:81:17
XPCWrappedNative_NoHelper { flags: Getter & Setter, folder: Getter, mime2DecodedSubject: Getter, subject: Getter & Setter, getStringProperty: getStringProperty(), isFlagged: Getter, recipients: Getter & Setter, ccList: Getter & Setter, messageSize: Getter & Setter, messageKey: Getter & Setter, … }
printingtoolsng-pengine.js:97:13
```
... and then click OK in the AutoPDF dialog:
```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. 2 test.html
TypeError: browser is null BrowserElementParent.sys.mjs:21:21
```
When I click Print NG from the main app toolbar while viewing the message list ...
```
Uncaught TypeError: event.target.attributes.is is undefined
    init chrome://confirmbeforedelete/content/confirmbeforedelete/CBD-common.js:81
CBD-common.js:81:17
XPCWrappedNative_NoHelper { flags: Getter & Setter, folder: Getter, mime2DecodedSubject: Getter, subject: Getter & Setter, getStringProperty: getStringProperty(), isFlagged: Getter, recipients: Getter & Setter, ccList: Getter & Setter, messageSize: Getter & Setter, messageKey: Getter & Setter, … }
printingtoolsng-pengine.js:97:13
```
... and then click OK in the AutoPDF dialog:
```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. 2 test.html
TypeError: browser is null BrowserElementParent.sys.mjs:21:21
```
I did not look super close, but I think it's the same set of messages from the main app toolbar button whether I'm viewing an individual message or the whole message list.

When I use CTRL+P, either from a message tab or from the message list ...
```
XPCWrappedNative_NoHelper { flags: Getter & Setter, folder: Getter, mime2DecodedSubject: Getter, subject: Getter & Setter, getStringProperty: getStringProperty(), isFlagged: Getter, recipients: Getter & Setter, ccList: Getter & Setter, messageSize: Getter & Setter, messageKey: Getter & Setter, … }
printingtoolsng-pengine.js:97:13
```
... and then click OK in the AutoPDF dialog:
```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. 2 test.html
TypeError: browser is null BrowserElementParent.sys.mjs:21:21
```
That's very similar to the main app toolbar button, but without the `event.target.attributes.is is undefined` error.

I hope that's helpful, and I'm glad to hear that you could repro the messenger error!

**Comment by Jayonas** [comment]
Oh wait, I'm also an idiot!  I'm not accustomed to checking that Documents folder because, like I said earlier, I usually have it set somewhere else, so I was watching the wrong folder while messing around just now.  Turns out that both the main app toolbar button and CTRL+P actually work correctly and create a PDF, whether I'm viewing the message list or an individual message.  So in the end, yeah, the only broken thing is actually the button by the headers in the message view.  Sorry for the incorrect report about the other ones; maybe I'll just delete that whole comment, assuming I can do that.

**Comment by cleidigh** [comment]
@Jayonas 
Well everything makes sense except the OK not working in the message list, that I can't reproduce nor does it make sense.
As soon as I push b2, probably tomorrow, we will see where we are.
@cleidigh

**Comment by cleidigh** [comment]
@Jayonas 
Last messages crossed, I think we are now in agreement, good.
I think b2 will hit everything.
@cleidigh

**Comment by cleidigh** [comment]
@Jayonas 
Posted b2
It has the help and message window fixes.
@cleidigh

**Comment by Jayonas** [comment]
@cleidigh Confirmed that b2 fixes both the help and the message window button for me.  Thanks!
