### ISSUE TITLE
How to enforce wrapping of contained URLs - Limit page width

### ISSUE THREAD

**Issue by pstein** [cleidigh/printing-tools-ng#213]
Printing Tools NG works in general (with PTNG specified font size & font).

However sometimes a message contains a loooooooooong URL

When I print such a msg (with "fit to width" option enabled) then the text becomes almost unreadable tiny since PTNG cannot automatically wrap the URL into the next line.
Or did I miss something?

Can this wrap feature be implemented?

BTW: in PTNG----"Body" tab there is an option "Maximum width for text".
Whats the unit for this option?
- number of chars?
- millimeter?
- inches?
- pixels?

What if the width of  text goes beyond that threshold?

**Comment by cleidigh** [comment]
@pstein 
Both @kiki-ja and I have done a couple of what we believe are representative examples of messages with long URLs. Without any changes to options the URLs wrap with no font changes or anything.
Here is an image example : 

![Test Message for normal](https://user-images.githubusercontent.com/25272315/235745735-f5910387-651b-424a-a364-865f06fc451a.png)

The max width setting is in characters, however, it only restricts p elements in messages.
@cleidigh

**Comment by pstein** [comment]
Ok, thank you.

The problem here was, that I specified in all tested pdf printer drivers (=NOT in PTNG) the option "Fit to page width".

As soon as I switch to "Scale 100" the overlong URLs are wrapped as desired. See attached snapshot

puuh,.... many side effects users have to consider

![Scale 100](https://user-images.githubusercontent.com/2775875/236185754-2e8fd9ea-2c4d-459c-9622-2936eb8a8d82.png)

**Comment by cleidigh** [comment]
@pstein 
You are correct, there are many interactions. One big uncontrolled thing is the huge variety of printer drivers.
We can really only address some types of issues as they come up, impossible to know everything.
Can I close?
@cleidigh

**Comment by pstein** [comment]
Yes, thank you. Close
