### ISSUE TITLE
[Feature Request] Option to NOT split graphics

### ISSUE THREAD

**Issue by rgrun1** [cleidigh/printing-tools-ng#216]
I would like to see an option to keep all graphics in one piece i.e NOT spitting them onto different pages
Sometime PT does a great job of this but then there are those other times
Just detect if it will be split and then either bump to the next page and if too big still, then "fit to page"
Then it is easy to load it into Acrobat/Nitro etc. and sabe out the graphics
NOT for all the time hence pleas make it an OPTION
Thanks

**Comment by cleidigh** [comment]
@rgrun1 
Unfortunately I don't think that there is any way I can do this in the extension. I believe only the pdf driver can really do th. I have only the html and no visibility to the rendering and therefore not the pagination either.
Sorry, but there are some things that extensions cannot do.
@cleidigh
