### ISSUE TITLE
2.2.2 Not printing to a pdf from the preview menu

### ISSUE THREAD

**Issue by rgrun1** [cleidigh/printing-tools-ng#217]
I used to be able to use print preview then print to the Nitro Printer the windows print dialog. 
I can no longer do that. It acts like it is doing something but the PDF is not there. If I automatically generate a PDF, it works but via the print preview module it does not
Thanks

**Comment by cleidigh** [comment]
@rgrun1 
Can you give me some details. First what versions of TB, os and ptng.
I am not clear what you mean by the windows dialog. If you are in the preview you can select any printer from there and click print. Can you explain what is different?
@cleidigh
