### ISSUE TITLE
[Report] PTNG 3.0.0 Supernova support

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#218]
PTNG 3.0.0b3
Thunderbird 114.0b5, 115.0a1 (20230509build) 64bit
Windows 10 Pro 22H2 64bit

I have not tried all the features but normal printing is fine.
Ctrl+P, Print Preview, and toolbar icons also work fine.

I expect it to work the same way as v2.2.2 and v2.2.3b1 in the future.
e.g. scale, margins, headers & footers, Option UI Layout, etc.

![114-115 Print Sample](https://github.com/cleidigh/printing-tools-ng/assets/80428201/4c8a4997-591c-452a-bbe8-fc9368427e34)

**Comment by kiki-ja** [comment]
About Option UI.

Supernova (Thunderbird 115.0, 114.0beta) ptng-options.xhtml no longer uses the spacer tag.
As a result, the layout of the Option UI is partially broken.
They should be replaced by padding or margin.

Hopefully this will be fixed in the future as well as v2.2.2 and v2.2.3b1.

![PTNG-3 0 0b3-TAB1](https://github.com/cleidigh/printing-tools-ng/assets/80428201/330c4888-76ed-46c3-87c4-9a63af20dee1)

![PTNG-3 0 0b3-TAB2](https://github.com/cleidigh/printing-tools-ng/assets/80428201/64f26320-3ee0-4966-ad26-8b550d706ce2)

![PTNG-3 0 0b3-TAB3](https://github.com/cleidigh/printing-tools-ng/assets/80428201/150c7c9c-dbff-4c4f-a371-8929835b0614)

![PTNG-3 0 0b3-TAB4](https://github.com/cleidigh/printing-tools-ng/assets/80428201/c1593974-9259-485c-9c3a-fba65abc5945)

![PTNG-3 0 0b3-TAB5](https://github.com/cleidigh/printing-tools-ng/assets/80428201/36fa97da-7df3-4a33-a4c6-5913a84049bb)

**Comment by cleidigh** [comment]
@kiki-ja 
@tidebre67
Yes I will have to replace spacers as I did with IETNG 
I also just figured out why the settings were not sent to preview (page ranges etc.)
It is actually a time zero scenario when the print_printer is not set.
I will do that patch and put out a beta.
Thaks all
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

PTNG 3.0.0b6
Thunderbird 115.0b4
Windows 10 Pro 22H2

Scale, Page Ranges, Margins, Headers & Footers seem to be working fine.

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

PTNG 3.0.0b6
Thunderbird 91.13.1, 102.12.0, 115.0b4
Windows 10 Pro 22H2

1. I cannot close the options dialog with the OK button.
Thunderbird 91.0, 102.0 only.

2. The grayed out wrench button remains in the addons manager.
Thunderbird 115.0b4 only.

![wrench icon-3](https://github.com/cleidigh/printing-tools-ng/assets/80428201/05df29a9-960a-4c74-8036-77b56ff5a7c4)

@kiki-ja

**Comment by cleidigh** [comment]
Hi Kiki
When you cannot close it usually means there is an error on options starts.
Can you check the console?
The wrench will be fixed when I update a TB api.
Christopher

**Comment by kiki-ja** [comment]
@cleidigh

>Can you check the console?

Console logs are attached.
Thunderbird 91.13.1 and 102.12.0 were identical.
```
16:29:31.676 Uncaught TypeError: PSSVC.maybeSaveLastUsedPrinterNameToPrefs is not a function
    savePrintSettings chrome://printingtoolsng/content/printerSettings.js:465
    savePMDprefs chrome://printingtoolsng/content/ptng-options.js:451
    oncommand chrome://printingtoolsng/content/ptng-options.xhtml:1
printerSettings.js:465:11
    savePrintSettings chrome://printingtoolsng/content/printerSettings.js:465
    savePMDprefs chrome://printingtoolsng/content/ptng-options.js:451
    oncommand chrome://printingtoolsng/content/ptng-options.xhtml:1
```
```
16:29:31.676 Uncaught TypeError: PSSVC.maybeSaveLastUsedPrinterNameToPrefs is not a function
    savePrintSettings chrome://printingtoolsng/content/printerSettings.js:465
    savePMDprefs chrome://printingtoolsng/content/ptng-options.js:451
    oncommand chrome://printingtoolsng/content/ptng-options.xhtml:1
printerSettings.js:465:11
    savePrintSettings chrome://printingtoolsng/content/printerSettings.js:465
    savePMDprefs chrome://printingtoolsng/content/ptng-options.js:451
    oncommand chrome://printingtoolsng/content/ptng-options.xhtml:1
```
[91-console-export-2023-6-27_16-30-3.txt](https://github.com/cleidigh/printing-tools-ng/files/11881282/91-console-export-2023-6-27_16-30-3.txt)
[102-console-export-2023-6-27_16-40-17.txt](https://github.com/cleidigh/printing-tools-ng/files/11881283/102-console-export-2023-6-27_16-40-17.txt)

>The wrench will be fixed when I update a TB api.

Understood.
Expect to be updated.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
I have to change the compatible TB versions.
Unfortunately v3+ will have to be for 115+ only.
The wrench issue is one example and there will be more incompatibility going forward.
I was hoping I could still support 102 also.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

> I have to change the compatible TB versions.
> Unfortunately v3+ will have to be for 115+ only.

I agree.

> The wrench issue is one example and there will be more incompatibility going forward.

I too feel that in the future there will be more incompatibilities.

> I was hoping I could still support 102 also.

Unfortunately, it would be better to regard it as a separate product from 102.

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

PTNG 3.0.0b7
Thunderebird 115.0 64bit
Windows 10 Pro 22H2 64bit

1. Wrench button has been improved to display correctly.
![PTNG-3 0 0b7-wrenchicon](https://github.com/cleidigh/printing-tools-ng/assets/80428201/f2ce457a-8876-4a38-bb6a-42ebf3287845)

2. Print preview and printing of News and RSS feed messages does not work.

@kiki-ja

**Comment by kiki-ja** [comment]
PTNG 3.0.0b8
Thunderbird 115.0 64bit
Windows 10 Pro 22H2 64bit

**About the icon buttons**

I think it is better to have icon buttons everywhere.
The reason is that Thunderbird 115.0 allows standard icon buttons to be placed in various places, but add-on icon buttons cannot be placed unless the add-on side supports them.

I especially have trouble accessing the add-on options.
It forces me to open the add-on manager in a tab(1), select the desired add-on(3), and click the wrench button(3) every time.(3 actions)
This is a pain for me.

Reference:
Our Fastest, Most Beautiful Release Ever: Thunderbird 115 "Supernova" Is Here!
https://blog.thunderbird.net/2023/07/our-fastest-most-beautiful-release-ever-thunderbird-115-supernova-is-here/

@kiki-ja

**Comment by kiki-ja** [comment]
PTNG 3.0.0b9,10
Thunderbird 115.0.1 64bit
Windows 10 Pro 22H2 64bit

Unable to print selected messages.
https://github.com/cleidigh/printing-tools-ng/issues/219#issuecomment-1645503280

@kiki-ja

**Comment by kiki-ja** [comment]
PTNG 3.0.0b11
Thunderbird 115.0.1 64bit
Windows 10 Pro 22H2 64bit

>Unable to print selected messages.

I have confirmed that it works correctly.
Thank you very much.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Thanks, sounds good.
Closing to track in 
- #229 
@cleidigh
