### ISSUE TITLE
v3.0.0-Exp for v115 Initial testing 

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#219]
@tidebre67 
@kiki-ja 
I just posted a a quick fix that should address the options passed to preview, ranges etc.
This was a T0 issue where either a printer had not been set or there was not yet a ptng_options set.

I was still seeing odd errors opening options, but only on one computer.
It will be interesting to see what you guys find.
If this works we should be down to detail testing.

https://github.com/cleidigh/printing-tools-ng/blob/TB-115-exps/xpi/Beta/printing-tools-ng-3.0.0-b4-tb.xpi

@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
installed b4
regret, see no change .
print settings are not transferred to print preview and same 
the other way round. tested some of my installed printers.

**Comment by cleidigh** [comment]
@tidebre67 
Well that is unexpected... Anything in the error console?
Sounds like I need debug info, it was a pretty obvious tweak, but I must have targeted the wrong problem.
Thanks for the quick test.
I think I will try the quick dbg and post tonight.
@cleidigh

**Comment by cleidigh** [comment]
@tidebre67 
@kiki-ja 
Well I just discovered they have made changes to how print settings are handled. We don't seem to be saving them. Headers and footers are no longer saved per printer rather only globally.
I also have the 115 branch from earlier than I thought so I have to merge in 2.0.3+ stuff and get up to date.
@cleidigh

**Comment by cleidigh** [comment]
@tidebre67 
@kiki-ja 
ok found the root cause...Me
Stupid new api call.
https://github.com/cleidigh/printing-tools-ng/blob/TB-115-exps/xpi/Beta/printing-tools-ng-3.0.0-b6-tb.xpi

@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
Christopher, will test tomorrow, reverting.

@tidebre67

**Comment by tidebre67** [comment]
@cleidigh 
tested some of my printers. all looks fine now, 
could not find any problem.
Excellent, Tks for that.

**Comment by kiki-ja** [comment]
@cleidigh

PTNG 3.0.0b6
Thunderbird 115.0b4
Windows 10 Pro 22H2

Scale, Page Ranges, Margins, Headers & Footers seem to be working fine.

@kiki-ja

**Comment by cleidigh** [comment]
@tidebre67 
@kiki-ja 
Thanks guys, on potential issue down. It's looking pretty good so far.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

PTNG 3.0.0b6
Thunderbird 91.13.1, 102.12.0, 115.0b4
Windows 10 Pro 22H2

1. I cannot close the options dialog with the OK button.
Thunderbird 91.0, 102.0 only.

2. The grayed out wrench button remains in the addons manager.
Thunderbird 115.0b4 only.

![wrench icon-3](https://github.com/cleidigh/printing-tools-ng/assets/80428201/05df29a9-960a-4c74-8036-77b56ff5a7c4)

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

PTNG 3.0.0b7
Thunderebird 115.0 64bit
Windows 10 Pro 22H2 64bit

1. Wrench button has been improved to display correctly.
![PTNG-3 0 0b7-wrenchicon](https://github.com/cleidigh/printing-tools-ng/assets/80428201/f2ce457a-8876-4a38-bb6a-42ebf3287845)

2. Print preview and printing of News and RSS feed messages does not work.

@kiki-ja

**Comment by tidebre67** [comment]
@cleidigh ,
for your information:
![ptng](https://github.com/cleidigh/printing-tools-ng/assets/44371934/71949f1f-f853-405d-82bd-fdde510b7080)

had to be changed to Print NG, like in the new uni toolbar.

**Comment by cleidigh** [comment]
@tidebre67 
Which menu are you showing in your post?
@kiki-ja 
I want to get b8 out with some of these items attacked. I just got a couple more modes working, tabs and separate windows.
@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
main window /menu is concerned, trust below print out shows what i mean:
![ptng for 115](https://github.com/cleidigh/printing-tools-ng/assets/44371934/76f9fd6d-de33-4f59-afce-5cce47e8ad78)

**Comment by kiki-ja** [comment]
PTNG 3.0.0b7
Thunderbird 115.0 64bit
Windows 10 Pro 22H2 64bit

@cleidigh
@tidebre67

What is your version of PTNG 3.0.0 Beta?
What is the version of Thunderbird 115.0?
What is your operating system and its version?

[Message Pane] -> [Message Header Toolbar] -> [More actions button] -> [Print...] is Thunderbird's normal print menu.
This is because PTNG 3.0.0b7 does not integrate (Ctrl + P) with Thunderbird's [Print...].

PTNG 3.0.0b7 icon buttons include [Print] [Print preview] [Options] [Help].

![message header toolbar](https://github.com/cleidigh/printing-tools-ng/assets/80428201/819fd06c-ae50-4a0f-94d1-4ebf982d245a)

It is a mystery why there is no PTNG icon button on the message header toolbar.

@cleidigh 
>I want to get b8 out with some of these items attacked. I just got a couple more modes working, tabs and separate windows.

Yes, I understand.
I will test and report back.

@kiki-ja

**Comment by tidebre67** [comment]
@cleidigh 
PTNG 3.0.0b7
Thunderbird 115.0 64bit
Windows 10 Home 22H2 64bit

**Comment by cleidigh** [comment]
@tidebre67 
@kiki-ja 
I think I understand what happened.
The message header icon was only recently fixed. I put up an incomplete b7 at some point so I think that caused confusion.
B8 will have several ui interface points fixed including the message context menu and the message header icon. I am not sure about the message header drop down menu. It may not be simple. If we have the icon do we need it?
@cleidigh

**Comment by cleidigh** [comment]
@tidebre67 
@kiki-ja 
b8 is posted.
I added the following 
- persistent printer code, ui and translations 
- print from main window with message pane hidden or shown
- fixed button in message hdr toolbar
- print from message in tab or separate window 
- added message context menu, tools and message pane right click 
- ui tweaks 
- note I have seen issues with the settings getting transferred to preview, watch out for that

I am still juggling with ietng so apologize if I am all over the place.

@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
short and quick test with my local printer and pdf24, b8 works great.
could not find issues with the settings transferred to preview.
@kiki-ja , do you see any problems in this respect ?

drop down menu in message header, for me not that important for others may be.
help and settings are working in this drop down menu, preview and print not.

Christopher, understand that you have a lot to solve in ptng and ietng to get both working in tb115.
Therefore thanks for your hard work .

**Comment by kiki-ja** [comment]
**To ALL
Describe the test environment appropriately.
The reason for this is that it can vary depending on the environment.**

PTNG 3.0.0b8
Thunderbird 115.0 64bit
Windows 10 Pro 22H2 64bit

@tidebre67

>@kiki-ja , do you see any problems in this respect ?

I have not tested all the features, but I had the following problems:
1. Print preview and print of locally stored eml message files was possible in b7, but not in b8.
2. Printing by PTNG 3.0.0b8 when directly opening an eml message file attached to a forwarded message is not yet supported.
3. Printing of News and RSS in PTNG 3.0.0b8 is not yet supported.

@cleidigh

>b8 is posted.
>I added the following
>
>   - persistent printer code, ui and translations
>   - print from main window with message pane hidden or shown
>   - fixed button in message hdr toolbar
>   - print from message in tab or separate window
>   - added message context menu, tools and message pane right click
>   - ui tweaks

I have checked the above content.
The context menu is good.
I would like to correct the translation of "persistent" (Should be the same as v2.2.3)
I will continue to test.

@kiki-ja

**Comment by cleidigh** [comment]
@tidebre67 
Can you clarify your comment on the message header drop down menu : 
I fixed the button, however, I have no items added to the "More" dropdown.
Which menu are you referring to that does not work for print and preview?
The button dropdown works for me.

@kiki-ja 
I also need clarification on a couple of your items : 
1. When you say locally stored eml file, do you mean double clicking on an eml file in explorer? This is not possible for a while since TB opens a limited message window with no extensions running. Since this didn't change from b7 to b8 I think you mean something different?
2.  I have to look into this, I may need exact way to reproduce, did this work in the past?
3. I think we had to do tweaks in the past for this, so I will look back 

My goal will be for b9 to be feature compatible with v2.2.3

I will update the persistent translation.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
I am going to need some help on the RSS feed issue.
The original issue you posted 
https://github.com/cleidigh/printing-tools-ng/issues/121
had a feed link that does not get recognized as valid.
if i change it to end in commits.atom I get recent commits.

Each looks like a message with the commit message. Printing with TB print or preview just shows the message not the GH page.
There is a web link in the header, but this opens a browser.
I need to understand a setup and what fails, I cannot reproduce.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
I cannot send an email with an eml attachment to myself so I don't know how I can test this.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
@tidebre67 
I posted b9 early because I think I have both eml and eml attachments working.
I now think I understand opening an eml from the file menu was what you @kiki-ja were referring to.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>1. When you say locally stored eml file, do you mean double clicking on an eml file in explorer?

No, in my case it is the way to open the message file from the Thunderbird menu.
The reason for this is that I have many Thunderbird versions (9 versions) installed and I cannot associate an eml file with a particular Thunderbird in Explorer and open it with a double click.


>My goal will be for b9 to be feature compatible with v2.2.3

I too feel it is a good idea.


>I am going to need some help on the RSS feed issue.
>The original issue you posted
>#121
>had a feed link that does not get recognized as valid.
>if i change it to end in commits.atom I get recent commits.

I think the RSS feed issue should be addressed in #121.
What do you think?

Sorry, How about Thunderbird Blog as a test RSS feed?
I think this can be shared with anyone.

The Thunderbird Blog
https://blog.thunderbird.net/

The Thunderbird Blog - RSS feed
https://blog.thunderbird.net/feed/


>I cannot send an email with an eml attachment to myself so I don't know how I can test this.

I am forwarding a sample message to myself for testing purposes, specifying the attachment style.
If you need it, I can attach it here or email it to you.

I will report on b9 later.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
I have the commits feed working.
What I see is printing these RSS messages with native TB print or ptng prints the same, just the commit comment.
What do you think should be different?
@cleidigh

**Comment by tidebre67** [comment]
> @tidebre67 Can you clarify your comment on the message header drop down menu : I fixed the button, however, I have no items added to the "More" dropdown. Which menu are you referring to that does not work for print and preview? The button dropdown works for me.

@cleidigh 
hope this will clarify
![message header-1](https://github.com/cleidigh/printing-tools-ng/assets/44371934/535c33e0-1e36-4829-96f5-8d798a749551)

**Comment by cleidigh** [comment]
@tidebre67 
Ok so we are talking about the message hdr button dropdown.
I have no problem so this is odd. Can you put trace1 in debug options and check the console?
Also does the main toolbar button work?
@cleidigh

**Comment by kiki-ja** [comment]
PTNG 3.0.0b9
Thunderbird 115.0 64bit
Windows 10 Pro 22H2 64bit

@cleidigh

>I posted b9 early because I think I have both eml and eml attachments working.

Yes, the original eml message file attached to the forwarded message can now be opened directly or once saved locally and opened for print preview and printing.(Green border of screenshot)
Good!

On the other hand, there were some parts that did not work.(Red border of screenshot)
1. Menu [File] --> [Print...(NG)] did not work.
2. [Print] and [Print Preview] did not work with the PTNG icon button on the message window toolbar.

![eml message window b9](https://github.com/cleidigh/printing-tools-ng/assets/80428201/11e69168-5eaa-4ff0-868b-fb04cbe64629)

In addition, [Print] and [Print Preview] did not work from the PTNG icon button on the toolbar when a normal message was opened in a window.

>I now think I understand opening an eml from the file menu was what you @kiki-ja were referring to.

Yes, that's right.

@kiki-ja

**Comment by kiki-ja** [comment]
PTNG 3.0.0b9
Thunderbird 115.0 64bit
Windows 10 Pro 22H2 64bit

@cleidigh

>What I see is printing these RSS messages with native TB print or ptng prints the same, just the commit comment.

In my case, printing and print preview did not work in PTNG.


>What do you think should be different?

I cannot tell the difference.

@kiki-ja

**Comment by cleidigh** [comment]
@tidebre67 
You need to use 
trace1
no capitalization.
@cleidigh

**Comment by kiki-ja** [comment]
PTNG 3.0.0b9
Thunderbird 115.0 64bit
Windows 10 Pro 22H2 64bit

@cleidigh

"trace1" was added to the debug option to get the error console logs.
I am attaching that text file.

[console-message-window-file-Print(NG)-2023-7-19.txt](https://github.com/cleidigh/printing-tools-ng/files/12083386/console-message-window-file-Print.NG.-2023-7-19.txt)
[console-message-window-toolbar-PTNGbutton-2023-7-19.txt](https://github.com/cleidigh/printing-tools-ng/files/12083387/console-message-window-toolbar-PTNGbutton-2023-7-19.txt)
[console-fwd-message-attachment-eml-open-toolbar-button-2023-7-19.txt](https://github.com/cleidigh/printing-tools-ng/files/12083388/console-fwd-message-attachment-eml-open-toolbar-button-2023-7-19.txt)
[console-locale-eml-open-toolbar-button-2023-7-19.txt](https://github.com/cleidigh/printing-tools-ng/files/12083389/console-locale-eml-open-toolbar-button-2023-7-19.txt)
[console-locale-eml-open-header-button-2023-7-19.txt](https://github.com/cleidigh/printing-tools-ng/files/12083390/console-locale-eml-open-header-button-2023-7-19.txt)








@kiki-ja

**Comment by cleidigh** [comment]
@tidebre67 
Perfect, I see the error, but I need absolute clarity on the view and layout.
Is it main window, tab, separate window, anything you can describe.
What is weird is it looks like the opposite button problem @kiki-ja has.

A side issue : Are you using the en-GB locale? I had an issue with help and sub locales.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
Great I will look at the logs.
In your screenshot above can you describe what window this is? I don't see the unified toolbar button and I don't see the search in the title bar.
@cleidigh

**Comment by tidebre67** [comment]
>  Perfect, I see the error, but I need absolute clarity on the view and layout. Is it main window, tab, separate window, anything you can describe. What is weird is it looks like the opposite button problem @kiki-ja has.
> 
> A side issue : Are you using the en-GB locale? I had an issue with help and sub locales. @cleidigh

@cleidigh 
no using DE.
open messages in new window
let me know if more details necessary.

**Comment by cleidigh** [comment]
@tidebre67 
@kiki-ja 
I think I have to come up with a list of invocation methods and views so we can all describe things with the same language.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

The screenshot I attached is a **window** of a local eml file opened from the file menu.
It is **not opened in a tab**.
Please see screenshots.

![Message Window Toolbar](https://github.com/cleidigh/printing-tools-ng/assets/80428201/1955e1da-c817-4532-a622-71231d22b870)

When opened in a **tab**, all PTNG icon buttons work correctly.

I am also testing with Thunderbird 115.0 en-US version. And of course the ja version.
The console log is also from the en-US version.

Reference:
The new view names for Thunderbird 115 Supernova can be found on the blog.

Getting Started With The Main Window Of Thunderbird 115
https://blog.thunderbird.net/2023/07/getting-started-with-the-main-window-of-thunderbird-115-supernova/

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Ok I now understand the description, but how did you open an eml file to a new window? I always get the message in a tab.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
Ahhh, found it in settings 
Open message in new window.
Just one more method to track
Now I can compare results.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
@tidebre67 
So I now understand that @kiki-ja is opening an eml message with the open in new window setting set.
I can reproduce his issues, I understand them, but still need a fix.
@tidebre67  Your issue is I think similar, but I think I still am not doing exactly what you are doing.
can you think of any more information on how and where you are printing?
@cleidigh

**Comment by kiki-ja** [comment]
The view name in the previous screenshot was incorrect.
The correct name is "Message Header Toolbar", not "Message Headerbar".

@cleidigh

>but how did you open an eml file to a new window?.

I set it to Window when I open individual messages.
You can select this option by going to Thunderbird's [Setting] --> [General] --> [Reading & Display] --> [Open messages in:].
This is a setting that has existed since older versions of Thunderbird.

When opening a message from [Menu] --> [File] --> [Open], or when selecting a message in the thread pane and double-clicking to open it, this setting is followed.

![Setting-General-Reading and Display-Open messages in](https://github.com/cleidigh/printing-tools-ng/assets/80428201/6ce410fe-b5b6-466f-9262-404b4ade9927)

On the other hand, from the right-click context menu of a message selected in the thread pane, it can be opened in any of the three ways.
This method allows you to open the message regardless of the [Setting] designation.

![open message select](https://github.com/cleidigh/printing-tools-ng/assets/80428201/dfdb6b2e-1adb-4060-a1c6-804794df3d70)

@kiki-ja

**Comment by tidebre67** [comment]
@tidebre67 Your issue is I think similar, but I think I still am not doing exactly what you are doing. can you think of any more information on how and where you are printing? @cleidigh

@cleidigh 
indeed, i presume too that the issues mentioned by kiki-ja are more less same i reported. 
i propose that you -if possible- fix these issues and i will see whether my mentioned issues solved too.

**Comment by kiki-ja** [comment]
@cleidigh

>I can now reproduce your results.
>I can reproduce his issues, I understand them, but still need a fix.

Thanks, so much.
I am sorry for my poor explanation.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
No problem, I am often giving bad descriptions.

@kiki-ja 
@tidebre67 
b10 has a lot of rework that effects how all the buttons, menus work.
Definitely needs thorough testing.
Will follow up on that. 
want to make a todo list.
@cleidigh

**Comment by tidebre67** [comment]
> @cleidigh indeed, i presume too that the issues mentioned by kiki-ja are more less same i reported. i propose that you -if possible- fix these issues and i will see whether my mentioned issues solved too.

@cleidigh 
it looks that my mentioned issues solved with b10.
great/tks

**Comment by kiki-ja** [comment]
PTNG 3.0.0b10
Thunderbird 115.0.1 64bit
Windows 10 Pro 22H2 64bit

@cleidigh

>b10 has a lot of rework that effects how all the buttons, menus work.

I have verified that print preview and print work correctly from all menus and PTNG icon buttons when opening normal messages, forwarded message attachment eml file, and local eml file in a tab or window.
Thank you for your hard work.

>Definitely needs thorough testing.

I hope that many users will help us test it.

I have installed it in a separate folder from my regular Thunderbird 91.0 and 102.0 and have tested it with separate profiles.
However, the message data is common.

@kiki-ja

**Comment by kiki-ja** [comment]
PTNG 3.0.0b9,10
Thunderbird 115.0.1 64bit
Windows 10 Pro 22H2 64bit

@cleidigh

Unable to print selected messages.

This function worked automatically in PTNG 2.2.3, but not in 3.0.0b9,10.
It would be great if it would work the same way as in PTNG 2.2.3.

In addition, the current Thuderbird 115 normal printing also requires manual switching between "Original" and "Selection" in Format.

![orignal format](https://github.com/cleidigh/printing-tools-ng/assets/80428201/ca60c131-04a0-4b6a-9afb-bcac43e31fc9)
![selection fomat](https://github.com/cleidigh/printing-tools-ng/assets/80428201/a37b8214-b69c-4c9a-9131-9041c61d73c7)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
If I understand your comments on printing selections, it is one issue, not two.
Printing selections works, however, unlike v2.2.3 you have to select to print selections in the preview.

This is known to me, it is due to fixing one issue and creating this one.
It's on my list to hopefully restore the behavior.

Your other results sound really good and it looks like @tidebre67 your issue resolved as well, that's great!
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
@tidebre67 
Alright I had a bit of a struggle with some issues with separate windows and selections, but I think I just got over the last hurdles.
Selection printing now should work everywhere and selection mode chosen in preview.
Still have to make a todo list, but next up is the keyboard shortcut Control P override.
I can't think of anything else not working.
b11 posted.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
@tidebre67 
I am going to close this and make a final testing issue for our last stuff.
@cleidigh

**Comment by kiki-ja** [comment]
PTNG 3.0.0b11
Thunderbird 115.0.1 64bit
Windows 10 Pro 22H2 64bit

>Selection printing now should work everywhere and selection mode chosen in preview.

I have confirmed that it works correctly.
Thank you very much.

>Still have to make a todo list, but next up is the keyboard shortcut Control P override.

I think it would be easier to understand if there was a todo list.
And if it can be integrated into Ctrl + P, I think this Issue #219 should be closed.

@kiki-ja

**Comment by tidebre67** [comment]
> @kiki-ja @tidebre67 Alright I had a bit of a struggle with some issues with separate windows and selections, but I think I just got over the last hurdles. Selection printing now should work everywhere and selection mode chosen in preview. Still have to make a todo list, but next up is the keyboard shortcut Control P override. I can't think of anything else not working. b11 posted. @cleidigh

@cleidigh 
Christopher, i tested all i use in PTNG and all looks fine, selection as well. Great work. Thks.
Yes, shortcut control P still outstnding.

**Comment by cleidigh** [comment]
@kiki-ja 
@tidebre67 
Thanks both.
After a false alarm it looks like selections are working for all.
I added the the todo list to 
- #225 
- b12 will have shortcuts working, already done

I am going to create a final testing issue and close old ones so we track in one place 
@cleidigh

**Comment by cleidigh** [comment]
Closing to track in 
- #229
