### ISSUE TITLE
Order/Hide of the message header BCC is ignored

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#22]
The order or hide/show-option of the message header BCC is ignored.
BCC is always printed as the last row.

![PrintingTool](https://user-images.githubusercontent.com/77779094/105354102-6170e780-5bf0-11eb-8466-a1837ead335a.PNG)

Printer preview/output:
![PrintingToolAusgabe](https://user-images.githubusercontent.com/77779094/105354375-c2002480-5bf0-11eb-920b-3b187dbd7043.PNG)

**Comment by cleidigh** [comment]
@RRoenn 
thanks for the post, happy New Year's!
I did some checks and I can verify the behavior you see.  I think I have determined it is a localization related issue.  English Swedish and Spanish all appear to work correctly
whereas German ignores the order/display state
I am working towards a maintenance  release shortly, I have put this on the list.
Christopher

**Comment by cleidigh** [comment]
@RRoenn 
that's what it was..
check out
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.1/xpi/printing-tools-ng-2.0.1-b2-tb.xpi
Christopher

**Comment by RRoenn** [comment]
Thank you for your quick reply. Now it works like a charm.

I am very happy that you bring this extension back to live. I just found it a few days ago.
