### ISSUE TITLE
@madvinegar Kalispera, hope you are keeping cool! Can't remember where you are, but my wife just got back from Crete and Athens, very hot...

### ISSUE THREAD

**Issue by Mark3032** [cleidigh/printing-tools-ng#227]
@madvinegar Kalispera, hope you are keeping cool! Can't remember where you are, but my wife just got back from Crete and Athens, very hot...

@madvinegar 
@Mark3032 
Thanks for the quick and detailed feedback and testing. I have to take a bit to consume and understand everything.
The pagination issues are particularly odd and tricky given that I don't have any control over that.

The first thing I have to do is repeat your results.
Can you both also mention OS type and printers.
@cleidigh

_Originally posted by @cleidigh in https://github.com/cleidigh/printing-tools-ng/issues/225#issuecomment-1652113504_

**Comment by Mark3032** [comment]
Printer is PDF24 (https://www.pdf24.org/),
Windows 10

**Comment by cleidigh** [comment]
@Mark3032 
Thanks 
I am closing as I think this was a mistake 
@cleidigh

**Comment by cleidigh** [comment]
closing
