### ISSUE TITLE
Printing Tools NG Hide Header Does Not Work

### ISSUE THREAD

**Issue by alamest** [cleidigh/printing-tools-ng#239]
Hello Team

I checked the option hide header in header tab still the header shows in the receipt print, tried many things still showing header in print

Waiting for your reply

Thanks

**Comment by cleidigh** [comment]
@alamest 
I am not seeing issues with my Win 10 dev machine, Thunderbird 115.4.3 and PrintingTools v3.0.1
Can you identify your versions?
Also are there any messages in the error log?
@cleidigh

**Comment by alamest** [comment]
You can check the attached image, that the header is still showing
I have selected the option "Hide Header" stil showing the header in Windows 11
![WhatsApp Image 2023-11-18 at 20 53 37](https://github.com/cleidigh/printing-tools-ng/assets/27527200/3f8f9116-d606-4e4a-a708-fc6bfccf16f5)

**Comment by cleidigh** [comment]
@alamest 
Which version of Thunderbird and PrintingTools?
I am wondering if PrintingTools is being invoked.
Also, are you using FiltaQuila to auto print? Which version?
Can you do the following : 

- In PrintingTools options fist tab, put the following in the debug options : 
trace1 finaloutput

Then open the error console with Control-Shift-J
Clear by clicking the trash can
Then run a test order
Go back to the error log, right click, copy all messages and then post that here.
@cleidigh

**Comment by cleidigh** [comment]
@alamest 
Any update?
@cleidigh
