### ISSUE TITLE
Maximum length of the lines are ignored

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#24]
Hello,

no matter what length I choose, I don't see any differences

![PrintingTools](https://user-images.githubusercontent.com/77779094/106278384-edab8c00-623a-11eb-9f79-328927986906.PNG)

There are also no differences in output for text or HTML mails.

Can you show an example, please?

**Comment by cleidigh** [comment]
@RRoenn 
b4 partially addresses this.  it looks like the original extension was only truncating
text within <pre> tags.  I do not think that is common these days.  I changed the logic
to truncate text in <p> paragraph tags.  that will cover e-mails using this style.
with so many possible formats,it's really pretty tough to be able to truncate anything 

I think I'm going to leave this 4 with the above improvement although not perfect.
Christopher

**Comment by cleidigh** [comment]
Fixed with 2.0.4
