### ISSUE TITLE
Plugin doesn't work after Thunderbird upgrade

### ISSUE THREAD

**Issue by nikga123** [cleidigh/printing-tools-ng#243]
Is there a way to fully reset the PrintingTools NG add-on? Since upgrading Thunderbird to 115.7.0, I have not been able to get the PrintingTools NG to print or show the dialog box. Prior to upgrading, the plug in worked fine. I tried re-installing the add-on to no avail. 

**UPDATE:** I made a new Thunderbird profile and installed the PrintingTools NG extension. It appears this is an issue with the version of Thunderbird, not corruption of the extension/settings, as I assumed.

If the add-on is set to "Print without the dialog window" it _will_ print. If not set, the dialog does not open and email does not print.

Thank you.

**Comment by cleidigh** [comment]
@nikga123 
I'm all good with Windows, v3.0.1 and Thunderbird v115.7
Can you post the debug console output and maybe we will see something?
@cleidigh

**Comment by nikga123** [comment]
@cleidigh 
Thank you. I ran the pluing with "trace1" (saw that in another post). Here is the output. Doesn't seem to revealing, but you might see something that I dont:

> PTNG: cmd_printng start: options :  null printingtoolsng-pengine.js:621:14
> PTNG: current window:  
> Object { id: 3, focused: true, top: -8, left: -8, width: 1936, height: 970, incognito: false, type: "normal", state: "maximized", alwaysOnTop: false, … }
> ​
> alwaysOnTop: false
> ​
> focused: true
> ​
> height: 970
> ​
> id: 3
> ​
> incognito: false
> ​
> left: -8
> ​
> state: "maximized"
> ​
> tabs: Array [ {…}, {…} ]
> ​
> title: "Sent - Local Folders - Mozilla Thunderbird"
> ​
> top: -8
> ​
> type: "normal"
> ​
> width: 1936
> ​
> <prototype>: Object { … }
> printingtoolsng-pengine.js:639:14
> PTNG: current tab:  
> Object { id: 1, index: 0, windowId: 3, highlighted: true, active: true, status: "complete", width: 712, height: 733, cookieStoreId: "firefox-default", url: "mailbox:///***************", … }
> ​
> active: true
> ​
> cookieStoreId: "firefox-default"
> ​
> favIconUrl: "chrome://messenger/skin/icons/new/compact/folder.svg"
> ​
> height: 733
> ​
> highlighted: true
> ​
> id: 1
> ​
> index: 0
> ​
> mailTab: true
> ​
> spaceId: 1
> ​
> status: "complete"
> ​
> title: "Re:"
> ​
> type: "mail"
> ​
> url: "mailbox:///**************************"
> ​
> width: 712
> ​
> windowId: 3
> ​
> <prototype>: Object { … }
> printingtoolsng-pengine.js:640:14
> PTNG: tab type :  mail printingtoolsng-pengine.js:641:14
> PTNG: tab url:  mailbox:///**************** printingtoolsng-pengine.js:642:14
> PTNG: mailType:  true printingtoolsng-pengine.js:643:14
> PTNG: selectedMessageUris 
> Array [ "mailbox-message://********************" ]
> ​
> 0: "mailbox-message://******************"
> ​
> length: 1
> ​
> <prototype>: Array []
> printingtoolsng-pengine.js:111:14
> PTNG: Done

**Comment by cleidigh** [comment]
@nikga123 
I didn't get much from the trace either, no exceptions.
Did you obscure the uris with asterisks?

Try this.
Set your printer to Save to PDF 
add pdfoutput to your debug options after trace1 with a space between.
Print by selecting a message in the message list
capture debug again.
@cleidigh

**Comment by nikga123** [comment]
Thanks @cleidigh 

Yes, I replaced the URLs with asterisks. This time I replaced out the person info with some other text.

I did as instructed and this is what I got:

> Uncaught TypeError: can't access dead object
>     l chrome://printingtoolsng/content/printingtoolsng-pengine.js:254
> printingtoolsng-pengine.js:254:12
> PTNG: cmd_printng start: options :  undefined printingtoolsng-pengine.js:621:14
> PTNG: current window:  
> Object { id: 3, focused: true, top: 26, left: 76, width: 1357, height: 713, incognito: false, type: "normal", state: "normal", alwaysOnTop: false, … }
> printingtoolsng-pengine.js:639:14
> PTNG: current tab:  
> Object { id: 1, index: 0, windowId: 3, highlighted: true, active: true, status: "complete", width: 712, height: 494, cookieStoreId: "firefox-default", url: "mailbox:///E:/Email/Local%20Folders/temp.sbd/folder.sbd/Sent?number=17420", … }
> printingtoolsng-pengine.js:640:14
> PTNG: tab type :  mail printingtoolsng-pengine.js:641:14
> PTNG: tab url:  mailbox:///E:/Email/Local%20Folders/temp.sbd/folder.sbd/Sent?number=17420 printingtoolsng-pengine.js:642:14
> PTNG: mailType:  true printingtoolsng-pengine.js:643:14
> PTNG: selectedMessageUris 
> Array [ "mailbox-message://nobody@Local%20Folders/temp/nicholasbanks%40mac.com/Sent#17420" ]
> printingtoolsng-pengine.js:111:14
> PTNG: PDF Output using      :  Mozilla Save to PDF printingtoolsng-pengine.js:145:15
> PTNG: PDF Output Dir enabled:  false printingtoolsng-pengine.js:146:15
> PTNG: Output directory (cfg):  <empty string> printingtoolsng-pengine.js:147:15
> PTNG: Single message, Use existing print messagePane printingtoolsng-pengine.js:186:16
> PTNG: Message uri:  mailbox-message://nobody@Local%20Folders/temp/folder/Sent#17420 printingtoolsng-pengine.js:187:16
> PTNG: Message URI:  mailbox-message://nobody@Local%20Folders/temp/folder/Sent#17420 printingtoolsng-pengine.js:315:16
> PTNG: Done printingtoolsng-pengine.js:664:14
>

**Comment by nikga123** [comment]
To be clear, the plugin prints as designed when set to hide the dialog window. But will not show the dialog window (or print) when the hide option is off. This started after an auto Thunderbird upgrade. Not the end of the world, but would be good to have this option working.

Thanks again for your time and for creating this plugin. I find it very useful.

**Comment by cleidigh** [comment]
@nikga123 
Thanks for the clarification and comments.
I'm scratching my head on this.
I may have to add some debug.
What os are you on?. 
@cleidigh

**Comment by cleidigh** [comment]
@nikga123 
One more thing to try:
Enable the pdf output directory and set to valid directory
Now print and you should get alert for preview or or not.
Try both ok and cancel, report results and debug.
Also if you can screenshot the pdf and print options tabs that would be great.
We will figure it out...
@cleidigh

**Comment by nikga123** [comment]
> @nikga123 Thanks for the clarification and comments. I'm scratching my head on this. I may have to add some debug. What os are you on?. @cleidigh

Thank you.
I am running Windows 10. 
(I'll get back to you on your other post in a bit.)

**Comment by nikga123** [comment]
> @nikga123 One more thing to try: Enable the pdf output directory and set to valid directory Now print and you should get alert for preview or or not. Try both ok and cancel, report results and debug. Also if you can screenshot the pdf and print options tabs that would be great. We will figure it out... @cleidigh

Doing the steps you listed above fixed the issue and the dialog now shows when printing. All is good. I can still give you the trace and the screenshots if you’d like, but I think we are good. Thank you very much for seeing this through.

**Comment by cleidigh** [comment]
@nikga123 
That is great!
I'm very happy we got it!
Reviews are always welcome %-)
@cleidigh

**Comment by nikga123** [comment]
Sorry, I spoke too soon. It worked for a while. I'll have to post the trace and screenshots after all. Not sure why it goes in and out.

Review: Yes! I'll review the product either way. The preview dialog is just an inconvenience, the plugin works just fine without it, which is how I primarily use it. I'll post a good review.

**Comment by nikga123** [comment]
A bit more data: The dialog opens when the email preview screen is "off." It doesn't work when preview screen is "on."

**Comment by nikga123** [comment]
[trace.txt](https://github.com/cleidigh/printing-tools-ng/files/14185874/trace.txt)
![PDF Output](https://github.com/cleidigh/printing-tools-ng/assets/105826760/4364a7d8-f5ad-4365-b73a-6b8becd84a31)
![Print and Page Options](https://github.com/cleidigh/printing-tools-ng/assets/105826760/717a0bee-500b-4509-9516-f8839f7efa6f)

Trace and screenshots attached. The trace is printing to PDF (clicking Ok) and then printing to PDF (clicking Cancel).

Thanks a lot @cleidigh !

**Comment by cleidigh** [comment]
@nikga123 
I'm not sure I understand your last comment.
What setting do you mean by "preview screen"?

**Comment by nikga123** [comment]
@cleidigh 

Sorry for being unclear. I'm referring to the email message pane (where you can see the content of the email). When the message pane is open, the print dialog fails to appear. When the message pane is closed (cannot see email content), Printing Tools NG opens the print dialog without issue.

**Comment by cleidigh** [comment]
@nikga123 
Ok so are you good or do you wish to debug further?
@cleidigh

**Comment by nikga123** [comment]
@cleidigh Good to go! Thank you. (I left a review for your add-on.)
