### ISSUE TITLE
Won't print to pdf only to printer

### ISSUE THREAD

**Issue by the-stagehand** [cleidigh/printing-tools-ng#249]
​Description of steps:
For a month now since initially installing PTNG has been working flawlessly to print to pdf exactly as expected with output directory & filename. Yesterday I upgraded TB to its latest version. I can't remember if there was also an upgrade for PTNG. After doing so, now, when I attempt to trigger a Print to PDF, it won't. It always defaults to print to the System Printer. 
I've removed most of the addons and disabled 2 I kept. I removed and reinstalled PTNG.
Thanks.

PTNG Version 3.0.1
TB 115.10.1 (64-bit)
Silicon MacOS Ventura Version 13.6.4

ERROR CONSOLE LOG 
w/Debug options pdfoutput & printsettings:
PTNG: Current system printer (bef force): Mozilla Save to PDF [printerSettings.js:553:15](chrome://printingtoolsng/content/printerSettings.js)
PTNG: New system printer : Mozilla Save to PDF [printerSettings.js:559:17](chrome://printingtoolsng/content/printerSettings.js)
PTNG: PDF Output using      :  Mozilla Save to PDF [printingtoolsng-pengine.js:145:15](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: PDF Output Dir enabled:  true [printingtoolsng-pengine.js:146:15](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: Output directory (cfg):  /Users/... [printingtoolsng-pengine.js:147:15](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: PDF Output autosave :  true [printingtoolsng-pengine.js:154:16](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: PDF Output using      :  Mozilla Save to PDF [printingtoolsng-pengine.js:388:15](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: PDF Output Dir enabled:  true [printingtoolsng-pengine.js:389:15](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: Output directory (cfg):  /Users/... [printingtoolsng-pengine.js:390:15](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: Message URI:  imap-message://email@address.com@inbox [printingtoolsng-pengine.js:434:16](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: Filename:  /Users/path/test.pdf [printingtoolsng-pengine.js:435:16](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: toFilename:  /Users/path/test.pdf [printingtoolsng-pengine.js:436:16](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
PTNG: pageRanges:  
Array []
[printingtoolsng-pengine.js:437:16](chrome://printingtoolsng/content/printingtoolsng-pengine.js)
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
2 [test.html](chrome://printingtoolsng/content/test.html)
TypeError: browser is null
[BrowserElementParent.sys.mjs:21:21](resource://gre/actors/BrowserElementParent.sys.mjs)

**Comment by cleidigh** [comment]
@the-stagehand 
Thanks for the post, sorry for the issue!
I just did a quick check on Windows without issue. I have to get my Mac to check there. I'm not sure that will tell me much as I am unfortunately running Mojave as it's old. PDF on Mac has had issues in the past.

So questions : 
- Can you print to pdf with the Thunderbird Print?
- If you preview is the email formatted correctly?
- If you print from preview what happens?
- What view are you printing from?

I may have to bite the bullet and get a newer Mac...
@cleidigh

**Comment by the-stagehand** [comment]
@cleidigh 
Hi, thanks for the reply.
So, it had something to do with the path for output directory. I changed it to another directory to see if it would work and it did. Then when I changed it back to the original directory it also worked. It's the exact same path as before.

To answer your ?s:
Yep, could print to TB Print
Yep, is formatted correctly in preview
Printing from preview worked normally.
I'm uncertain the view name, but it's the [cancel] and [print] selection view. I select print to go straight to Pdf without review. 
I could see the info line at the bottom of the window report it attempting to create the file, then it would divert to the printer. If I select cancel it proceeds to TB print view and prints from there. I also attempted to print from multiple files chosen with the same results - immediately attempts to write to file, then diverts both jobs directly to the printer without any other interaction.
I'm not a programmer, so I hope that helps. Probably just needs some sort of check on the output path.
Hah, yeah, seems like good idea. I like playing around with the silicon.
Let me know if you have any other questions, but I'm good at this point (knocks on wood.)
@the-stagehand

**Comment by cleidigh** [comment]
@the-stagehand 
Thanks for the report.
I am not sure what happened, however, it seems like a glitch that I would not know how to avoid.
One thing that has come up on newer osx is the apple security manager blocking access to directories. I wonder if that could be the issue?
@cleidigh
