### ISSUE TITLE
How use ${date_custom} at file name format?

### ISSUE THREAD

**Issue by Zombiehamser** [cleidigh/printing-tools-ng#250]
I want add ${date_custom} to file name format, and as default I have settings:
![image](https://github.com/cleidigh/printing-tools-ng/assets/57707453/7cb3e904-ab99-4524-9e3c-703128f61464)
with file name:
![image](https://github.com/cleidigh/printing-tools-ng/assets/57707453/4b20d1bf-6cdb-4d23-99ae-45a07e12922f)

I want change it to the next format: %Y.%m.%d %H:%M:%S 
But I dont know how write format string.
${%Y.%m.%d %H:%M:%S } or ${date_custom('%Y.%m.%d %H:%M:%S')} not working.

**Comment by cleidigh** [comment]
@Zombiehamser 
You change the custom date field and just use the % items, no braces or token names. So:
Use
%Y.%m.%d %H:%M:%S
In the custom date field and
${date_custom}_${subject}
as you already have for the filename field.
@cleidigh

**Comment by Zombiehamser** [comment]
> @Zombiehamser You change the custom date field and just use the % items, no braces or token names. So: Use %Y.%m.%d %H:%M:%S In the custom date field and ${date_custom}_${subject} as you already have for the filename field. @cleidigh
Thanks a lot! Working perfect!

**Comment by cleidigh** [comment]
@Zombiehamser 
отличный!
I will go ahead and close this.
Cheers.
@cleidigh
