### ISSUE TITLE
 Doesn't print after a few days

### ISSUE THREAD

**Issue by vallesierra** [cleidigh/printing-tools-ng#252]
Hello, there is a similar thread but I decided to open my own thread. I use printing-tools-ng and it works perfectly for 3 - 4 days, then suddenly it doesn't print, I manually run the filter created with "FiltaQuilla" and the printing doesn't work.
I have Thunderbird installed on my PC, when Windows starts it automatically runs and opens. I have programmed a filter with FiltaQuilla which sends the email from 'x' sender to a specific folder and prints the email. I notice that the email is moved to the indicated folder, but the email is not printed. Many times I have to uninstall "printing-tools-ng" and reinstall it to make it work, but days later the same thing happens.
When the error occurs, printing does work by clicking from IMPRIMIT NG

**Comment by cleidigh** [comment]
@vallesierra 
I owe you another response on the width issue, but I have been swamped lately. I will address this first being more important. 
With quite a number of people using this I'm hopefully we can work , bit tricky as you can imagine.

So first thing is to put
trace1
in debug options, this will give us some debug output.
Now when it stops working we will want to capture the debug output and post here.
To do this follow below: 

- Open debug console with Control-Shift-J
- Clear with trashcan
- Return to Thunderbird 
- When problem occurs, go to console 
- Right click and choose Copy all messages 
- Paste into notepad and save file, post this file here
- Now clear log and press the print button 
- capture and post that output as well 

We will start there.
Also restarting Thunderbird without a reinstall does not make it work again?

@cleidigh

**Comment by vallesierra** [comment]
Perfect, I have done what you told me, I have cleaned the output console and I have sent a test email which has been printed correctly, I have consulted the console and I observe that some errors or warnings have been generated, it was also printed correctly .
I will send new results when I fail, thank you very much for your help Cleidigh.

[https://drive.google.com/file/d/1WiLJ0VJCR6AkoqTHEMH-Q06LdbpKJrxm/view?usp=drive_link](https://drive.google.com/file/d/1WiLJ0VJCR6AkoqTHEMH-Q06LdbpKJrxm/view?usp=drive_link)

**Comment by cleidigh** [comment]
Excellent!

**Comment by vallesierra** [comment]
The error occurred very quickly, I sent email and the email was not printed, the log is as follows.
[https://drive.google.com/file/d/1W4BwHTGH7N6m9WRb3J0DtqV-cYlNCPru/view?usp=drive_link](https://drive.google.com/file/d/1W4BwHTGH7N6m9WRb3J0DtqV-cYlNCPru/view?usp=drive_link)

Then press the "Print NG" button which printed correctly, generating the following log.
[https://drive.google.com/file/d/1-Acu1XaOcdDOnriTEu6a69m9-_9RchGN/view?usp=drive_link](https://drive.google.com/file/d/1-Acu1XaOcdDOnriTEu6a69m9-_9RchGN/view?usp=drive_link)

I manually ran the message filter with: "Run Now", it did not print and generated the following log.
[https://drive.google.com/file/d/1qdCoz9GZUvigZzOZBH8EWHlAKDmx8QdC/view?usp=drive_link](https://drive.google.com/file/d/1qdCoz9GZUvigZzOZBH8EWHlAKDmx8QdC/view?usp=drive_link)

I closed Thunderbird and reopened it, sent email again and it printed, generating the following log.
[https://drive.google.com/file/d/1-nu2qaZB5RMJu_6xrIW6mRJhUKIUV3T7/view?usp=drive_link](https://drive.google.com/file/d/1-nu2qaZB5RMJu_6xrIW6mRJhUKIUV3T7/view?usp=drive_link)

**Comment by cleidigh** [comment]
@vallesierra 
Thanks for your detailed logging, I am looking at them now.
One question, is Thunderbird always on the message tab? No one is doing anything with it correct?
@cleidigh

**Comment by cleidigh** [comment]
@vallesierra 
Well one interesting thing I noticed in the logs is you are in Columbia, que bueno, siempre me gusto saber donde estan mis usadores %-)
Estaba en muchos partes de Sud America y vivio en Argentina pero no tuvo la placer de viajar de Columbia. Bueno, de la problema...

All the errors are a failure to get a message mapping. It's an internal error that will be a bit of an effort to track. I need to figure out the internal location that the error does not specifically show.

I will work on this first.
Saludos
Christopher

**Comment by vallesierra** [comment]
If I live in Colombia, we have very beautiful places, Argentina is also beautiful, I hope one day you will have the joy of visiting 🙂
I really appreciate your interest in helping me and improving the plugin, thank you very much 👍🏼, I will be attentive Cristobal.

**Comment by cleidigh** [comment]
@vallesierra 
Buen dia.
Yes I wish I could visit Columbia, my wife loved Cali. Unfortunately with ALS my travels are over

No progress so far , but I have one thought. You are doing a message move before the print. That's something I have not seen before. Would it be possible to test without doing the move? Another possible test would be to print then move.
Just two ideas.
Cristobal

**Comment by vallesierra** [comment]
Hello, what a coincidence I am from Cali.

Currently it moves the message and then prints, but I have created print and then move, I will tell you what happens. I will also test by just printing.

**Comment by cleidigh** [comment]
@vallesierra 
Excelente y que bueno de conocerte amigo\a de Cali!!
Cristobal

**Comment by cleidigh** [comment]
btw
The print with no move would be the first test I would do as that is what eliminates things most users do not do.
Cristobal

**Comment by vallesierra** [comment]
Es un gusto Cristobal, mi nombre es Edwin Sierra.

Ok perfecto, realizaré pruebas solo imprimiendo.

**Comment by cleidigh** [comment]
Perfecto Edwin!

**Comment by cleidigh** [comment]
Hola Edwin
Estoy esperando que la falta de noticias es bueno?
Ha trabajando bien?
Cristobal

**Comment by vallesierra** [comment]
Hola Cristobal
Hasta el momento ha trabajado bien, voy a darle seguimiento una 1 semana más, lo tengo como solo **imprimir** el correo, sin enviarlo a ninguna carpeta, lo de la impresion "Ajustar ancho" lo volvi a configurar de esa manera y esta funcionano bien.

Muchas gracias por tu apoyo, te estaré contando alguna novedad.

Ya sabes aquí en Colombia tienes un amigo, saludos.

**Comment by cleidigh** [comment]
Hola amigo, 
Como vai en Cali?

Que te crees? Esta funciando bien todo?
Cristobal

**Comment by vallesierra** [comment]
¡ Hola Cristobal !
Todo muy bien por acá, 

Las pruebas durante estas 2 semanas han sido exitosas, ha trabajado muy bien, quiero agradecer tu valiosa ayuda y felicitarte por tan excelente herramienta que creaste y mantienes, la cual utilizamos miles de personas, nuevamente muchas gracias.

Cuando quieras visitar este hermoso país tienes las puertas abiertas, siempre a la orden.

**Comment by cleidigh** [comment]
Hola Edwin
Che, barbaro!
Voy a cerrar.
Espero que te vas bien!
Christobal
