### ISSUE TITLE
Print without the dialog option is disabled after restart

### ISSUE THREAD

**Issue by amwebch** [cleidigh/printing-tools-ng#26]
Hi,

First of all, thank you for this great addon!

Unfortunately I have a small bug: under "Global printing options", the checkbox "Print without the dialog" gets disabled after each restart. This is quite annoying, especially when you configure the solution for clients who are not tech-savvy and have no clue where to look for in order to correctly re-enable the setting.
I suppose that this is more of an issue on Thunderbird-side, because the issue happen also when editing the preference "print.always_print_silent" in the Config editor, it still gets disabled again after the next restart. But maybe you can still have a look into it, in the hope that there is something you can do on the addon side to make the setting more persistent.

The only workaround I found for now is to manually edit the file "channel-prefs.js" (under "Program Files\Mozilla Thunderbird\defaults\prefs") and adding the following line:
`pref("print.always_print_silent", true);`
Unfortunately I don't know how future-proof this solution is.

I am using Thunderbird 78.7.1 (64 bit) and PrintingTools NG 2.0.0

Thank you and best regards,
Aron

**Comment by cleidigh** [comment]
@amwebch 
Thanks!
I just did a test with 2.0.0/78.7.1(32-bit) as well as the next maintenance beta 2.0.1-b4
the silent preference  remained sticky through restarts. also I am on Windows 10, I don't think it was clear what OS you are using.
I will install the latest 64bit so we are consistent on that front
one thing that will be interesting for you to check  is if you can see if the preference remains sticky if you have all extensions disabled.
cheers
Christopher

**Comment by amwebch** [comment]
Thanks @cleidigh for the feedback.

I have made some additional tests, and effectively the problem seems to be a conflict with another addon: [FilaQuilla](https://addons.thunderbird.net/it/thunderbird/addon/filtaquilla) - Version 3.0.3
If I keep FiltaQuilla disabled the option "Print without the dialog" and the corresponding preference "print.always_print_silent" stay active persistently, but as soon as I enable FiltaQuilla, the option is disabled (right away, without even the need to restart Thunderbird).

NB: I am using Windows 10, too (sorry for that missing information)

Best regards,
Aron

**Comment by cleidigh** [comment]
@amwebch 
I have  brought  @realraven in a look at both extensions
Christopher

**Comment by cleidigh** [comment]
@realraven
I see where you are always setting the print_silent preference to true .
that is conflicting when 'users set it in printing tools.
what do you suggest we do?
![image](https://user-images.githubusercontent.com/25272315/108788574-44f50180-7546-11eb-977d-b8b5cb0237f3.png)

**Comment by RealRaven2000** [comment]
The only quick way to fix this that I can imagine is to backup the setting when printing starts and restore it after each print operation, like this:

```
self.print =
{
  id: "filtaquilla@mesquilla.com#print",
  name: self.strings.GetStringFromName("filtaquilla.print.name"),
  apply: function(aMsgHdrs, aActionValue, aListener, aType, aMsgWindow) {
    // print me
    let count = aMsgHdrs.length;
    for (let i = 0; i < count; i++) {
      let hdr = aMsgHdrs.queryElementAt(i, Ci.nsIMsgDBHdr);
      printQueue.push(hdr);
    }
    let rootprefs = Cc["@mozilla.org/preferences-service;1"]
                       .getService(Ci.nsIPrefService)
                       .getBranch("");

    function printNextMessage() {
      if (printingMessage || !printQueue.length)
        return;
      printingMessage = true;
      let timer = Cc["@mozilla.org/timer;1"].createInstance(Ci.nsITimer);
      timer.initWithCallback(function _printNextMessage() {
        let hdr = printQueue.shift();
        let uri = hdr.folder.generateMessageURI(hdr.messageKey);
        Services.console.logStringMessage("Queue filter request to print message: " + hdr.subject);
        let printSilentBackup = rootprefs.getBoolPref("print.always_print_silent");
        rootprefs.setBoolPref("print.always_print_silent", true);
        let printDialog =
          window.openDialog("chrome://messenger/content/msgPrintEngine.xhtml", "",
                            "chrome,dialog=no,all,centerscreen",
                            1, [uri], statusFeedback,
                            false, Ci.nsIMsgPrintEngine.MNAB_PRINT_MSG, window);
        printDialog.addEventListener("DOMWindowClose", function (e) {
          Services.console.logStringMessage("Finished printing message: " + hdr.subject);
          printingMessage = false;
          rootprefs.setBoolPref("print.always_print_silent", printSilentBackup); // try to restore previous setting
          
          printNextMessage();
        }, true);
      }, 10, Ci.nsITimer.TYPE_ONE_SHOT);
    }
    printNextMessage();
  }
```

**Comment by RealRaven2000** [comment]
is the option disabled (grayed out so you cannot change it) or switched off (the checkbox not ticked)?
Is there a way to set this setting in Thunderbird itself (or do we need printing-tools-ng) for this?

I raised [issue 97](https://github.com/RealRaven2000/FiltaQuilla/issues/97) on the FiltaQuilla github for tracking this - assuming you want it fixed for Thunderbird 78...

**Comment by RealRaven2000** [comment]
I added a test version here:

https://github.com/RealRaven2000/FiltaQuilla/issues/97#issuecomment-785067703

**Comment by cleidigh** [comment]
@RealRaven2000 
printing tools allow users to set Print_silent in the options and it is supposed to remain sticky.
FQ sets it false each time starts.  I can override but why do you need to reset it?

**Comment by RealRaven2000** [comment]
I don';t think this should be on startup, but I only just see that Kent added:
```
    try {
      rootprefs.clearUserPref("print.always_print_silent");
    } catch (e) {}
```
I think that's clearly wrong as it deletes any preferences a use may have set (including setting with printing tools NG). I think that needs to be removed too. The patch addresses what happens during the filter - print action only (where the printout should be done without human interaction).

Fresh patch: https://github.com/RealRaven2000/FiltaQuilla/issues/97#issuecomment-785297545

**Comment by cleidigh** [comment]
@RealRaven2000 
Okay that makes sense,I agree it should not change the preference permanently.
PT gives access to this preference which I do not believe can be set anywhere else
other than the config editor.  If anything else changes it PT will Respect the  change.
can you think of anything else in conflict?  does FQ allow the user to change?

**Comment by RealRaven2000** [comment]
> @RealRaven2000
> can you think of anything else in conflict? does FQ allow the user to change?

No, Filtaquilla is a pretty "hands off" Add-on which only has a dialog for enabling / disabling custom actions and conditions. I think this one was just programmed a little sloppily by Kent (who planned to circle back on the feature and never got around to it)

**Comment by cleidigh** [comment]
fixed in FQ
