### ISSUE TITLE
Presentation of the date format short

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#28]
Hello Christopher,

with the b4 I only get 20.1.2021 and also 1.3.2021. I think that is realy short short...

A paper print from mail recived 20.01.2021, 10:31 looks good
The change is since printing-tools-ng-2.0.1-b2-tb (22.01.2021)

It looks much better with a leading 0, so like 01.03.2021

at position // cleidigh fix short format
			if (longFormat === 0) {
				options = {
				  year: 'numeric', month: '2-digit', day: '2-digit'
				 ...

With time (hour, minute) I see no diffenent between 'numeric' or '2-digit' option

Can you add a new option for that or fix it to the old behavier?

Many thanks!

**Comment by cleidigh** [comment]
@RRoenn 
Just in time,I was just about to finalize.
here's the results of the patch:
let me know case I miss anything ASAP
![image](https://user-images.githubusercontent.com/25272315/109563078-47f37300-7aad-11eb-99c2-ddc5f59c07fa.png)

**Comment by cleidigh** [comment]
@RRoenn 
implemented in b6/posted

**Comment by RRoenn** [comment]
YES. Thank you :-)

**Comment by RRoenn** [comment]
oh, I got the wrong version 2.0.0 : 68/78 Update - January 3, 2021
where is b6 ?

**Comment by cleidigh** [comment]
just posted 2.0.1 to the queue
you will probably have to manually update
