### ISSUE TITLE
Where can I configure the settings?

### ISSUE THREAD

**Issue by zalmanlew** [cleidigh/printing-tools-ng#29]
I initially found it in **Print Preview** (there was a button called <kbd>Printing options</kbd>)

I had unchecked everything - including the option for `⬜ Show the options button in the preview window`.

I'm not sure how to undo this and I cannot seem to find how to access it any other way.

I'm on Thunderbird 78.7.1 if it makes a difference

**Comment by cleidigh** [comment]
@zalmanlew 
if you enable the main menu there is a tools menu with options Menu for extension options
see the screenshot.  NOTE IN THE NEXT VERSION V2.0.1 this will be removed and options will set the add-ons page under the ellipses for each extension
![image](https://user-images.githubusercontent.com/25272315/110038481-cbab9a80-7d0d-11eb-8898-f0e1237a9fa4.png)
Christopher
