### ISSUE TITLE
Hide the headers - still leaves some extra whitespace on top

### ISSUE THREAD

**Issue by zalmanlew** [cleidigh/printing-tools-ng#31]
I activated `Hide the headers` to remove the default headers - this helps a lot but there's still approximately ¾" or so of whitespace.

Is it possible to reduce the amount of extra whitespace still being occupied at the top of the page?

**Comment by cleidigh** [comment]
is this possibly the margins ?

**Comment by zalmanlew** [comment]
@cleidigh I investigated further and noticed that the printer itself needs to feed a bit before cutting (which is where most of the whitespace comes from).

**Comment by cleidigh** [comment]
excellent!
I like easy solutions
Christopher
