### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#34]
Hello @cleidigh.

Where can I find the original to these translation?
![Unbenannt](https://user-images.githubusercontent.com/77779094/110241318-7a3f1d80-7f50-11eb-9e9b-7cc236799d64.PNG)

There are some mistakes and typos... which I would like to correct.

And I think for `<!ENTITY wrap "Wickeln">` better translation is "Umbrechen"

**Comment by cleidigh** [comment]
@RRoenn 
this is actually the extension description on ATN.  it may be on the automatic translation.
'current text

PrintingTools NG bietet zahlreiche Layout- und Formatierungsoptionen für
Drucken von Nachrichten, Adressbüchern und einzelnen Kontakten. Es ist
eine Abzweigung und Aktualisierung der ursprünglichen PrintingTools-Erweiterung. Zur Zeit
Die Erweiterung unterstützt Thunderbird 68-72 mit der Absicht, letztendlich
Konvertierung in eine vollständige MailExtension für 78+.

<b> Neue Version 0.1.3: Gebietsschemas / Drucker </ b>

- Neue Standarddruckeroption (dauerhaft)
- Fehlende Übersetzungen korrigieren
- Viele neue Orte
 
Vollständige Gebietsschemaliste (Original und Neu):

   (hy) Armenier, (ca) Katalaner, (zh-CN) Chinesen (vereinfacht),
   (da) Dänisch, (nl) Niederländisch, (en) Englisch, (fi) Finnisch,
   (fr) Französisch, (gl) Galizisch, (de) Deutsch, (el) Griechisch,
   (hu) Ungarisch, (it) Italienisch, (ja) Japanisch, (ko) Koreanisch,
   (nein) Norwegisch, (pl) Polnisch, (pt-PT) Portugiesisch (Portugal),
   (ru) Russisch, (sk) Slowakisch, (sl) Slowenisch, (es) Spanisch,
   (sv) schwedisch, (uk) ukrainisch


Im Folgenden sind die wichtigsten Verbesserungen aufgeführt, die von PrintingTools NG bereitgestellt werden:
Weitere Funktionen finden Sie in den Optionen.

Optionen & Menüs:
- Zugriff auf Optionen über die Tools / Add-On-Optionen
- Das Menü Druckoptionen wurde zu den Dateimenüs hinzugefügt
- Optionale Schaltfläche "Druckoptionen" zum Fenster "Seitenansicht" hinzugefügt

Nachrichtenlayout und Formatierung:
- Nachrichtenkopfrahmen hinzufügen
- Fügen Sie Benutzername, Ordner oder benutzerdefinierten Titel hinzu
- Standard- oder erweiterte Header ausblenden
- Standard-Header neu anordnen
- Fügen Sie die Anhangstabelle mit Symbolen zur Kopfzeile hinzu
- Inline-Anhänge ausblenden
- Konfigurieren Sie Schriftfamilie und Schriftgröße
- Markieren Sie die zitierte Textfarbe, Schriftart und Größe
- Nur ausgewählten Text drucken

Adressbuch & Kontakt Layout & Formatierung:
- Konfigurieren Sie Schriftfamilie und Schriftgröße
- Kompakte Druckformatoption
- Nur Name und E-Mail drucken
- Entfernen Sie "Card For" aus den Einträgen

**Comment by cleidigh** [comment]
Closed w/v2.0.5
