### ISSUE TITLE
I'd like to help with Japanese translation.

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#37]
Hellow Christopher Leidigh!
 
I used to provide the Japanese locale for the original Printing Tools.

There are several untranslated and incorrect translations in the current Japanese locale of PrintingTools NG.
I would like to provide a corrected locale file.
Please tell me how to do that.

**Comment by cleidigh** [comment]
@kiki-ja 
that would be great!
are you able to do a PR on the Japanese locale files ?
if not I can point you to the files and you could edit them and return them
Christopher

**Comment by kiki-ja** [comment]
@cleidigh

This is the first time I am using GitHub.
So I don't know how to use it.
Please help me understand.

**Comment by cleidigh** [comment]
@kiki-ja 
probably easiest for me to post both the English and Japanese finals here
then you edit
I then merge
Christopher

**Comment by cleidigh** [comment]
sorry bad  dictation I am disabled
I  will post the files here

**Comment by cleidigh** [comment]
Closed w/v2.0.5
