### ISSUE TITLE
To much options ...

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#38]
Version 2.0.4 : 68/78 Update - March 9, 2021

Pagepreview
![options](https://user-images.githubusercontent.com/77779094/110788804-64429d00-826f-11eb-9642-5fb9294a4ac1.PNG)

There is a bug while moving the options to the addon dialog ...

**Comment by RRoenn** [comment]
After the update everything seemed to be okay.
Going from pagepreview to settings was also fine.

Then I visited the settings from this detailed view ...
![setting](https://user-images.githubusercontent.com/77779094/110792385-9bb34880-8273-11eb-819d-7ffbc4975d4b.PNG)

**Comment by RRoenn** [comment]
After restart, everything is fine now. Can't reproduce it.

Maybe only the first time after updating to v2.0.4 without restart thunderbird?

Or maybe because I clicked on the yellow message bar ...

**Comment by cleidigh** [comment]
@RRoenn 
good looks like it's okay.
I think the issues concerns doing the complete removal before updating
I saw some of the things you did a couple of times.

**Comment by cleidigh** [comment]
can we close this?

**Comment by RRoenn** [comment]
so if this is no bug, just a feature ;-)
we can close. Thank you again
