### ISSUE TITLE
Increase Print Font Size above size 36

### ISSUE THREAD

**Issue by kcomu** [cleidigh/printing-tools-ng#44]
In the print preview window, when I go to printing options, then style and the "use fonts with a size in pixel of" setting, the maximum font size is 36. I would like to be able to set a font size above 36 (preferably, I would like it as large as is possible).

Thanks,

**Comment by cleidigh** [comment]
@kcomu 
just curious, is this to support visually impaired users? I just ask because I am disabled so accessibility is very important to me
if I keep this to a picklist I can easily get you a beta
can you think of a reasonable maximum?
Christopher

**Comment by kcomu** [comment]
Hi Christopher, This isn't for a visually impaired user, but I do need my documents to print in a large font, as these prints will need to be viewable from a distance. If you could set it for 150 font, with options for 125 and 100 (or somewhere close to them) that should work for what we need it to do. 

Thanks for your help. 
C

**Comment by cleidigh** [comment]
@kcomu 
check out the beta
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b1-tb.xpi
I added sizes 
May still do it as a value box

**Comment by cleidigh** [comment]
Closed w/v2.0.5
