### ISSUE TITLE
please correct all Japanese locale names to "ja".

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#46]
Incorrect locale name in Japanese.
It is "ja", not "ja-JP".

The locale name "ja-JP" does not exist in Mozilla products.

"ja" = for Windows,Linux
"ja-JP-mac" = for macOS

If you don't specify an OS, just use "ja".
So please correct all Japanese locale names to "ja".

[Reference.]
Directory Listing: /pub/thunderbird/releases/78.8.1/win64/
https://ftp.mozilla.org/pub/thunderbird/releases/78.8.1/win64/

Directory Listing: /pub/thunderbird/releases/78.8.1/linux-x86_64/
https://ftp.mozilla.org/pub/thunderbird/releases/78.8.1/linux-x86_64/

Directory Listing: /pub/thunderbird/releases/78.8.1/mac/
https://ftp.mozilla.org/pub/thunderbird/releases/78.8.1/mac/

**Comment by cleidigh** [comment]
Closed w/v2.0.5
