### ISSUE TITLE
Unable to save font selection.

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#47]
@cleidigh

[Bug Report]
There is a problem that the font selection in the print option of the address book is not saved.
I hope this will be fixed in the future. 

![Address Book - Option](https://user-images.githubusercontent.com/80428201/110912718-9d563c80-8357-11eb-8a91-99d281a8095c.jpg)

**Comment by kiki-ja** [comment]
@cleidigh 

Report 2.0.5-b7

This is the difference I found in the font selection issue.
There were the following differences between the one for messages and the one for addressbook.

[about:config]
Fine: "extensions.printingtoolsng.messages.font_family" = "BIZ UDP ゴシック".
Invalid: "extensions.printingtoolsng.addressbook.font_family"= "BIZ UDP???"

It looks like there is a problem with font family names containing Japanese characters.
Why don't we just process the same code as for messages?
Could this be a hint to fix it?

**Comment by kiki-ja** [comment]
Please see the screenshot.

![font select](https://user-images.githubusercontent.com/80428201/114252008-2c4d8780-99de-11eb-8f5d-2bfc7069e1ca.png)


![font select 03](https://user-images.githubusercontent.com/80428201/114252013-3079a500-99de-11eb-915f-2c53c8dc8936.png)

**Comment by cleidigh** [comment]
I completely missed the font including Japanese characters
I am trying to locate a font I can test with.
Christopher

**Comment by kiki-ja** [comment]
@cleidigh 

2.0.5-b7b solved the problem.
Thank you very much.

Please see the screenshot.

![b7b font familt name](https://user-images.githubusercontent.com/80428201/114304710-a4679a80-9b0f-11eb-9dc5-cd01ed2e5374.png)

If you want to actually test it, you can do so by installing the Japanese language pack from the following link.


'Language packs for Windows'
https://support.microsoft.com/windows/language-packs-for-windows-a5094319-a92d-18de-5b53-1cfc697cfca8

**Comment by cleidigh** [comment]
Closed w/v2.0.5
