### ISSUE TITLE
I translated "About this Add-on" for the Japanese version.

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#48]
@cleidigh

I translated "About this Add-on" for the Japanese version of the following site page.

https://addons.thunderbird.net/ja/thunderbird/addon/printingtools-ng/

The text file is attached.

[About this Add-on - PrintingTools NG.txt](https://github.com/cleidigh/printing-tools-ng/files/6128629/About.this.Add-on.-.PrintingTools.NG.txt)

**Comment by kiki-ja** [comment]
I translated "About this Add-on" for PrintingTools NG 2.0.4 ja version.
The text file is attached.

[About this Add-on - PrintingTools NG 2.0.4.txt](https://github.com/cleidigh/printing-tools-ng/files/6134404/About.this.Add-on.-.PrintingTools.NG.2.0.4.txt)

**Comment by cleidigh** [comment]
@kiki-ja 
does the about text need updating?
I have the change log 
Version 2.0.5 : 68/78 Update - April 23, 2021

- Allow compatibility to 87.0 (experimental support only)
- Add #44 increase maximum font sizes
- Add option for background color
- Add option for customizable borders w/CSS
- Fix #62, #8 Printing selected text w/Print command (not preview)
- Fix #53 handle embedded tables sizing
- Fix #50 localize headers for Japanese
- Fix #49, #30 layout issues, headers 
- Fix #46, #37, Japanese locale improvements @kiki-ja
- Fix #34 German locale improvements @RRoenn
- Fix #52 localize background color label

A big thanks for testers:
@RRoenn
@kiki-ja
@tidebre67 
@KC-T 
@madvinegar

**Comment by kiki-ja** [comment]
@cleidigh 

I don't see any problem with English.
On the other hand, it would be nice to have it localized.
I think it would be great if it were available in multiple languages, not just Japanese.

I translated the change log into Japanese.
Please use it if you like.

The text of the change log translated into Japanese is attached.
[ja change log v2.0.5.txt](https://github.com/cleidigh/printing-tools-ng/files/6356631/ja.change.log.v2.0.5.txt)

**Comment by cleidigh** [comment]
I integrated everything
Thanks!

**Comment by kiki-ja** [comment]
@cleidigh 

I am attaching the Change log for the 2.0.6 update.

I have a favor to ask Christopher Leidigh.
Please add ". " at the end of sentences.
The reason for this is that sometimes the context doesn't make sense or the translation is wrong.

About this Add-on is different between the English and Japanese versions of ATN (addons.thunderbird.net).
It would be great if you could make them the same.

Please forgive me if this is a small request.
 
**ja change log for About this Add-on ja** 
[ja change log v2.0.6.txt](https://github.com/cleidigh/printing-tools-ng/files/6565444/ja.change.log.v2.0.6.txt)
 
 
**About this Add-on on ATN [en-US]**
![About this Add-on on ATN en-US version](https://user-images.githubusercontent.com/80428201/120087189-d4e7b000-c120-11eb-8d45-36ae6007e0aa.png)

About this Add-on on ATN [ja]
![About this Add-on on ATN ja version](https://user-images.githubusercontent.com/80428201/120087232-2b54ee80-c121-11eb-80ea-21348a14a059.png)

**Comment by cleidigh** [comment]
I understand. I edit   tomorrow

thanks again

**Comment by kiki-ja** [comment]
@cleidigh

> I have a favor to ask Christopher Leidigh.
> Please add ". " at the end of sentences.
> The reason for this is that sometimes the context doesn't make sense or the translation is wrong.

The same is true for the comment text in Issues.
Please forgive me if this is a small request.


------------- Original Message ------------
Date: 2021/05/30 Sun 12:31

**Comment by kiki-ja** [comment]
@cleidigh 

I have updated the Japanese description.txt file.

[Japanese description.txt](https://github.com/cleidigh/printing-tools-ng/files/6581354/Japanese.description.txt)

**Comment by kiki-ja** [comment]
@cleidigh 

I have updated the ja change log v2.0.6.txt.

[ja change log v2.0.6.txt](https://github.com/cleidigh/printing-tools-ng/files/6581360/ja.change.log.v2.0.6.txt)

**Comment by kiki-ja** [comment]
@cleidigh 

I have updated the Japanese about.txt.

[Japanese about.txt](https://github.com/cleidigh/printing-tools-ng/files/6581373/Japanese.about.txt)

**Comment by cleidigh** [comment]
@kiki-ja 
excellent,thank you
I finally figured out for where to set the localized change log!
should be set

**Comment by kiki-ja** [comment]
@cleidigh 

I attach a Japanese translation file for addons.thunderbird.net (ATN).
Please use it.

- [About this Add-on - PrintingTools NG 2.1.0.txt](https://github.com/cleidigh/printing-tools-ng/files/8206430/About.this.Add-on.-.PrintingTools.NG.2.1.0.txt)
- [Version Infomation.txt](https://github.com/cleidigh/printing-tools-ng/files/8206432/Version.Infomation.txt)

@kiki-ja
