### ISSUE TITLE
header list a little wider?

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#49]
@cleidigh

Can you please make the header list a little wider?
If it's in Japanese, the line is broken.

A screenshot file is attached.

![Header sample image](https://user-images.githubusercontent.com/80428201/110944696-22554c00-8380-11eb-922e-bbc52e4b7194.jpg)

**Comment by cleidigh** [comment]
@kiki-ja 
I am working on several layout issues and I will take care of this.
it raises an important question I have had:
when I use the Japanese locale several of the header names (subject,from et cetera)
get shown in English, is this the expected result?
thanks
Christopher

**Comment by kiki-ja** [comment]
@cleidigh

> I am working on several layout issues and I will take care of this.

Thanks.

> when I use the Japanese locale several of the header names (subject,from et cetera)
get shown in English, is this the expected result?

Yes, the Thunderbird default is to display in English.
The screenshot below is a print preview of the Japanese version of Thunderbird.
![Header List Sample - Thunderbird ja Default](https://user-images.githubusercontent.com/80428201/111464286-e8ab8900-8763-11eb-853b-7e89de71ecfd.jpg)

I will upload another Issues [feature request] on this issues.

**Comment by cleidigh** [comment]
@kiki-ja 
here's the next step in the layout
may still change some spacing
I think I should leave CC & BCC as is.  This seems to be mainly standard

![image](https://user-images.githubusercontent.com/25272315/111931950-bc10ad80-8a92-11eb-9efe-334a9e057df4.png)

**Comment by kiki-ja** [comment]
> may still change some spacing

添付ファイ
ル：
　　↓
添付ファイル：

The above is good because it is one line with a space.

> I think I should leave CC & BCC as is. This seems to be mainly standard

I think so too.
However, it is good to keep the option to localize.

**Comment by cleidigh** [comment]
@kiki-ja 
b3 has the localization for the headers

b3 has some spacing tweaks and I am not able to produce any outline errors
if someone can show a problem, copy the entire console log after doing a preview
Christopher
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b3-tb.xpi

**Comment by kiki-ja** [comment]
@cleidigh

> b3 has the localization for the headers

That's very good.
There is now a space next to the header list so there are no more line breaks.

I will show you a screenshot of the print preview and PDF print.
This is what I did to fix all the Japanese locales. (printing-tools-ng-2.0.5-b3-ja.zip)

![2 0 5b3 ja Print Preview Sample00](https://user-images.githubusercontent.com/80428201/112147958-9fa27b80-8c20-11eb-9ee8-69e66b5d8b9f.jpg)
 
![2 0 5b3 ja Print PDF Sample](https://user-images.githubusercontent.com/80428201/112147982-a92be380-8c20-11eb-90fc-30fd9700e5bf.jpg)
 
[printing-tools-ng-2.0.5-b3-ja.zip](https://github.com/cleidigh/printing-tools-ng/files/6189689/printing-tools-ng-2.0.5-b3-ja.zip)

**Comment by RRoenn** [comment]
@cleidigh 
you can see also there are missing borders in the print preview (not visible top and bottom).
But in paper print out or pdf print out they are visible, so I think this is no problem to think about.

**Comment by cleidigh** [comment]
I think this is a sporadic rendering issue.

I will try one last thing,making the outlines thicker

then I will give up

1 9:32 AM, RRoenn wrote:

**Comment by cleidigh** [comment]
@kiki-ja 
I think for now I will keep consistency with TB by using cc,bcc as is
I still have to merge your other corrections,next beta

**Comment by kiki-ja** [comment]
@cleidigh

I understand.
I will check the localized files after the merge.

**Comment by cleidigh** [comment]
@RRoenn 
@kiki-ja 
FYI, I seem to have broken 2.0.5-b3
have not been able to fix
I will be working on it
Christopher

**Comment by cleidigh** [comment]
@RRoenn 
@kiki-ja 
b3 is now fully localized @kiki-ja I hope I got all of your translations in
I think I finally fixed the borders
I have to do more testing but wanted you guys to see
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b3-tb.xpi
Christopher

**Comment by kiki-ja** [comment]
@cleidigh

> b3 is now fully localized

Thanks!

> @kiki-ja I hope I got all of your translations in

Unfortunately, some of them were not translated.
I will make updates and pull requests.
Please adopt them.

> I have to do more testing but wanted you guys to see

I also present a modified version of the Japanese translation file.

**Comment by cleidigh** [comment]
b4 should now have all correct translations

**Comment by cleidigh** [comment]
Closed w/v2.0.5
