### ISSUE TITLE
Extension does not work for e-mails which are saved to disk and for e-mails which are attachments to e-mails

### ISSUE THREAD

**Issue by dipgithub** [cleidigh/printing-tools-ng#5]
Hi Christopher,

Great to see that you have also made this wonderful extension compatible with the current version of Thunderbird. Thanks a lot!
I hope you are ok and the virus did still not affect you and your family.

I found the following issue in the extension:
When you open an e-mail message which is save to disk as eml file (by double clicking the eml file) the settings of the extension are not used for this e-mail. That means, that for example the sequence of the header fields is no arranged as defined, the attachments are not included in the header but are still listed only at the end of the message and the font style and size as defined in the extension are not used for the printout. Further, the printer as defined in the extension seems not to be used.

This problem does not only exists when you open an e-mail which is saved to disk, but also if you open an e-mail which is an attachment to a received e-mail.

The problem seems to exist in Microsoft Windows as well as in Linux.

Can you reproduce this problem?

Best regards
Dieter

**Comment by cleidigh** [comment]
@dipgithub 
Great to hear from you. We are doing okay just be very vigilant about isolating.  But I hope you and your family are doing well also.  Germany is doing so much better than most of our country.  Fortunately Rhode Island where we live is still absolutely one of the most responsible states so we are very lucky!

Yes, Thomas, one of your compatriots in the German Thunderbird user community convinced me to update painting tools.
I am weak and glutton for punishment ;-)
I am now completely full time dealing with 4+ significant extensions.  I am also still working on the core Thunderbird team helping developers so no free time!

I had not tried open e-mail from the desktop or any directory before.  I just tried it and it clearly starts Thunderbird put in some form of a single e-mail mode.  The PrintingTools options are intact from whatever last time they were set, but I do see several issues. The "Printing Options" is not added to the file menu , but the button for the options is added to the preview window.  The printing out trends are not applied to the printer output as you observed.

I will have to investigate this mode , but it will be a little bit I am trying to get out the last extension . I am responsible for sixty eight (ColumnsWizard) .

Thanks for the new icon options, I will of course roll those in.
@cleidigh

**Comment by dipgithub** [comment]
@cleidigh 
Christopher, I hope you are still doing well and the virus did not affect you or your family and friends.

I just read that support for Thunderbird 68 will end already in September which means that one has to upgrade to Thunderbird 78 to further receive security updates. Unfortunately, as far as I understand, your extensions printing-tools-ng and import-export-tools-ng will not work in Thunderbird 78. Do you have plans to update them for Thunderbird 78 before support for Thunderbird 68 ends?

Best regards,
Dieter

**Comment by RRoenn** [comment]
I have the same problem when you open an email which is saved to disk, but also if you open an email which is an attachment to a received email.

But I think it is a big bug in Thunderbird himself.
I can't save these emails either. The dialog for saving the file is not displayed.

**Comment by cleidigh** [comment]
Closed with v2.1.0
