### ISSUE TITLE
Please make all headers localizable (L10n).

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#50]
@cleidigh

[Feature request]
Please make all headers localizable (L10n), and allow us to choose between Default and L10n.
See the screenshot below.

![Make all headers localizable](https://user-images.githubusercontent.com/80428201/111465719-c4e94280-8765-11eb-946e-8e57b4b1dcdf.jpg)

Thanks.

**Comment by cleidigh** [comment]
@kiki-ja 
I really do not understand why these are not localized fully for printing.
I think what I will do is add missing localized headers and then add
a Boolean option to use English or localized headers all or none

**Comment by kiki-ja** [comment]
@cleidigh

> I really do not understand why these are not localized fully for printing.

I don't understand it as well. I believe it is a specification.

> I think what I will do is add missing localized headers and then add a Boolean option to use English or localized headers all or none

It's almost exactly what you requested of me.
I agree with a Boolean option.
I think that would be great.

**Comment by cleidigh** [comment]
Closed w/v2.0.5
