### ISSUE TITLE
Please make it possible to localize "Headers Background Color".  -Version 2.0.5

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#52]
@cleidigh

I would like to see "Headers Background Color" localized in all languages.
In the version 2.0.5.

![PrintingTools NG 205b3-Option-Style](https://user-images.githubusercontent.com/80428201/112394655-737e1c00-8d40-11eb-9cc6-041589c1cd08.jpg)

![PrintingTools NG 205b3 ja-Option-Style](https://user-images.githubusercontent.com/80428201/112394664-7711a300-8d40-11eb-8e7c-72d5f3df29a0.jpg)

**Comment by cleidigh** [comment]
Yep

have.  not done final localization

**Comment by cleidigh** [comment]
It is going to be

"Use background for Headers Color:"

**Comment by kiki-ja** [comment]
@cleidigh

I was relieved.
When the localized file is completed, I will send it all translated into Japanese.

Thanks.

**Comment by cleidigh** [comment]
Closed w/v2.0.5
