### ISSUE TITLE
Width of table copied and pasted from Word file too wide to be printed fully (Thunderbird 78.8.1)

### ISSUE THREAD

**Issue by KC-T** [cleidigh/printing-tools-ng#53]
Please see the subject. This did not happen before the recent update. If printing-tools-ng is disabled, the width is fine.

Looking forward to your help.

Printing-tools-ng can print the list of attachment just under the heading band rather than at the end of the email. This saves a lot of paper. Without this feature, I would not use Thunderbird in spite of the many other good features. I did discontinue using Thunderbird during the time when printing-tools became not compatible with Thunderbird upgrade. I resumed after printing-tools-ng came out. 

K C

**Comment by cleidigh** [comment]
@KC-T 
I am about to do a maintenance, release hopefully I can address this.
it would be very helpful if you send me an e-mail with an example table
that does not work. also tell me any relevant settings
can you also be specific about where this broke?
Christopher

**Comment by KC-T** [comment]
Sorry, wrong button pressed to close.

**Comment by cleidigh** [comment]
@KC-T 
this is related to fixing truncation #23  
truncating the body is really not reliable
@rroen
can you check that I did not break our prior fix
if everything looks good I will clean up and release

https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b5-tb.xpi

**Comment by cleidigh** [comment]
Concerning the date format
unfortunately everyone has a different preference
 what I need to do for date format fully configurable 
what locale are you using?
most locales other than the US utilized 24-hour format
it looks like you are using en-US try en-UK

**Comment by KC-T** [comment]
> @KC-T
> this is related to fixing truncation #23
> truncating the body is really not reliable
> @rroen
> can you check that I did not break our prior fix
> if everything looks good I will clean up and release
> 
> https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b5-tb.xpi

Table overflowing issue has been rectified. Thank you!

However, there is a side effect.

The spacing in the header section between the attributes and values has become wider as seen below:

![Screen Shot 04-05-21 at 11 09 AM](https://user-images.githubusercontent.com/81372892/113533051-78c04e00-95ff-11eb-8477-8e1937109283.PNG)

as compared to the previous:

![jjgibegdannbmnab](https://user-images.githubusercontent.com/81372892/113532816-e324be80-95fe-11eb-8de4-8c47b1f076a4.png)

K C

**Comment by KC-T** [comment]
> Concerning the date format
> unfortunately everyone has a different preference
> what I need to do for date format fully configurable
> what locale are you using?
> most locales other than the US utilized 24-hour format
> it looks like you are using en-US try en-UK

I have set the Date and Time Formatting of Thunderbird to use Regional setting locale: English (Hong Kong) or English (Australia).

I have specifically set Windows 10's regional date and time to short date d/M/yyyy and 24-hour format. However, PrintingTools NG's short (native) date format remains unchanged and still displays in M/d/yyyy and 12-hour format. Its long and localized time also still displays 12-hour format.

In the interim, I have switched to use long and localized so as to show the month distinctly from the date. i.e., Apr for 4/5/2021.

K C

**Comment by cleidigh** [comment]
This spacing is to accommodate longer localizations while remaining 
consistent

I May tweak changes between locales

**Comment by cleidigh** [comment]
@KC-T 
The problem is JavaScript has en-US, en-AU, en-HK date formatting
all using 12 hour time.  en-UK uses 24-hour time
I should overwrite the defaults
the ultimate solution I will do later to provide a fully customizable format
in the meantime I think the closest format would be to change to the English locale

**Comment by cleidigh** [comment]
@KC-T 
@kiki-ja
@RRoenn

b6 should be ready to publish unless any issues posted
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b6-tb.xpi

**Comment by KC-T** [comment]
> @KC-T
> @kiki-ja
> @RRoenn
> 
> b6 should be ready to publish unless any issues posted
> https://github.com/cleidigh/printing-tools-ng/blob/v2.0.5/xpi/printing-tools-ng-2.0.5-b6-tb.xpi

@cleidigh @KC-T 

Report:
1. Overflowing table issue resolved. Thanks!
2. Long spacing in headers understood.
3. Truncated subject appearing in 2.0.5-b5 rectified in 2.0.5-b6.
4. Short (native) date or long localized date still give 12-hour format whether using UK or HK locale specifically defined to use 24-hour format in Windows 10.

K C

**Comment by RRoenn** [comment]
@cleidigh 
Hello Christopher, 
Sorry for my lack of response over the Easter days.

my report with b6:
- my settings were retained
- **in the header of the settings dialog is the old version number 2.0.5-b3 displayed**
- **had to restart tb (multiple button in page preview)**
- background color checkbox and color are working
- rendering issue with the bottom border and the right border in page preview still exists, pdf and paper print outs are okay
- visibility and order of the message headers is working
- long list of adresses and long names of attachments are working
- the date format, that we are using, is fine. no checks on other options.

I hope that will help you.

**Comment by kiki-ja** [comment]
@cleidigh 

Report about 2.0.5-b6.

1.Once the background color checkbox is turned on, it cannot be turn off.
This seems to be a problem only in the ja locale.


2.background color are working. This is good!


3.I have the same problem as Issue [Unable to save font selection.#47].
This seems to be a problem only with ja locale.


4.'null' appears at the bottom of the subject line when I turn off 'Align the headers'.
This seems to be a problem only with ja locale.
See screenshot.


5.'headers order' option is incorrect.
This seems to be a problem only with ja locale.
See screenshot.


I'm guessing that the problem with only ja locale is caused by the following
A. Added 'headers-ja.properties'.
B. Added code for 'headers-ja.properties' to 'printingtoolsng-pengine.js' and 'ptng-options.js'.
C. I'm having problems with the code added to them.
                                     
                                         
![Test Sample ja 01 205b6](https://user-images.githubusercontent.com/80428201/113731910-1cab1600-9734-11eb-85d0-eb0611348622.png)

![Test Sample en-US 01 205b6](https://user-images.githubusercontent.com/80428201/113732057-39474e00-9734-11eb-9aca-51c7b49645e2.png)

![Test Sample ja 02 205b6](https://user-images.githubusercontent.com/80428201/113732099-42381f80-9734-11eb-9ec1-b659b5edfabd.png)

![Test Sample en-US 02 205b6](https://user-images.githubusercontent.com/80428201/113732131-48c69700-9734-11eb-9723-cdfc025019c5.png)

**Comment by cleidigh** [comment]
@KC-T 
something is off with your dates, they do not match what I am observing:
- HK uses twelve hour time 
- UK uses twenty four time

this is using en-UK
if that does not work I guess I could force HK to use 24time

![image](https://user-images.githubusercontent.com/25272315/113782069-9aa0fa00-96ff-11eb-952c-ddc10873da39.png)


examples of short gate formats
short date formats printingtoolsng-pengine.js:1059:15
en-US : 04/03/2021, 2:42 AM printingtoolsng-pengine.js:1060:15
en-HK : 03/04/2021, 2:42 am printingtoolsng-pengine.js:1061:15
en-HK : 3/4/2021 printingtoolsng-pengine.js:1062:15
en-UK : 03/04/2021, 02:42 printingtoolsng-pengine.js:1063:15
de : 03.04.2021, 02:42 printingtoolsng-pengine.js:1064:15
default : 03/04/2021, 02:42 printingtoolsng-pengine.js:1065:15
short date formats printingtoolsng-pengine.js:1059:15
en-US : 04/03/2021, 2:42 AM printingtoolsng-pengine.js:1060:15
en-HK : 03/04/2021, 2:42 am printingtoolsng-pengine.js:1061:15
en-HK : 3/4/2021 printingtoolsng-pengine.js:1062:15
en-UK : 03/04/2021, 02:42 printingtoolsng-pengine.js:1063:15
de : 03.04.2021, 02:42 printingtoolsng-pengine.js:1064:15
default : 03/04/2021, 02:42 printingtoolsng-pengine.js:1065:15

**Comment by KC-T** [comment]
@cleidigh @KC-T 

For unknown reasons, the short date format still cannot print 24-hour time (as previously possible before even though I changed my locale to English (UK) or English (Europe). The date and time shown on the bottom right corner of Windows 10 do respond to the changes.

For the time being, I would use long and localized and 12-hour format.

I would suggest you to release the patches for the other issues first while dealing with the date and time options later.

K C

**Comment by cleidigh** [comment]
Closed w/v2.0.5
