### ISSUE TITLE
Print attachment icons for more file types and for files with four character extensions like *.docx

### ISSUE THREAD

**Issue by dipgithub** [cleidigh/printing-tools-ng#6]
Hi Christopher,

In the present version of the add-on icons for attachments are only printed for file types with three character extensions (e.g. *.doc). I amended the code to allow also file types with four character extensions (e.g. *.docx) and added the following file extensions to the list of known file types: docx, jpeg, msg, pptx, tif, tiff, xlsx. All amendments can be found in function "findIconSrc" in file "printingtools.js". I further added the corresponding icon files to folder "icons".

I attach the amended add-on as zip file.

Best regards
Dieter

[PrintingTools_ng-0.1.3_dipgithub-tb.zip](https://github.com/cleidigh/printing-tools-ng/files/4873976/PrintingTools_ng-0.1.3_dipgithub-tb.zip)

**Comment by cleidigh** [comment]
@dipgithub 
finally adding these with the 78 update !
I used some of the newer office icons
see #18 
happy holidays!
Christopher

**Comment by cleidigh** [comment]
added in v2.0.0
