### ISSUE TITLE
printing plain text mail or html mail results in different font size (or zooming)

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#63]
If I have no font style and no text size selected, the text size of plain text mails and html mails is different.

plain text mail
![textmails](https://user-images.githubusercontent.com/77779094/114555154-b6f4e780-9c67-11eb-94b0-980d80a0668e.PNG)

html mail
![htmlmail](https://user-images.githubusercontent.com/77779094/114555252-cd9b3e80-9c67-11eb-8395-c52822a84c93.PNG)

**Comment by cleidigh** [comment]
is this something that definitely changed?

have not really Touched this area

**Comment by RRoenn** [comment]
I don't know if this also in the original version. I just noticed and wanted to show it.

I just testet with v2.0.5-b5 and -b10

**Comment by cleidigh** [comment]
@RRoenn 
unless we specifically choose a font, Thunderbird is in control of this.
I don't think I can change that

**Comment by cleidigh** [comment]
Close?

**Comment by RRoenn** [comment]
Tested with 2 mails with a fresh profil and ptNG v2.1.1-b3 ... I didn't see any differences.
