### ISSUE TITLE
Printing tools for Thunderbird Beta?

### ISSUE THREAD

**Issue by madvinegar** [cleidigh/printing-tools-ng#66]
Is it possible to make "printing tools" addon working in beta editions of thunderbird?

I have an M1 Macbook pro and the only way to get native operation of thunderbird in apple silicon is to install the beta version.

Can you make printing tools work with Thunderbird 88 beta?

Right now I am on the latest beta 88.0b3

Thanks  :)

**Comment by cleidigh** [comment]
actually the latest beta I enabled this

check out

https://github.com/cleidigh/printing-tools-ng/issues/61

b14

Christopher

**Comment by madvinegar** [comment]
I installed it in my M1 MPB. 
Whilst the print selection works great, it does not print out the headers... :) :) :)

**Comment by cleidigh** [comment]
@madvinegar 
I have been able Put verify that 2.0.6-b2  installs and basic operations work
so basically I am enabling 89.* but not guaranteed
any feedback welcome
Christopher 
https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b2-tb.xpi

**Comment by madvinegar** [comment]
Thanks! I will try and let you know!

Στις Πέμ, 20 Μαΐ 2021, 00:13 ο χρήστης Christopher Leidigh <
***@***.***> έγραψε:

**Comment by madvinegar** [comment]
Hi Chris! Tried 2.0.6-b4. Works great. The only problem is that when I print  a selection of the email text (print selection feature) it does not print out the headers. Is there a way to fix this?

No matter if I print a selection of the main body of the email or not, I always want to print the headers.

**Comment by cleidigh** [comment]
I believe the extension only prints the selection, but I don't think it 
ever printed headers with the selection.

are you saying it did before!

Christopher

**Comment by madvinegar** [comment]
In the old original version of "printing tools" (the version I was using in
thunderbird 60.9), when you were selecting text to print, the headers were
always printed out.

The reason this is important is the following.
Imagine a scenario where there are a lot of emails (forwarded the one below
the other) but you want to print out only the last (most recent one). So
you select only the text of the most recent email, but you also need the
headers to be printed out (so as to know the date, title, receivers etc.).

**Comment by cleidigh** [comment]
@madvinegar 
just tested, and it prints headers
profile problem?
![image](https://user-images.githubusercontent.com/25272315/119274771-9497a780-bbdf-11eb-90d8-c5097c990a26.png)

**Comment by madvinegar** [comment]
I don't think it's a profile problem. I have not moved/copied any emails to my macbook. All emails have been downloaded from the server. Maybe it's a settings problem...? I will keep testing and let you know. Thanks again!

**Comment by cleidigh** [comment]
Fixed with v2.0.6
