### ISSUE TITLE
Feature Request - Include display of *.p7s files in the list of attachments.

### ISSUE THREAD

**Issue by aterrion** [cleidigh/printing-tools-ng#67]
By default, Thunderbird ignores the display of .p7s file attachments when printing. 
These are digital signature files used in Russia / Ukraine countries. 
Perhaps this is normal behavior for Thunderbird, but countries like Russia / Ukraine, possibly other countries, use signature algorithms that are not compatible with Thudrebird. Therefore, it is not possible to check the signature by the program itself, but in order to print the information that the attachment contains and the signature file, it must be displayed. 
You can also implement this as the "add_p7m_vcf_attach" option, the principle is the same only to search for p7s files.
This is a popular problem in the RU segment of Thunderbird users, it would be really cool if you can help fix it.

**Comment by cleidigh** [comment]
@aterrion 
I have no experience with p7m or p7s
can you send me some info links? also  e-mail with this type of attachment so I can investigate.
Christopher

**Comment by aterrion** [comment]
@cleidigh 
I sent you an email with a pdf file attachment and a p7s file. (Subject: Mail with p7s file attachment).
The p7m and p7s files are digital signature files, but their formats differ in different countries and if this is not the format used in the USA, Europe, then Thunderbird behaves strangely, not displaying these files as a attachments. The next 2 screenshots will show how I see it.
![Screen-1](https://user-images.githubusercontent.com/25282194/115669975-94db2380-a351-11eb-9d5b-54ce96b345de.jpg)
![Screen-2](https://user-images.githubusercontent.com/25282194/115670010-9dcbf500-a351-11eb-8ef6-e2ea586e8d0b.jpg)

After examining the source code of your plugin, I saw an option to display p7m and vcf files. I remembered that these files are similar in essence and made a change to the original plugin file by replacing ".p7m" with ".p7s" and got what I wanted. Screenshots below.

![Screen-4](https://user-images.githubusercontent.com/25282194/115670531-31052a80-a352-11eb-9945-4c592189df99.jpg)
![Screen-3](https://user-images.githubusercontent.com/25282194/115670551-3498b180-a352-11eb-877a-455b28e5f493.jpg)

**Comment by cleidigh** [comment]
@aterrion 
I observed  the same thing.
I wanted to make sure that it attachment of this type 'was passed to the printing engine
I see that it is
this is a trivial addition for the next  release
possibly next in beta
Christopher

**Comment by cleidigh** [comment]
@aterrion 
For clarification:
just listing the p7s file attachment is sufficient?

**Comment by cleidigh** [comment]
@aterrion 
I think one option to display any key file or a list of hidden attachments to display

**Comment by aterrion** [comment]
@cleidigh 
Yes, listing the p7s file attachment is sufficient.
I also agree that you can combine the display of hidden attachments into one option.
Also, if you agree, then add icons for files
p7s and p7m in signature or handwriting form. Example:
![key](https://user-images.githubusercontent.com/25282194/115829944-46448c80-a418-11eb-8bef-4e823f1e4ce8.gif)


Additionally, I would like to draw your attention:
I didn't find the "add_p7m_vcf_attach" option in the plugin configuration GUI. Perhaps this is a bug or was it intended?
![Screen-5](https://user-images.githubusercontent.com/25282194/115830064-755afe00-a418-11eb-953b-cc4e55b1af15.jpg)

**Comment by cleidigh** [comment]
@aterrion 
this functionality was already in the extension when I adopted it.
my guess is that it was added for someone without ever making it
available in the UI
I can do that in the next maintenance drop
Christopher

**Comment by cleidigh** [comment]
@aterrion 
b2  this implemented under attachment options
any improvement shown on the localization for Russian/Ukrainian welcome!

https://github.com/cleidigh/printing-tools-ng/blob/v2.0.6/xpi/printing-tools-ng-2.0.6-b2-tb.xpi

Christopher

**Comment by cleidigh** [comment]
Fixed with v2.0.6
