### ISSUE TITLE
Print selection only

### ISSUE THREAD

**Issue by robertlover** [cleidigh/printing-tools-ng#74]
Hello,
in thunderbird i have configured two profiles, in use for many years.
In profile one the "print selection only" option works fine, in profile two it doesn't work?
Thunderbird v. 78.10.2 
Printng-tools-ng v. 2.0.5
Thank you

**Comment by kiki-ja** [comment]
@robertlover 

See previous solved cases.

"Print selected text only" not working in Thunderbird 78.9
https://github.com/cleidigh/printing-tools-ng/issues/62

**Comment by RRoenn** [comment]
maybe you can try this? from https://github.com/cleidigh/printing-tools-ng/issues/8

delete the *.msf files ...

> 
> 
> Just to confirm the problem is fixed. Found the culprit. The mistake I was making when transferring my old inbox and old sent files was that I was also transferring the inbox.msf and sent.msf files.
> The trick is to transfer just the inbox and sent files and let the system re-build the msf files.
> @kiki-ja correctly pointed this out.
> 
> So now I can print selection without any problem.
> Thank you all for your assistance!
> @cleidigh

**Comment by robertlover** [comment]
I followed the advice contained in your posts, but without success.
I copied the profile (all inclusive) to another PC and it works without problems (same program and extension versions)

**Comment by kiki-ja** [comment]
@robertlover 

You mean the results are different on different PC even though they have the same profile?
I do not know the cause.

I have a guess.
This is a case where the location of the "profile 2(two)" in question is different from the local location.

So I ask you the following question. Please tell me.

1. Where do you keep the "profile 2(two)" in question?
If it is somewhere other than local (PC) such as online storage (Server, OneDrive, Google Drive, Dropbox, etc)?

2. Is the "profile 2(two)" in question using online synchronization?

3. Where do you keep the "profile 1(one)" that worked fine?
Is it the default location for Thunderbird on your PC?

4. Does the "profile 1(one)" that worked fine use online synchronization?

ーーーーーーーーーーーーーーーーーーーーーー
Putting Thunderbird profiles and messages in online storage can cause inconsistencies and corruption of index files (.msf).
The same applies to the use of online synchronization.
I asked this question to consider this possibility.
ーーーーーーーーーーーーーーーーーーーーーー

**Comment by robertlover** [comment]
@kiki-ja 

Sorry for the delay,

on both PCs the profiles are in the standard position:  C:\Users\xxxxxx\AppData\Roaming\Thunderbird\Profiles

**Comment by kiki-ja** [comment]
@robertlover 

Thank you for your answer.
I understand the location of the profile.

Please answer my questions 2 and 4 as well.

**Comment by robertlover** [comment]
@kiki-ja

**Comment by robertlover** [comment]
@kiki-ja 

the profiles are identical. I simply copied the problematic profile (friend's PC) to another PC (my PC). On PC 2 it works without problems. local profile, imaps account, No online synchronization used.

**Comment by kiki-ja** [comment]
@robertlover 

I understand that you are not using online synchronization.

Here are some other possible problems.
Do any of them apply to you?

　１．Your friend's PC and your PC have different operating systems or OS versions.
　２．The versions of Thunderbird on your PC and your friend's PC are different.
　３．When you copied the profile, you overwrote it.

**[Solution]**
　1.To be sure, reinstall Thunderbird on your PC.
　　**Caution:** Do not delete the profiles at all. As this will eliminate any problems with Thunderbird itself.
　2.Create a new profile in Thunderbird on your PC.
　3.Set up an IMAP account and install only PrintingTools NG 2.0.6.
　4.Synchronize and receive IMAP accounts to see if they work properly.

This is one of the basic troubleshooting steps.

**Comment by querixg** [comment]
I often want to print selected text only, combined with the header, and to have attachments listet compactly. So I've been very glad finding Printing Tools adapted to newer versions of Thunderbird.

But unfortunately printing selected text only didn‘t work till after a very time-consuming series of tests I have now realized, that it is valid only when the selection is done in the message pane or in a tab.

Since I've been used for many years to having the message pane deactivated and to opening a mail in a new window rather than in a tab, trying to print selected text only has been futile. (Moreover: if some text is selected in the message pane and the mail is opened in a new window and some text selected there too, the text selected in the message pane is printed and not the text selected in the window.)

May I call this a bug? Since workaround is simple - before selecting text open the mail in a tab - perhaps this observation helps others who didn't succed in printing selected text only.

(Hopefully I've used the correct terminology. I'm using Thunderbird in german.)

**Comment by kiki-ja** [comment]
@querixg 

>But unfortunately printing selected text only didn‘t work till after a very time-consuming series of tests I have now realized, that it is valid only when the selection is done in the message pane or in a tab.

I have also reproduced and confirmed the same.

Windows 10 Pro 21H1 64bit
Thunderbird 78.12.0 64bit

When I opened the message in a window, I could not print just the selected text.
Now it prints the full message.

@robertlover 

Is your case the same as this?

**Comment by robertlover** [comment]
> @querixg
> 
> > But unfortunately printing selected text only didn‘t work till after a very time-consuming series of tests I have now realized, that it is valid only when the selection is done in the message pane or in a tab.
> 
> I have also reproduced and confirmed the same.
> 
> Windows 10 Pro 21H1 64bit Thunderbird 78.12.0 64bit
> 
> When I opened the message in a window, I could not print just the selected text. Now it prints the full message.
> 
> @robertlover
> 
> Is your case the same as this?

sorry for the delay, 
opening messages in a tab solves the problem, 
thank you very much

**Comment by cleidigh** [comment]
@robertlover 
Have you checked out v2.1.0
Also working on multiple selections, see #99 
@cleidigh
