### ISSUE TITLE
Merging Thunderbird profiles

### ISSUE THREAD

**Issue by decroft** [cleidigh/printing-tools-ng#75]
I have two separate profiles and I want to merge them. Your import does not import Thunderbird emails and folders, correct? So first I have to export from one profile to eml files and then import to the other? Do I export to one directory or one file? 

Will this keeps all the emails in the correct folders on exporting? 
If there are two folders with same name does it just combine into one after the merge?

Also, since you know Thunderbird, where can I get a detailed explanation of what the each entry in Profile.ini means?

Thanks for the help,
Doug

**Comment by cleidigh** [comment]
@decroft 
thanks for posting!  I'm messed up, I gave you wrong link, duh!
I will create this issue in the right repository and we troubleshoot there
Christopher

**Comment by cleidigh** [comment]
see new issue:
https://github.com/thundernest/import-export-tools-ng/issues/240
 Christopher
