### ISSUE TITLE
First page is empty with portrait format but not with landscape format 

### ISSUE THREAD

**Issue by RRoenn** [cleidigh/printing-tools-ng#78]
Hello @cleidigh

I got an email with around 5 to 6 pages. If I print in standart portrait format the first page is empty except the header. The content is printed at the second page. If I print the same email in landscape format, the printout is normal. Printing without the addon looks normal.

Maybe you can have a look?

Greetings from Germany
RRoenn

**Comment by kiki-ja** [comment]
@RRoenn 
@cleidigh 
and All.

This is my report.
I can't reproduce it in my environment.

Windows 10 Pro 64bit 21H1
Thunderbird 78.11.0 64bit
PrintingTools NG 2.0.6

Here are some questions to make the problem more specific.
1. Does it happen with all the same few pages of other messages?
2. Does the problem only occur with messages from a specific sender?
3. Are the messages in plain text or HTML?
4. Does it reproduce with a new profile in Thunderbird?
5. Can I save the message in eml format and attach it here as a compressed file in zip or 7z format?
Caution: Naturally, you should mask any privacy information.

**Comment by RRoenn** [comment]
Below are my answers

> Here are some questions to make the problem more specific.
> 
>     1. Does it happen with all the same few pages of other messages?
No, just a few messages. Maybe 4 to 6 a year from more than 40.000

>     2. Does the problem only occur with messages from a specific sender?
No

>     3. Are the messages in plain text or HTML?
HTML

>     4. Does it reproduce with a new profile in Thunderbird?
Not tried yet

>     5. Can you save the message in eml format and attach it here as a compressed file in zip or 7z format?
>        Caution: Naturally, you should mask any privacy information.
Message size is about 20mb. I will try to rip privacy information and also attachments. I will see, if the problem occurs with a smaller sample message.

I am going to holiday soon. I am back end of july. I will try a new profile and make a sample message in this time.

**Comment by kiki-ja** [comment]
@RRoenn 
@cleidigh 
and All.

Thank you very much for your answer.
The following is a summary of the characteristics of the messages that are causing the problem.

１． Not all of the messages on pages 5 to 6.
2. Only a few specific messages.
3. They are not from a specific sender.
4. The message is HTML format.
5. The size of the message is about 20MB.

Finding the differences between the messages that cause problems and those that don't may give you some clues.
Put them in source view (Ctrl + U) and try to find the differences.

[Example of difference checkpoints]
#There are many line breaks and blank lines.
#The presence of attachments.

We are still waiting for your confirmation results with the new profile and sample messages where the problem occurs.
You can do it after your vacation.

**Comment by cleidigh** [comment]
@RRoenn 
any update on this?
Christopher

**Comment by RRoenn** [comment]
Hello @cleidigh @kiki-ja 

same result with new profile. Please see sample message attached.
I stripped the attachments and content. 
If I delete or shortened one of the lines in the html content, the message will show correctly.
So I replaced almost every char with a 'x'.

[SampeMail.zip](https://github.com/cleidigh/printing-tools-ng/files/6975157/SampeMail.zip)

**Comment by kiki-ja** [comment]
@RRoenn 
@cleidigh 

>same result with new profile.

Thank you for the result report. I understand.

>If I delete or shortened one of the lines in the html content, the message will show correctly.

Thank you for attaching the sample message.
It was displayed correctly on my end as well.

However, I was not able to reproduce the phenomenon in question.
Is it because of the structure of the HTML message, or is it because of PrintingTools NG?
Were you able to isolate which was the cause?

Again, can you attach a sample message that reproduces the problem?

**Comment by cleidigh** [comment]
@RRoenn 
I think this can be closed?
@cleidigh

**Comment by RRoenn** [comment]
Hello @cleidigh 
I will test again till end of next week. Thank you

**Comment by RRoenn** [comment]
just tested SampleMail with tb 91.7.0-bit and PTNG v2.1.1-b3 ... can't reproduce the issue.
