### ISSUE TITLE
Mail Date (short native) changed to US/UTC format unwantedly

### ISSUE THREAD

**Issue by calteTM** [cleidigh/printing-tools-ng#83]
**With v2.06 the short(native) date format in the mail header is changed to US/UTC format (08/26/2021 16:37) which is unwanted for us (computer A)**
On another computer with the same setup but with V.2.0 the format is shown according the system entries, correctly (26.08.2021, 16:37/ TB system language is english) (computer B)

Rem1: If I deactivate the addon on computer A, the format is shown according the system (26.08.2021, 16:37)
Rem2: If I change TB system language to german on computer A, v.206 shows the format correctly

We are running:

- TB 78.12.0
- PrintingToolsNG - V2.00 or V2.06

Thanks for your support

**Comment by cleidigh** [comment]
@calteTM 
v2.1.1 will have a custom date option to address this.

- #105 

@cleidigh
