### ISSUE TITLE
Can't find Print Preview function

### ISSUE THREAD

**Issue by KennyReff** [cleidigh/printing-tools-ng#84]
Hi.  I installed Printing Tools NG into TB v78.13.0 specifically for its print preview function, which TB is lacking.

The developer messaged me that, "Print Preview is available both on the message Context and the file menus," but I can't for the life of me find the button. Screen shots attached showing the TB file menu and the context bar at the top of the message.

Thanks!

<img width="342" alt="Screen Shot 2021-08-31 at 5 42 25 PM" src="https://user-images.githubusercontent.com/89876977/131579715-7b38f937-3088-4552-b453-4a25860f3867.png">

<img width="919" alt="Screen Shot 2021-08-31 at 5 42 40 PM" src="https://user-images.githubusercontent.com/89876977/131579725-0c9ded11-7d6c-414a-9cc5-1103e11f5346.png">

**Comment by cleidigh** [comment]
@KennyReff 
ahh you are on OS X , always give this Information
you can do to preview from
the sprinter dropdown

![image](https://user-images.githubusercontent.com/25272315/131732979-4efd6408-e483-4a9e-a1c7-3e8adcddcdd3.png)

**Comment by cleidigh** [comment]
for 78 I believe that is the only  solution
I have not beenn able to try 91
for  windows there is a new preview
the priinting engine also  is new
This should help with shreedded several
 issues
