### ISSUE TITLE
Export messages from search dialog not working well

### ISSUE THREAD

**Issue by HansVorrink** [cleidigh/printing-tools-ng#85]
Thank you for this extremely useful addon. 
I have found an issue using the 'Export messages from search dialog' if the export function of the 'only selected messages' is used. No email is exported, nothing happens. If I choose the export function 'all' email is exported to the folder of my choice correctly. I am using Thunderbird 78.14.0 (32 bits) and ImportExportTools NG version 10.0.4
Any ideas what I'm doing wrong or is this a bug? Regards

**Comment by jobisoft** [comment]
Please check if this is also broken in v11.0.

**Comment by HansVorrink** [comment]
After updating to Thunderbird v. 91.3.1 and ImportExportTools NG version 11.1 the exporting function works well.

Thank you and regards
