### ISSUE TITLE
Image resize alters some styling resulting in img issues

### ISSUE THREAD

**Issue by garyhooper** [cleidigh/printing-tools-ng#86]
In the email message below (generated from the Apple store), the Apple logo is displayed twice when printing, but only once (as expected) when viewing the message.

See [Apple.eml.zip](https://github.com/cleidigh/printing-tools-ng/files/7360717/Apple.eml.zip).

**Comment by cleidigh** [comment]
@garyhooper 
Have you tried v2.1.0?
@cleidigh

**Comment by garyhooper** [comment]
v2.1.0 still fails.

**Comment by cleidigh** [comment]
@garyhooper 
I reopened this...
@cleidigh

**Comment by cleidigh** [comment]
@garyhooper 
The apple.eml file is a binary file not eml/text. Perhaps it was exported in the wrong format?
@cleidigh

**Comment by garyhooper** [comment]
The attached file is a zip of an exported email message.

**Comment by garyhooper** [comment]
The attached is a zip file created on a Mac: [Apple.eml.zip](https://github.com/cleidigh/printing-tools-ng/files/8468884/Apple.eml.zip)

**Comment by cleidigh** [comment]
@garyhooper 
Got it, thanks 
@cleidigh

**Comment by cleidigh** [comment]
@garyhooper 
I reproduced the double image. This occurred with the image resizing option where the original styling manipulation was altering more than it should have.
There were also some new Thunderbird behaviors to take into account.
I will post b10 later and you can test it by downloading.  I will have this in the v2.1.1 release.
Thanks for the catch.
@cleidigh

**Comment by cleidigh** [comment]
@garyhooper 
You can give b10 a try. It deals with hide and resize restoring things to avoid the duplicate images.
Pointer in the release status : 
#106 
@cleidigh

**Comment by garyhooper** [comment]
This corrects it.  Thanks!

**Comment by cleidigh** [comment]
Great, closing.
