### ISSUE TITLE
Add option to hide or show individual headers

### ISSUE THREAD

**Issue by SkatingDodger** [cleidigh/printing-tools-ng#9]
Just tried it today - works great.  Possible suggestion - I mainly use it to prevent headers being printed but it would be handy to have the option to put the date at the top.  I tried the option to 'Add received date' but it doesn't appear when headers are hidden.
Would it be possible to either add the date independently of headers at the top, or select which items in the header are to be printed. You already have an option to order the header items.  Thank you for a very useful program.

**Comment by cleidigh** [comment]
@SkatingDodger 
Thanks for the support, glad the extension is useful!
I am furiously working on several other extensions so it will probably be a bit before I can circle back around
for future improvements.  What I do frequently is post minor unofficial updates for trial versions.
I might be able to squeeze something like that in.

For clarification:
- The generalized enhancement would be options to hide any of the headers
- you are not talking about the page headers/footers correct?

@cleidigh

**Comment by cleidigh** [comment]
@SkatingDodger 
managed to squeeze it in 4 2.0
check out the beta #18
happy New Year's!
Christopher

**Comment by cleidigh** [comment]
added in v2.0.0
