### ISSUE TITLE
extra item under "file"

### ISSUE THREAD

**Issue by vtrasikis** [cleidigh/printing-tools-ng#90]
When I after installing the beta, when I click on "file" there is an extra item, just below "print" that does NOTHING when I click on it...
![Screenshot - 1_3_2022 , 08_53_13](https://user-images.githubusercontent.com/1740910/147957685-bbaac462-701c-4598-a1ed-8b93663be3ab.png)

**Comment by cleidigh** [comment]
Please try b9, it is much closer to release 

@cleidigh

**Comment by cleidigh** [comment]
@vtrasikis 
can I close this with the release of v2.1.0?
@cleidigh
