### ISSUE TITLE
All headers suppressed (inc date/from/to) but leaves that space stays empty, until Destination changes (TB91, v2.0.7-b3)

### ISSUE THREAD

**Issue by JDLH** [cleidigh/printing-tools-ng#91]
This report is from PrintingTools NG beta version 2.0.7-b3 on Thunderbird 91.4.1 (64-bit) on macOS 10.14.6 Mojave. I appreciate being able to try this unfinished version. I understand that not everything works yet. I hope this report helps the developers.

I have a short email message. I want to make it into a 1-page PDF file, using Thunderbird's "Print"… "Save as PDF" feature. 

When I use the "Print"… command without Printing Tools NG, the preview shows that the message's 31 headers occupy 75% of the first page. The message body occupies only 50% of a page, bit this is split between the bottom 25% of page 1, and the top 25% if page 2. When I change the Destination setting in the Print dialogue, the preview changes to have the expected formatting, without the blank space.

**How to reproduce the bug**

1. Activate Printing Tools NG beta 2.0.7-b3.
2. Set the Printing Tools NG options, to select (check) "Hide always extended headers", and to unselect (uncheck) "Hide the headers".
2. Open the email message in Thunderbird.
3. Menu item "Print". A print dialogue appears, with a preview of the printout (or PDF to be saved).

**Observed behaviour**

1. When first it appears, the preview indicates that the printed output will consume 2 pages.
2. The top 75% of the first page, where the headers had been, is completely blank. 
3. Not even the seven special headers ("Subject" "Date" "From" "To" "CC" "BCC" Attachments, as given in the Headers order options pane of PrintingTools NG) are displayed in the print preview.
4. In the top right of the print dialogue, change the setting of the Destination drop-down menu. For instance, I change from the printer name to the "Save as PDF" entry.
5. The preview re-draws, so that the blank space is closed up, the seven special headers are displayed, and the extended headers are not displayed.
6. Press the "Save" button. Thunderbird saves a PDF file containing the email message, formatted as seen in the preview in step 5.

**Expected behaviour**
1. When first it appears, the preview indicates that the printed output will consume 1 pages.
2. The top 75% of the first page, where the headers had been, is not blank. 
3. The seven special headers are displayed, and the extended headers are not displayed.
4. This correct preview appears without changing the setting of the Destination menu, but changes to the Destination setting result in the same formatting each time.
5. Press the "Save" button. Thunderbird saves a PDF file containing the email message, formatted as seen in the preview in step 4.

**Comment by cleidigh** [comment]
@JDLH 

can you try b9, it has a completely new approach 

@cleidigh

**Comment by JDLH** [comment]
I repeated my print preview test, with Printing Tools NG version 2.0.7-b9, and with a different email message. The observed behaviour is now different than with b3, but it still does not match expected behaviour. 

**Observed behaviour (with version 2.0.7-b9)**

- When first it appears, the preview indicates that the printed output will consume 4 pages.
- All of the first page is filled with headers. All headers are displayed in the print preview.
- The headers include the seven special headers ("Subject" "Date" "From" "To" "CC" "BCC" Attachments, as given in the Headers order options pane of PrintingTools NG) plus all other headers.
- In the top right of the print dialogue, change the setting of the Destination drop-down menu. For instance, I change from the printer name to the "Save as PDF" entry.
- The preview re-draws. All of the headers, special and extended, are still displayed, with no change. The header and footer text is in a slightly different position, indicating that the PDF destination has no margin between text and edge of PDF page.
- Press the "Save" button. Thunderbird saves a PDF file containing the email message, formatted as seen in the preview in step 5.

Sorry that I cannot report everything is fixed with b9. Thank you for your work on the plug-in! I definitely look forward to it working fully.

**Comment by cleidigh** [comment]
@JDLH 
With v2.1.0 Release and so much changed under the hood,
do you still have this problem?
@cleidigh

**Comment by JDLH** [comment]
v2.1.0 is installed in my copy of Thunderbird (which is now v91.6.2, still on macOS 10.14.6 Mojave). I see the new button in the message's toolbar. I have done some print previews, and the header suppression works as expected. This is great! I have not yet tested it very much. 

Thank you for all your work on this. What I see so far is very encouraging.

**Comment by cleidigh** [comment]
@JDLH 
Great and thanks!
So close?
@cleidigh
