### ISSUE TITLE
 [cleidigh/printing-tools-ng] v2.0.7 - Thunderbird v91 compatibility - Release Status (#81)

### ISSUE THREAD

**Issue by pechh** [cleidigh/printing-tools-ng#92]
Hi there

Printing Tools NG 2.0.7-b7
OS: Windows 11Pro
Thunderbird 91.54.1 (64bit)

Printing by normal "print" selection doesn't print borders around header
Printing by "PTNG Print" in menu file works normally

still testing,

ciao

**Comment by kiki-ja** [comment]
@pechh

The same is true for us.
Please see the following Issues.
You can also leave your comments there.

v2.0.7 - Thunderbird v91 compatibility - Release Status
https://github.com/cleidigh/printing-tools-ng/issues/81

2.0.7 Beta Test Reports
https://github.com/cleidigh/printing-tools-ng/issues/80

**Comment by librelegal** [comment]
You have tested b7 (Printing Tools NG 2.0.7-b7), I do not find it here (https://github.com/cleidigh/printing-tools-ng/tree/v2.0.7/xpi), whre can I get it? 
b6 does not work for me under Linux or Windows (no frame, attachments listed at end of text, instead of the top in the frame)

**Comment by kiki-ja** [comment]
@librelegal 

>was: b6 does not work for me under Linux or Windows (no frame, attachments listed at end of text, instead of the top in the frame)
>new: b6 work for me under (linux and Windows) only with printing by "PTNG Print" in menu after turning off "show attachments inline" in the view menu


Please see below.
https://github.com/cleidigh/printing-tools-ng/issues/81#issuecomment-1025807805

**Comment by kiki-ja** [comment]
>pechh 
>Printing Tools NG 2.0.7-b7
>Thunderbird 91.54.1 (64bit)

It's probably just a simple typo.

**Comment by KC-T** [comment]
> Hi there
> 
> Printing Tools NG 2.0.7-b7 OS: Windows 11Pro Thunderbird 91.54.1 (64bit)
> 
> Printing by normal "print" selection doesn't print borders around header Printing by "PTNG Print" in menu file works normally
> 
> still testing,
> 
> ciao

Same for me.

Additionally:

The list of attachment appears at the header ass specified, but also appears at the end of the email even if the "hide inline attachmetnt" is selected. This should not be necessary.

By the way, I do not understand the function of "hide inline attachment" though it has been there for a long time.

K C

**Comment by 3LaHoonK** [comment]
Hello

@cleidigh 

There is a problem with the Version 2.0.7-b9 

Cannot choose printer and other pages and there are hidden pages

I hope to solve the problems, thank you, waiting for a reply


![image](https://user-images.githubusercontent.com/30515994/152979677-ba6545b6-18dc-473c-a1c5-1fcf88a3f360.png)

![image](https://user-images.githubusercontent.com/30515994/152979730-26a7646e-54e3-46dc-aeee-d408c4ceb47a.png)
