### ISSUE TITLE
[Feature Request] Add PTNG icon to toolbar

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#93]
@cleidigh

This is my new feature request.
But pass and through is not a problem.

- I would like to see an icon added to the Thunderbird toolbar.
  I would like to see three actions when clicking the icon: [Open PTNG Options Dialog], [Open Print Preview], and [Print].

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh 

Addition.
It would be nice to have an icon for the "Header View Toolbar" as well.

![Header View Toolbar](https://user-images.githubusercontent.com/80428201/154053280-9e9d79f3-173a-4ae2-bd12-6ddee03e1e66.png)

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
@reinerblock

Sorry,but I am trying to get to the  same view without luck 
can either of you give me the info to get these views?
I will see how difficult it is.
I don't think that they are customizable in the standard ways

@cleidigh

**Comment by reinerblock** [comment]
The header toolbar can be activated by using the context menu, as illustrated by the screenshot below.

![grafik](https://user-images.githubusercontent.com/5745579/154122823-c6d48f84-a1e7-490d-81a7-c8d11799a9af.png)

Additionally, I use SmartTemplates.

![grafik](https://user-images.githubusercontent.com/5745579/154122978-308181ca-f148-435a-8455-12454a3150f7.png)

And Message Header Toolbar Customize.

![grafik](https://user-images.githubusercontent.com/5745579/154123071-2da7f52e-ae15-4721-af91-5ecbf655eeca.png)

**Comment by kiki-ja** [comment]
@cleidigh 
ALL

As you said, the standard way seems to be difficult.
The following bugs may be helpful.

1556261 - Re-Implement message header toolbar customisation to add and remove buttons (feature removed in 69+)
https://bugzilla.mozilla.org/show_bug.cgi?id=1556261

The following add-ons will allow you to customize it.
I hope this will be helpful.

Message Header Toolbar Customize : Add-ons for Thunderbird
https://addons.thunderbird.net/thunderbird/addon/msghdr-toolbar-customize/

@kiki-ja

**Comment by cleidigh** [comment]
@reinerblock
I may be dense...
what window is this? It does not look like the 3 pane?
i cannot get a context menu 

do i need an extension?
how  does the template extension relate?
@cleidigh

**Comment by reinerblock** [comment]
Does this explain it?

![grafik](https://user-images.githubusercontent.com/5745579/154133699-0fd4208a-4571-492f-8f31-37af2bca1c06.png)

**Comment by reinerblock** [comment]
I just added the explanation of the add-ons why my header toolbar looks a little different compared to the default one.

**Comment by cleidigh** [comment]
i can see your 3 pane view and that looks like my normal view 
does the hdr bar add on add the ctx menu?
did i miss your explanation somewhere?

**Comment by cleidigh** [comment]
I installed the extension and I get the customize ctx menu 
it only allows adding a few icons I do not even see the regular tb print?

@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh 
All

This is an explanation of the difference between the standard mode operation of Thunderbird and the operation using add-ons.

**In the case of Thunderbird's standard mode.**
Troubleshooting Mode (formerly Safe Mode)
1.Click the More icon button.
2.The Pulldown menu will appear.
There is no context menu.
![Header Toolbar - More Menu](https://user-images.githubusercontent.com/80428201/154149708-9532def4-6511-47b1-9c58-28ebe3e78397.png)

**Next, let's look at the Message Header Toolbar Customize Add-on.**
1.Click the [∨] buttun (More actions) of the Header Toolbar. 2.
2.Click Customize Toolbar.
3.The Message Header Toolbar Customize window will appear.
　　Here, you can control the icon Hide, Up, Down, etc.
![Message Header Toolbar Customize 02](https://user-images.githubusercontent.com/80428201/154149758-7bcb72c4-84c2-4810-ba4a-7c379694f6b8.png)

Currently, the print icon button in Thunderbird only allows standard printing.
So you can either integrate the PTNG print menu there, or add a new PTNG print menu button.
My wish is to **add a PTNG print menu button**.

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh 
All

>it only allows adding a few icons I do not even see the regular tb print?

There is no print icon button on the header toolbar by default in Thunderbird.
Only the "Print" pull-down menu is available.
Using the Message Header Toolbar Customize Add-on will add a "Print" button.

Reference: from the author's blog
h.ogi blog: New functionalities of Message Header Toolbar Customize 2.1.0
https://hogiblog.blogspot.com/2020/10/new-functionalities-of-message-header.html
>Star and Print Buttons
>This feature is new in v2.1.0 Beta5.
> 
>Star and Print buttons are added to the message header toolbar. Please note the buttons are hidden by default. 

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh 
All

Reference Information:

"Allow HTML Temp" add-on adds its own icon button to the header toolbar.
You may be able to do this by using the methods of this add-on.

![Allow HTML Temp icon buttun](https://user-images.githubusercontent.com/80428201/154258672-baa3c813-903a-40ca-8784-7f0cb57336fa.png)

Allow HTML Temp :: Add-ons for Thunderbird
https://addons.thunderbird.net/thunderbird/addon/allow-html-temp/

Allow HTML Temp - Add-on to allow HTML (only) temporarily - Thunderbird Mail DE
https://www.thunderbird-mail.de/lexicon/entry/226-allow-html-temp-add-on-to-allow-html-only-temporarily/

ThunderbirdMailDE / Allow HTML Temp · GitLab
https://gitlab.com/ThunderbirdMailDE/allow-html-temp

@kiki-ja

**Comment by reinerblock** [comment]
As does [SmartTemplates](https://addons.thunderbird.net/en-US/thunderbird/addon/smarttemplate4/?src=ss)

**Comment by cleidigh** [comment]
great I will look into it and see how much work 
I really would like to release by end of the week 
@cleidigh

**Comment by cleidigh** [comment]
Ask and we deliver....


![image](https://user-images.githubusercontent.com/25272315/154616316-dabcbf1d-3c32-4948-b8ee-5ed103fb5f1a.png)

**Comment by kiki-ja** [comment]
@cleidigh 
All

That's fantastic!
Thank you very much.

@kiki-ja

**Comment by KC-T** [comment]
Tested b15 on 91.6.1 Windows 11.
Presently it suits my need but there are random problems found:

1. A particular email containing 6 attachments which can be previewed the first time cannot be previewed the second time, but other emails with less or more attachments of bigger sizes can be previewed more than once. If Thunderbird is restarted, that particular email can be previewed, but the same problem still exists. This may be a cache problem. I also feel that there are some time delay when previewing some emails.
2. The user name before the headers is repeated for several times occasionally.
3. The attachment list which should appear at the end of the email appears after the bordered headers occasionally when the print-NG button on the tool bar is used.
4. The border around headers disappears during preview when the page size is changed by scrolling through the list of page sizes. Luckily, this does not affect the normal page sizes that I use.
5. "occasionally" means the phenomenon does not appear every time.

1. 6.

**Comment by KC-T** [comment]
By the way, can someone tell me where the Page Setup has gone. Cannot find it from Thunderbird 91.

**Comment by KC-T** [comment]
The particular email that I mentioned does not have any recipients included in the "To:" field.

I have tested Chinese (China) and Chinese (Taiwan). Both have the attachment list included in the headers. The order of the other header items are not as defined. Both have not used the "Cc" and "Bcc" abbreviations. The order of Chinese (China) follows the defined order partially. The order of Chinese (Taiwan) follows the default Thunderbird order.

**Comment by kiki-ja** [comment]
@cleidigh 
All

If there is no problem with the PTNG toolbar button, I think this issue can be closed.
I will send you the corrected Japanese translation for localization.
I will also test the issue reported by @KC-T.

@kiki-ja

**Comment by kiki-ja** [comment]
@KC-T

>Windows 11.

Thunderbird 91.0 series does not officially support Windows 11.
This may cause unknown problems.
Please refer to the system requirements below.

Thunderbird — 91.0 System Requirements — Thunderbird
https://www.thunderbird.net/en-US/thunderbird/91.0/system-requirements/

I do not reproduce 1.-4. problem.

Is it the case that the problem occurs with a particular message, or a particular attachment?
Does deleting the cache solve the problem?
Is there a difference in the receiving server (POP, IMAP)?
Is this happening only with the PTNG toolbar button?

It will take some time before the print preview is displayed under the following conditions.
- Large size messages
- IMAP account with synchronization only + large size messages

This is also the case for the normal print preview in Thunderbird.
Does this case apply to you?

Either way, find a condition that you can reproduce.
If you don't, you won't find a way to solve the problem.

@kiki-ja

**Comment by kiki-ja** [comment]
@KC-T

>The particular email that I mentioned does not have any recipients included in the "To:" field.

Is this the same issue as the previous comments below?
https://github.com/cleidigh/printing-tools-ng/issues/79#issuecomment-877627047

If it's the same, I think it's better to create a new issue.
The reason is that it doesn't seem to have anything to do with the PTNG toolbar button.
In Thunderbird's normal printing, you can print messages without the "To" field in the header.

@kiki-ja

**Comment by kiki-ja** [comment]
@KC-T

>By the way, can someone tell me where the Page Setup has gone.
>Cannot find it from Thunderbird 91.

What is Page Setup?
Is it the system dialog for printing shown in the screenshot below?

![The Page Setuo Dialog](https://user-images.githubusercontent.com/80428201/155997258-330f4c46-5c14-4bc5-8ed5-d366bf1a4a17.png)

@kiki-ja

**Comment by RRoenn** [comment]
I think you mean this?
(Sorry, only german. no time)


Es gibt in Hamburgermenü -> Einstellungen -> Allgemein -> Konfiguration bearbeiten
u.a. folgende Schlüssel, global und für jeden installierten Drucker
einzustellen, (einige Beispiele)

print.print_footercenter &P (einfache Seitennummerierung unten mitte)
print.print_footerleft
print.print_footerright &D (Druckdatum unten rechts)
print.print_headercenter
print.print_headerleft &T (Titel oben links)
print.print_headerright

https://www.borncity.com/blog/2021/02/24/firefox-86-0-0-und-78-8-0-esr-verfgbar/#comment-101552

![8XUZtIU](https://user-images.githubusercontent.com/77779094/156000501-99edbf68-a658-4657-a6d0-670c165a2585.png)

**Comment by tidebre67** [comment]
> By the way, can someone tell me where the Page Setup has gone. Cannot find it from Thunderbird 91.

> 

guess you are talking about this:
![Screenshot 2022-02-28 172811](https://user-images.githubusercontent.com/44371934/156022535-cbb877fd-1b0a-49e9-9275-2867a3b2a321.png)
![Screenshot 2022-02-28 172836](https://user-images.githubusercontent.com/44371934/156022646-129dde9c-64fd-4c7a-814f-e2d00ab8c4e9.png)

it looks that is not part of TB 91 any longer unfortunately.

**Comment by kiki-ja** [comment]
@KC-T

About Page Setup.

The print dialog has been integrated into preview windows since version 91.
"Print using the system dialog..." is also available.
Please see the help article below.

>_Improved:_ Printing has just become better: The new print dialog inherited from the Mozilla platform combines printing, print preview, and print settings in a single, simplified user interface. Or you can still use your system's print dialog if you prefer that. 

"New one-stop print dialog with integrated preview and settings / New in Thunderbird 91 | Thunderbird Help"
https://support.mozilla.org/en-US/kb/new-thunderbird-91#w_new-one-stop-print-dialog-with-integrated-preview-and-settings

It is also in the release notes.

>- CHANGED  Printing UI updated

"Thunderbird — Release Notes (91.0)"
https://www.thunderbird.net/en-US/thunderbird/91.0/releasenotes/

@kiki-ja

**Comment by KC-T** [comment]
@tidebre67 
Yes, those are the Page Setup I was looking for,

@kiki-ja 
I could not find the Page Setup settings in the new print dialog.
For the occasional problems that I have reported before, I would continue to observe and tell the exact occasions when the problems arise. 

@RRoenn 
Thank you for telling me that the page setup has been moved to be defined in the Config.

**Comment by KC-T** [comment]
> I have tested Chinese (China) and Chinese (Taiwan). Both have the attachment list included in the headers. The order of the other header items are not as defined. Both have not used the "Cc" and "Bcc" abbreviations. The order of Chinese (China) follows the defined order partially. The order of Chinese (Taiwan) follows the default Thunderbird order.

I hope that these locale problems can be resolved.

**Comment by kiki-ja** [comment]
@KC-T

>I could not find the Page Setup settings in the new print dialog.

**Do you understand** that this is due to a **specification change in version 91.0** series?
It is **not directly related to PrintingTools NG** 2.0.7.
**Do you also understand** that it has **nothing to do with #93**?

>For the occasional problems that I have reported before, I would continue to observe and tell the exact occasions when the problems arise.

If the issue topic has already been reported, **please post it there**.
**This issue** topic is "**[Feature Request] Add PTNG icon to toolbar" for PTNG 2.0.7 beta**.
Please **do not post unrelated** issues.
The reason for this is that it would be off topic and confusing.

>I hope that these locale problems can be resolved.

If it is a new issue, **please create a new issue**.

@kiki-ja

**Comment by kiki-ja** [comment]
@reinerblock
@tidebre67
@KC-T
@RRoenn
All

If there are no new problems, this issue topic will be closed.
Thank you @cleidigh and everyone.

@kiki-ja

**Comment by cleidigh** [comment]
@KC-T 
You have multiple great test results which appear to be edge conditions.
If you can create the separate issues and details to reproduce I will try to determine if we can fix now or if we will address in a point revision.
@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
all

As this is one of our nice new features I think I will charge the install note, can I get translation help from my good Japanese and German friends and any other languages?

Note: Try out the new PrintingTools NG toolbar button, use the View\Toolbars\Customize menu to add it to your toolbar.

@cleidigh

**Comment by cleidigh** [comment]
@KC-T 
If you can create an issue on the ZN and ZN(TW)
with any specific examples and screen shots that would be helpful.
I just did some checking and it looked correct in ZN(cn)
I  do not have the ZN(tw) locale so I don't know how that would even work
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

I will be happy to help with the Japanese translation.

>Note: Try out the new PrintingTools NG toolbar button, use the View\Toolbars\Customize menu to add it to your toolbar.

Ａｄｄ：
You can add it to the header toolbar of the message pane as well.

Japanese translation:
"PrintingTools NG の新しいツールバーボタンをお試しください。ツールバーのカスタマイズメニューからツールバーに追加してください。
メッセージペインのヘッダーツールバーにも同様に追加できます。"

@kiki-ja

**Comment by tidebre67** [comment]
> As this is one of our nice new features I think I will charge the install note, can I get translation help from my good Japanese and German friends and any other languages?
> 
> Note: Try out the new PrintingTools NG toolbar button, use the View\Toolbars\Customize menu to add it to your toolbar.
> 
> @cleidigh

Christopher, propose the fllwg:
Note:
probieren Sie den neuen PrintingTools NG toolbar button, zu finden wie folgt:
Ansicht >> Symbolleisten >> Anpassen und  füge 'Drucken NG' zur Symbolleiste hinzu.

@tidebre67
